<script setup lang="ts">
// The explorer: every provider, every operation, and an honest account of what stands in the way.
//
// The headline count is the number of operations that own a defect. It is **not** "N of 25 working":
// `works` is false for all 25 today because the auth seam has not landed in flux, and a site that
// made 20 operations working exactly as designed look broken would be as dishonest as one that hid
// the five real gaps.
//
// So the presentation follows `scope`, which the emitter puts on every issue for this reason:
//
//   catalog  → a banner here, above everything
//   provider → a banner on that provider's card
//   operation → a badge and the reason, on the operation, wherever it appears

import { computed } from 'vue'
import { withBase } from 'vitepress'
import {
  allOperations,
  catalogIssues,
  defectCount,
  type Catalog,
} from '../../../data/catalog.mts'
import IssueNotice from './IssueNotice.vue'
import OperationList from './OperationList.vue'
import ProviderCard from './ProviderCard.vue'

const props = defineProps<{ catalog: Catalog }>()

const operations = computed(() => allOperations(props.catalog))
const defects = computed(() => defectCount(operations.value))
const wide = computed(() => catalogIssues(props.catalog))
</script>

<template>
  <p class="summary" :data-defect-count="defects">
    <strong>{{ catalog.providers.length }}</strong> providers ·
    <strong>{{ operations.length }}</strong> operations ·
    <strong>{{ defects }}</strong> with a defect of their own.
    Generated by <code>{{ catalog.generator }}</code> — every field on this page comes from
    <a :href="withBase('/catalog.json')">catalog.json</a>, which the build emits from the same IR as
    the <code>.flux</code> modules.
  </p>

  <IssueNotice
    title="Affects every operation in the catalogue"
    tone="inherited"
    banner="catalog"
    :issues="wide"
  />

  <h2 id="providers">Providers</h2>
  <div class="providers">
    <ProviderCard
      v-for="provider in catalog.providers"
      :key="provider.id"
      :provider="provider"
    />
  </div>

  <h2 id="operations">Operations</h2>
  <OperationList :providers="catalog.providers" />
</template>

<style scoped>
.summary {
  font-size: 14px;
  color: var(--vp-c-text-2);
}

.providers {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
  gap: 16px;
  margin: 16px 0;
}
</style>
