//! The generated catalog data, one module per provider.
//!
//! Generated by flux-connectors 0.5.0 — do not edit. Regenerate with `flux-connectors build`.
//!
//! **A whole-catalogue artifact**, and therefore written by a *full* build only: an index
//! rendered from `build --provider zendesk` would name one provider and silently drop the
//! rest. `web/public/catalog.json` follows the same rule for the same reason
//! (`docs/designs/catalog-json.md`). The corollary is the point of C-104 — a provider-scoped
//! build writes only that provider's own files, so provider work fans out instead of
//! serialising on this one file.
//!
//! `crates/catalog/tests/embedded_operations.rs` holds this list against `providers/`, and
//! `crates/connector-cli/tests/catalog_artifacts.rs` holds the whole tree to being a fixed
//! point of a build, so a stale index is loud rather than silent.

pub(crate) mod airtable;
pub(crate) mod asana;
pub(crate) mod babelforce;
pub(crate) mod fly;
pub(crate) mod freshdesk;
pub(crate) mod github;
pub(crate) mod google;
pub(crate) mod hubspot;
pub(crate) mod intercom;
pub(crate) mod jira;
pub(crate) mod notion;
pub(crate) mod openai;
pub(crate) mod openrouter;
pub(crate) mod sentry;
pub(crate) mod shopify;
pub(crate) mod slack;
pub(crate) mod stripe;
pub(crate) mod zendesk;
pub(crate) mod zoom;

use crate::Provider;

/// Every provider, ordered by id — the order [`crate::providers`] publishes and the order the
/// catalog's flat listing walks.
#[rustfmt::skip]
pub(crate) static PROVIDERS: &[&Provider] = &[
    &airtable::PROVIDER,
    &asana::PROVIDER,
    &babelforce::PROVIDER,
    &fly::PROVIDER,
    &freshdesk::PROVIDER,
    &github::PROVIDER,
    &google::PROVIDER,
    &hubspot::PROVIDER,
    &intercom::PROVIDER,
    &jira::PROVIDER,
    &notion::PROVIDER,
    &openai::PROVIDER,
    &openrouter::PROVIDER,
    &sentry::PROVIDER,
    &shopify::PROVIDER,
    &slack::PROVIDER,
    &stripe::PROVIDER,
    &zendesk::PROVIDER,
    &zoom::PROVIDER,
];
