//! **The README's image is a checked artifact** (C-45).
//!
//! Before this story the image was generated by a script nothing ran and nothing verified: its own
//! docstring said "the output is a GENERATED ARTIFACT and nothing yet checks it for drift". So the
//! README could show Flux the compiler had stopped emitting and no test would notice.
//!
//! Two properties close that, and both are asserted against the real repository rather than a
//! fixture, because the thing under test is what a reader of this README sees:
//!
//! 1. [`the_snippet_is_verbatim_from_the_generated_module`] — the source the image renders is
//!    lifted out of `connectors/zendesk.flux` character for character, so the README cannot disagree
//!    with the compiler about what it emits.
//! 2. [`a_build_plans_both_readme_images_and_they_are_current`] — both SVGs travel through
//!    [`pipeline::plan`], which makes them subject to everything the pipeline already guarantees:
//!    `build` rewrites them, `diff` reports them stale, and a rebuild over unchanged inputs writes
//!    nothing.

use std::path::{Path, PathBuf};

use connector_cli::pipeline;
use connector_cli::workspace::Workspace;

/// The operation the README shows, named once.
const SNIPPET_OPERATION: &str = "zendesk-ticket-comment-add";

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("the repository root exists")
}

fn read(relative: &str) -> String {
    let path = repo_root().join(relative);
    std::fs::read_to_string(&path).unwrap_or_else(|error| {
        panic!("cannot read {}: {error}", path.display());
    })
}

/// **The snippet is the compiler's output, not a retelling of it.**
///
/// A hand-kept copy would drift the moment the emitter changed a symbol name or a body path — and
/// the README is where a reader decides whether this project's output is worth trusting.
#[test]
fn the_snippet_is_verbatim_from_the_generated_module() {
    let snippet = read("assets/readme-snippet.flux");
    let module = read("connectors/zendesk.flux");

    assert!(
        snippet.starts_with(&format!("op {SNIPPET_OPERATION}(")),
        "the snippet must be the `{SNIPPET_OPERATION}` declaration, got:\n{snippet}"
    );
    assert!(
        module.contains(snippet.trim_end_matches('\n')),
        "assets/readme-snippet.flux is not a verbatim extract of connectors/zendesk.flux — \
         re-extract it from the `{SNIPPET_OPERATION}` declaration:\n{snippet}"
    );
}

/// **Both images are planned, and both are current.**
///
/// The staleness half is what a script can never provide: it fails the moment someone changes the
/// snippet, the emitter or the palette without rebuilding, which is precisely how the committed
/// image and the committed Flux come apart.
#[test]
fn a_build_plans_both_readme_images_and_they_are_current() {
    let workspace = Workspace::new(repo_root());
    let plan = pipeline::plan(&workspace, None).expect("every shipped provider compiles");

    let planned: Vec<String> = plan
        .artifacts
        .iter()
        .map(|artifact| {
            workspace
                .display_path(&artifact.path)
                .display()
                .to_string()
                .replace('\\', "/")
        })
        .collect();

    for theme in ["light", "dark"] {
        let wanted = format!("assets/readme-snippet-{theme}.svg");
        assert!(
            planned.contains(&wanted),
            "a build plans no {wanted}, so the README image is generated by hand again. \
             Planned artifacts:\n  {}",
            planned.join("\n  ")
        );
    }

    let stale: Vec<String> = plan
        .changes()
        .map(|artifact| workspace.display_path(&artifact.path).display().to_string())
        .collect();
    assert!(
        stale.is_empty(),
        "a rebuild would change committed artifacts — run `cargo run -p connector-cli -- build`:\n  {}",
        stale.join("\n  ")
    );
}

/// A `--provider` run leaves the images alone, for the reason `site/catalog.json` is also whole-run
/// only: the README is a document about the repository, not an artifact of one connector. Pinned so
/// the choice is a decision a reader can find rather than an accident of ordering.
#[test]
fn a_provider_scoped_build_leaves_the_images_alone() {
    let workspace = Workspace::new(repo_root());
    let plan = pipeline::plan(&workspace, Some("zendesk")).expect("zendesk compiles");

    let images: Vec<String> = plan
        .artifacts
        .iter()
        .map(|artifact| artifact.path.display().to_string())
        .filter(|path| path.contains("readme-snippet"))
        .collect();
    assert!(
        images.is_empty(),
        "a provider-scoped build planned README images:\n  {}",
        images.join("\n  ")
    );
}
