//! `connectors.lock`, and the hash domain it records.
//!
//! Two properties are the whole story, and both are here as tests rather than as intentions:
//!
//! 1. **Unchanged inputs reproduce the file byte for byte.** `flux-connectors check` (C-14) is only
//!    worth running if a clean tree is silent, so anything that varies without an input changing —
//!    a timestamp, a map's iteration order, the order providers were discovered in — would make the
//!    tool cry wolf until someone turned it off.
//! 2. **Each hash covers exactly one input.** That is what lets `check` say *which* input moved.
//!
//! The fixture is Zendesk as `docs/designs/provider-operation-inventory.md` §3 records it, run
//! through the real [`provider::load`] front-end rather than a hand-built IR, so the hashes here are
//! the hashes a build would actually record.

use connector_spec::{provider, sha256_hex, Connector, LockEntry, Lockfile, Provenance};

// ---------------------------------------------------------------------------------------------
// The fixture, and a stand-in for the parts of the pipeline this crate does not own
// ---------------------------------------------------------------------------------------------

const ZENDESK_TOML: &str = r#"
id = "zendesk"
vendor = "Zendesk"
base_url = "https://acme.zendesk.com"
description = "Zendesk Support ticketing"
default_auth = [{ credentials = ["zendesk.api_token"] }]

[[auth]]
name = "zendesk.api_token"
scheme = "basic"
env = ["ZENDESK_API_TOKEN"]
user_env = ["ZENDESK_USER"]
user_suffix = "/token"

[[operations]]
id = "zendesk.ticket.show"
method = "GET"
direction = "read"
path = "/api/v2/tickets/{ticket_id}.json"
description = "Show one ticket"
risk = "low"
idempotency = "idempotent"

[[operations.params.path]]
name = "ticket_id"
required = true
schema = { type = "integer", format = "uint64", minimum = 1 }
"#;

const SPEC: &str = r#"{"openapi":"3.0.0","info":{"title":"Zendesk","version":"1.0.0"}}"#;

/// Where [`SPEC`] sits in the cache, spelled as the two fixtures below spell `[spec] path`.
const SPEC_PATH: &str = "specs/zendesk/1.0.0.json";

const GENERATOR: &str = "flux-connectors 0.1.0";

/// The committed bytes one build reads, plus the identity of the generator reading them — every
/// input `connectors.lock` claims to cover.
struct Inputs {
    definition: String,
    spec: Option<String>,
    generator: String,
}

impl Default for Inputs {
    fn default() -> Self {
        Self {
            definition: ZENDESK_TOML.to_string(),
            spec: Some(SPEC.to_string()),
            generator: GENERATOR.to_string(),
        }
    }
}

/// The fixture definition, compiled against a cache holding [`SPEC`] at [`SPEC_PATH`].
fn load(definition: &str) -> connector_spec::LoadedProvider {
    provider::load_with_spec(
        "providers/zendesk.toml",
        definition,
        &[connector_spec::SpecDocument {
            path: SPEC_PATH,
            document: SPEC,
        }],
    )
    .expect("load")
}

/// A stand-in for `connector-flux`, doing the one thing that matters here: an artifact is a
/// function of both the IR *and* the generator that emitted it, so a generator bump has to reach
/// the artifact hash. `crates/connector-cli/src/seam.rs` stamps exactly this header today.
fn emit(connector: &Connector, generator: &str) -> String {
    format!(
        "// Generated by {generator} — do not edit.\n{}\n",
        connector.hash_domain().expect("hash domain")
    )
}

/// One provider's full trip from committed bytes to a lockfile row, as `connector-cli` will make
/// it: load the TOML **against the spec cache**, hash the spec bytes that were read off disk, emit,
/// record.
///
/// The cache is passed whether or not the definition pins anything, exactly as `seam::load` passes
/// it — a directory holding a document is not a declaration, and the two fixtures here that *do*
/// declare `[spec]` are compiled rather than skeletonised (C-421).
fn entry(inputs: &Inputs) -> LockEntry {
    let loaded = load(&inputs.definition);
    let mut connector = loaded.connector;
    connector.provenance.spec_sha256 = inputs.spec.as_ref().map(|spec| sha256_hex(spec.as_bytes()));

    let module = emit(&connector, &inputs.generator);
    let document = document(&connector, &inputs.generator);
    LockEntry::for_connector(&connector, &inputs.generator)
        .expect("lock entry")
        .with_artifact("zendesk.flux", module.as_bytes())
        .with_artifact("catalog/zendesk.catalog.json", document.as_bytes())
}

/// A stand-in for the canonical catalog document (C-536), the way [`emit`] stands in for
/// `connector-flux`: the document is the *complete* published surface in one JSON file, which is
/// exactly why its bytes carry everything the lockfile must not — the resolved endpoint, the
/// credential names, the environment keys. Recording it is safe only because the row holds a path
/// and a hash; this fixture is what lets `the_lockfile_carries_no_credential_and_no_endpoint`
/// state that against the new rows rather than assume it.
fn document(connector: &Connector, generator: &str) -> String {
    format!(
        "{{\"generator\":{generator:?},\"connector\":{:?},\"base_url\":{:?},\"auth\":{}}}\n",
        connector.id,
        connector.base_url,
        serde_json::to_string(&connector.auth).expect("auth serializes"),
    )
}

/// The rendered lockfile for one set of inputs.
fn render(inputs: &Inputs) -> String {
    let mut lockfile = Lockfile::new();
    lockfile.insert(entry(inputs));
    lockfile.to_toml().expect("render")
}

/// A minimal connector, for the hash-domain tests that need to vary one field at a time.
fn bare(provenance: Provenance) -> Connector {
    Connector {
        id: "zendesk".into(),
        authority: None,
        runtime: connector_spec::Runtime::Http,
        api_version: None,
        services: Vec::new(),
        vendor: "Zendesk".into(),
        base_url: "https://acme.zendesk.com".into(),
        description: String::new(),
        auth: Vec::new(),
        default_auth: Vec::new(),
        operations: Vec::new(),
        events: Vec::new(),
        channels: Vec::new(),
        config: Vec::new(),
        verify: None,
        graphs: Vec::new(),
        provenance,
    }
}

// ---------------------------------------------------------------------------------------------
// The hash domain
// ---------------------------------------------------------------------------------------------

/// The story's first finding, stated directly. Two fetches of byte-identical inputs differ only in
/// *when* they happened, so the hashed bytes must be identical — anything else is phantom drift on
/// every re-fetch, which is the failure `connectors.lock` exists to prevent rather than cause.
#[test]
fn the_hash_domain_excludes_fetched_at() {
    let first = bare(Provenance {
        fetched_at: Some("2024-01-01T00:00:00Z".into()),
        ..Provenance::default()
    });
    let refetched = bare(Provenance {
        fetched_at: Some("2026-07-30T12:00:00Z".into()),
        ..Provenance::default()
    });

    assert_eq!(
        first.hash_domain().expect("hash domain"),
        refetched.hash_domain().expect("hash domain"),
        "re-fetching byte-identical inputs must not change the hashed bytes"
    );
    assert_eq!(
        first.ir_sha256().expect("hash"),
        refetched.ir_sha256().expect("hash"),
    );
}

/// `fetched_at` is the field the review caught, but the rule is broader and worth pinning as such:
/// provenance says where the bytes came from, the IR hash says what was compiled from them. Every
/// provenance field is recorded and verified as its own lockfile column, so hashing it here too
/// would double-count it — and would move `ir_sha256` for edits that change no generated byte.
#[test]
fn the_hash_domain_excludes_every_provenance_field() {
    let empty = bare(Provenance::default());
    let full = bare(Provenance {
        source_url: Some("https://example.test/openapi.json".into()),
        upstream_version: Some("0.7.0".into()),
        fetched_at: Some("2026-07-30T12:00:00Z".into()),
        spec_sha256: Some("a".repeat(64)),
        // The per-document record C-410 added is provenance too, so it is outside the hash domain
        // for the same reason the four scalars are: re-vendoring a document must not move
        // `ir_sha256` unless the compiled meaning moved with it.
        specs: vec![connector_spec::SpecSource {
            path: "specs/zendesk/2024-06-01.json".into(),
            sha256: Some("a".repeat(64)),
            ..Default::default()
        }],
        operation_specs: [(
            "zendesk-ticket-list".into(),
            connector_spec::OperationSpecSource {
                operation_id: "ListTickets".into(),
                source_url: Some("https://example.test/openapi.json".into()),
                upstream_version: "0.7.0".into(),
                sha256: "a".repeat(64),
            },
        )]
        .into(),
        toml_sha256: Some("b".repeat(64)),
    });

    assert_eq!(
        empty.hash_domain().expect("hash domain"),
        full.hash_domain().expect("hash domain"),
    );
    assert!(
        !full.hash_domain().expect("hash domain").contains("sha256"),
        "no provenance field may appear in the hashed bytes"
    );

    // And the complete encoding still carries all of it — the domain is a projection, not a
    // deletion. A round trip through disk must not lose provenance.
    let complete = full.canonical_json().expect("serialize");
    assert!(complete.contains("2026-07-30T12:00:00Z"));
    assert!(complete.contains("https://example.test/openapi.json"));
    assert!(complete.contains("ListTickets"));
}

/// The other half of the contract: everything that *does* decide what gets generated is in the
/// domain, so a real change cannot slip past `check`.
#[test]
fn the_hash_domain_covers_the_compiled_meaning() {
    let base = provider::load("providers/zendesk.toml", ZENDESK_TOML)
        .expect("load")
        .connector;
    let baseline = base.ir_sha256().expect("hash");

    let mut renamed = base.clone();
    renamed.id = "zendesk-eu".into();
    let mut moved = base.clone();
    moved.base_url = "https://other.zendesk.com".into();
    let mut described = base.clone();
    described.description = "something else".into();
    let mut deauthed = base.clone();
    deauthed.default_auth.clear();
    let mut trimmed = base.clone();
    trimmed.operations.clear();
    let mut retyped = base.clone();
    retyped.operations[0].risk = connector_spec::Risk::Destructive;

    for (what, changed) in [
        ("id", renamed),
        ("base_url", moved),
        ("description", described),
        ("default_auth", deauthed),
        ("operations", trimmed),
        ("an operation's risk", retyped),
    ] {
        assert_ne!(
            baseline,
            changed.ir_sha256().expect("hash"),
            "changing {what} must change the IR hash"
        );
    }
}

/// The hash is a function of the connector's *value*, not of the order its collections were built
/// in — `tests/determinism.rs` makes the same guarantee about the full encoding, and the domain
/// must not weaken it.
#[test]
fn the_hash_is_stable_across_repeated_computation() {
    let connector = provider::load("providers/zendesk.toml", ZENDESK_TOML)
        .expect("load")
        .connector;
    let first = connector.ir_sha256().expect("hash");
    for _ in 0..64 {
        assert_eq!(first, connector.ir_sha256().expect("hash"));
    }
    assert_eq!(
        first.len(),
        64,
        "a sha256 renders as 64 lowercase hex digits"
    );
    assert!(first
        .chars()
        .all(|c| c.is_ascii_hexdigit() && !c.is_uppercase()));
}

// ---------------------------------------------------------------------------------------------
// Byte-for-byte reproducibility — the property `check` is built on
// ---------------------------------------------------------------------------------------------

/// **The load-bearing test.** Recomputing everything from unchanged inputs reproduces the file
/// exactly: same bytes from an independent second pass, same bytes on repetition, same bytes when
/// providers are recorded in a different order, and same bytes after a round trip through the
/// parser. If any of those drifted, `check` would report drift on a clean tree.
#[test]
fn unchanged_inputs_reproduce_the_lockfile_byte_for_byte() {
    let first = render(&Inputs::default());

    // A second, wholly independent pass over the same bytes.
    let second = render(&Inputs::default());
    assert_eq!(
        first, second,
        "a rebuild over unchanged inputs must be a no-op"
    );

    // Repetition within one process — the failure mode a `HashMap` would produce.
    for _ in 0..32 {
        assert_eq!(first, render(&Inputs::default()));
    }

    // Discovery order must not leak into the file.
    let mut forwards = Lockfile::new();
    let mut backwards = Lockfile::new();
    for id in ["alpha", "omega", "middle"] {
        let mut connector = bare(Provenance::default());
        connector.id = id.into();
        forwards.insert(LockEntry::for_connector(&connector, GENERATOR).expect("entry"));
    }
    for id in ["middle", "omega", "alpha"] {
        let mut connector = bare(Provenance::default());
        connector.id = id.into();
        backwards.insert(LockEntry::for_connector(&connector, GENERATOR).expect("entry"));
    }
    assert_eq!(
        forwards.to_toml().expect("render"),
        backwards.to_toml().expect("render"),
        "the file must depend on the set of providers, not on the order they were visited in"
    );

    // Reading the committed file back and rewriting it must be the identity — otherwise `check`
    // could not compare a parsed lockfile against a freshly built one.
    let reparsed = Lockfile::parse(&first).expect("parse");
    assert_eq!(first, reparsed.to_toml().expect("render"));
    assert_eq!(
        reparsed,
        Lockfile::parse(&reparsed.to_toml().expect("render")).expect("parse")
    );
}

/// Nothing in the file may vary with *when* the build ran. This is the same rule as
/// `the_hash_domain_excludes_fetched_at`, one level up: a lockfile that churned on every re-fetch
/// would be reverted out of the repo within a week.
#[test]
fn the_lockfile_records_no_timestamp() {
    let with_timestamp = Inputs {
        definition: format!(
            "{ZENDESK_TOML}\n\
             [spec]\n\
             path = \"{SPEC_PATH}\"\n\
             upstream_version = \"1.0.0\"\n\
             fetched_at = \"2026-07-30T12:00:00Z\"\n"
        ),
        ..Inputs::default()
    };

    let rendered = render(&with_timestamp);
    assert!(
        !rendered.contains("2026-07-30"),
        "a fetch timestamp must not reach the lockfile:\n{rendered}"
    );
    assert!(
        !rendered.contains("fetched_at"),
        "the lockfile has no timestamp field at all:\n{rendered}"
    );
    // The provenance itself is untouched — it is still on the connector, where a human can read it.
    let loaded = load(&with_timestamp.definition);
    assert_eq!(
        loaded.connector.provenance.fetched_at.as_deref(),
        Some("2026-07-30T12:00:00Z")
    );
}

/// The rendered shape, pinned. A lockfile is read as a PR diff, so its layout is a deliverable:
/// one `[[provider]]` block per provider, scalars before tables, hashes one per line.
#[test]
fn the_rendered_shape_is_pinned() {
    let mut lockfile = Lockfile::new();
    let mut connector = bare(Provenance {
        source_url: Some("https://example.test/openapi.json".into()),
        upstream_version: Some("0.7.0".into()),
        fetched_at: Some("2026-07-30T12:00:00Z".into()),
        spec_sha256: Some("a".repeat(64)),
        toml_sha256: Some("b".repeat(64)),
        ..Provenance::default()
    });
    connector.id = "zendesk".into();
    lockfile.insert(
        LockEntry::for_connector(&connector, GENERATOR)
            .expect("entry")
            .with_artifact("zendesk.flux", b"module")
            .with_artifact("zendesk.connector.toml", b"manifest"),
    );

    assert_eq!(lockfile.to_toml().expect("render"), EXPECTED_RENDERING);
}

/// One provider, every field populated. Note what is *not* here: no `fetched_at`, though the
/// connector carried one, and no upstream endpoint.
const EXPECTED_RENDERING: &str = r#"# connectors.lock — generated by flux-connectors. Do not edit by hand.
# Verified by `flux-connectors check`; regenerated by `flux-connectors build`.

version = 1

[[provider]]
id = "zendesk"
generator = "flux-connectors 0.1.0"
source_url = "https://example.test/openapi.json"
upstream_version = "0.7.0"
spec_sha256 = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
toml_sha256 = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
ir_sha256 = "cc61fb34bdffc46fea5d86a18cd30917724e87d36e7c4ee4d9a944ecd44553f0"

[provider.artifacts]
"zendesk.connector.toml" = "05b3abf2579a5eb66403cd78be557fd860633a1fe2103c7642030defe32c657f"
"zendesk.flux" = "120970d812836f19888625587a4606a5ad23cef31c8684e601771552548fc6b9"
"#;

/// The catalog pack's `[pack]` section (C-537): rendered between the version and the provider
/// rows, round-tripping exactly, and absent — not defaulted — from a lockfile no full build gave
/// one.
#[test]
fn the_pack_section_renders_and_round_trips() {
    // A pre-C-537 lockfile parses, and its absence of a pack is an absence.
    let vintage = Lockfile::parse(EXPECTED_RENDERING).expect("an old lockfile still parses");
    assert!(
        vintage.pack().is_none(),
        "a lockfile without a [pack] section records no pack"
    );

    let mut lockfile = Lockfile::new();
    lockfile.set_pack(connector_spec::LockPack {
        path: "crates/catalog-reader/catalog.pack".into(),
        schema_version: 1,
        sha256: "c".repeat(64),
    });
    let mut connector = bare(Provenance::default());
    connector.id = "zendesk".into();
    lockfile.insert(LockEntry::for_connector(&connector, GENERATOR).expect("entry"));

    let rendered = lockfile.to_toml().expect("render");
    let pack_at = rendered
        .find("[pack]")
        .expect("a [pack] section is rendered");
    let provider_at = rendered
        .find("[[provider]]")
        .expect("the provider rows follow");
    assert!(
        pack_at < provider_at,
        "the one whole-catalogue record renders before the per-provider rows:\n{rendered}"
    );

    let reparsed = Lockfile::parse(&rendered).expect("parse");
    assert_eq!(reparsed.pack(), lockfile.pack(), "the section round-trips");
    assert_eq!(
        rendered,
        reparsed.to_toml().expect("render"),
        "parse-then-render is the identity with a pack recorded, as without one"
    );

    // Recording again replaces, so a rebuild records one pack both times.
    lockfile.set_pack(connector_spec::LockPack {
        path: "crates/catalog-reader/catalog.pack".into(),
        schema_version: 1,
        sha256: "d".repeat(64),
    });
    assert_eq!(lockfile.pack().expect("recorded").sha256, "d".repeat(64));
}

// ---------------------------------------------------------------------------------------------
// One hash per input
// ---------------------------------------------------------------------------------------------

/// Editing the provider TOML moves its own hash, and the hashes of what it produced — never the
/// spec's, never the generator.
#[test]
fn a_changed_toml_moves_the_toml_hash_and_nothing_upstream_of_it() {
    let before = entry(&Inputs::default());

    let after = entry(&Inputs {
        definition: ZENDESK_TOML.replace("Show one ticket", "Show a single ticket"),
        ..Inputs::default()
    });

    assert_ne!(
        before.toml_sha256, after.toml_sha256,
        "the TOML bytes changed"
    );
    assert_ne!(
        before.ir_sha256, after.ir_sha256,
        "so did what they compile to"
    );
    assert_ne!(
        before.artifacts, after.artifacts,
        "and so did the artifacts"
    );
    assert_eq!(
        before.spec_sha256, after.spec_sha256,
        "the spec did not move"
    );
    assert_eq!(before.generator, after.generator, "nor did the generator");
}

/// The sharp end of excluding provenance from the hash domain: a comment-only edit changes the
/// file's bytes and *nothing else*. `check` reports the TOML as edited, and does not claim the
/// generated artifacts went stale — because they did not.
#[test]
fn a_comment_only_edit_moves_the_toml_hash_alone() {
    let before = entry(&Inputs::default());

    let after = entry(&Inputs {
        definition: format!("# a note for the next reader\n{ZENDESK_TOML}"),
        ..Inputs::default()
    });

    assert_ne!(before.toml_sha256, after.toml_sha256);
    assert_eq!(
        before.ir_sha256, after.ir_sha256,
        "a comment compiles to nothing, so the IR hash must not move"
    );
    assert_eq!(before.artifacts, after.artifacts);
}

/// A new vendored spec moves the spec hash. Nothing else moves *here* because this fixture builds
/// its IR from the TOML alone — the two columns are independent by construction. Now that ingest
/// exists (C-4), a spec change that touches a **selected** operation moves `ir_sha256` too, which is
/// correct and is exactly what the separate columns are for: a document that moved and an IR that
/// did not is a vendor edit nothing this connector selected.
#[test]
fn a_changed_spec_moves_the_spec_hash() {
    let before = entry(&Inputs::default());

    let after = entry(&Inputs {
        spec: Some(SPEC.replace("1.0.0", "1.1.0")),
        ..Inputs::default()
    });

    assert_ne!(before.spec_sha256, after.spec_sha256);
    assert_eq!(before.toml_sha256, after.toml_sha256);
    assert_eq!(before.generator, after.generator);
}

/// A generator bump invalidates generated output — that is the point of recording it — and must
/// invalidate nothing else. None of the inputs moved, so none of the input hashes may.
#[test]
fn a_changed_generator_moves_the_artifact_hashes_alone() {
    let before = entry(&Inputs::default());

    let after = entry(&Inputs {
        generator: "flux-connectors 0.2.0".to_string(),
        ..Inputs::default()
    });

    assert_ne!(before.generator, after.generator);
    assert_ne!(
        before.artifacts, after.artifacts,
        "a generator bump must invalidate the artifacts it produced"
    );
    assert_eq!(before.toml_sha256, after.toml_sha256);
    assert_eq!(before.spec_sha256, after.spec_sha256);
    assert_eq!(
        before.ir_sha256, after.ir_sha256,
        "the IR is what the inputs mean, and the inputs did not change"
    );
}

// ---------------------------------------------------------------------------------------------
// What must never be in the file
// ---------------------------------------------------------------------------------------------

/// A lockfile is committed, reviewed in a diff, and kept forever. It carries hashes, ids and
/// versions — never a secret, and never a resolved endpoint. The spec's `source_url` is the one
/// URL it holds, and that is a published specification document, not a tenant's API.
#[test]
fn the_lockfile_carries_no_credential_and_no_endpoint() {
    let rendered = render(&Inputs {
        definition: format!(
            "{ZENDESK_TOML}\n\
             [spec]\n\
             path = \"{SPEC_PATH}\"\n\
             source_url = \"https://developer.zendesk.com/zendesk/oas.yaml\"\n"
        ),
        ..Inputs::default()
    });

    for forbidden in [
        // The endpoint the generated module calls, and the path it calls on it.
        "acme.zendesk.com",
        "/api/v2/tickets",
        // The credential's name, its scheme, and the environment keys that resolve it. None of
        // these is a secret on its own, and none of them belongs in a hash record either: the
        // lockfile's job is drift detection, and every name it prints is a name an attacker
        // reading the repo gets for free somewhere it is actually load-bearing.
        "zendesk.api_token",
        "ZENDESK_API_TOKEN",
        "ZENDESK_USER",
        "basic",
        "/token",
    ] {
        assert!(
            !rendered.contains(forbidden),
            "{forbidden:?} must never reach connectors.lock:\n{rendered}"
        );
    }

    // The specification URL is recorded, deliberately — C-14 re-fetches from it.
    assert!(rendered.contains("https://developer.zendesk.com/zendesk/oas.yaml"));

    // The canonical document's row (C-536) is the sharpest instance of the rule: the document's
    // own bytes carry the endpoint, the credential names and the environment keys — the fixture
    // above puts them there on purpose — and what reaches the lockfile is its path and its hash.
    assert!(
        rendered.contains("\"catalog/zendesk.catalog.json\""),
        "the document row must be recorded:\n{rendered}"
    );
}

// ---------------------------------------------------------------------------------------------
// The file as a whole
// ---------------------------------------------------------------------------------------------

/// Rebuilding one provider replaces its row rather than appending a second one, and the rows stay
/// ordered by provider id however they arrived.
#[test]
fn a_rebuild_replaces_a_row_rather_than_duplicating_it() {
    let mut lockfile = Lockfile::new();
    for id in ["zendesk", "ollama", "zendesk", "freshdesk"] {
        let mut connector = bare(Provenance::default());
        connector.id = id.into();
        lockfile.insert(LockEntry::for_connector(&connector, GENERATOR).expect("entry"));
    }

    let ids: Vec<&str> = lockfile.entries().iter().map(|e| e.id.as_str()).collect();
    assert_eq!(ids, ["freshdesk", "ollama", "zendesk"]);
    assert!(lockfile.entry("ollama").is_some());
    assert!(lockfile.entry("shopify").is_none());
}

/// C-25 will record **two** hashes for the babelforce spec — what upstream served, and the scrubbed
/// copy this repo may legally vendor. That has to be an added field, not a reshaped entry: absent
/// everywhere it does not apply, present and round-tripping where it does.
#[test]
fn a_second_spec_hash_is_additive() {
    let connector = bare(Provenance {
        spec_sha256: Some("a".repeat(64)),
        ..Provenance::default()
    });
    let plain = LockEntry::for_connector(&connector, GENERATOR).expect("entry");
    assert_eq!(plain.upstream_spec_sha256, None);

    let scrubbed = LockEntry::for_connector(&connector, GENERATOR)
        .expect("entry")
        .with_upstream_spec_sha256("c".repeat(64));

    let mut lockfile = Lockfile::new();
    lockfile.insert(plain.clone());
    let without = lockfile.to_toml().expect("render");
    assert!(
        !without.contains("upstream_spec_sha256"),
        "the second hash must not clutter every other provider's row"
    );

    let mut lockfile = Lockfile::new();
    lockfile.insert(scrubbed.clone());
    let with = lockfile.to_toml().expect("render");
    assert!(with.contains(&format!("upstream_spec_sha256 = \"{}\"", "c".repeat(64))));
    assert_eq!(
        Lockfile::parse(&with).expect("parse").entry("zendesk"),
        Some(&scrubbed),
    );
    // And it is genuinely additive: dropping it recovers the plain row exactly.
    assert_eq!(
        Lockfile::parse(&without).expect("parse").entry("zendesk"),
        Some(&plain),
    );
}

/// A lockfile from a future format version is refused rather than misread — a silently
/// misinterpreted file would report drift in every provider at once, which reads as a broken tool
/// rather than as the version mismatch it is.
#[test]
fn a_lockfile_from_another_format_version_is_refused() {
    let rendered = render(&Inputs::default());
    let future = rendered.replace(
        &format!("version = {}", connector_spec::LOCKFILE_VERSION),
        &format!("version = {}", connector_spec::LOCKFILE_VERSION + 1),
    );

    let error = Lockfile::parse(&future).expect_err("a future version must be refused");
    let message = error.to_string();
    assert!(message.contains("version"), "{message}");
    assert!(message.contains("connectors.lock"), "{message}");
}

/// The lockfile is as strict as the IR types, and for the same reason: a key nobody recognizes is
/// either a typo in a hand-edit or a field from a version this build cannot honor, and discarding
/// it silently would mean verifying less than the file claims to record.
#[test]
fn an_unknown_key_is_refused() {
    let rendered = render(&Inputs::default());
    let tampered = rendered.replace("ir_sha256 = ", "ir_sha256_typo = ");

    let error = Lockfile::parse(&tampered).expect_err("an unknown key must be refused");
    assert!(error.to_string().contains("ir_sha256_typo"), "{error}");
}
