//! `connectors.lock` — the record that makes drift *detectable* rather than absorbed.
//!
//! One entry per provider, each holding the hashes and versions of everything that produced that
//! provider's artifacts. `flux-connectors check` (C-14) recomputes every one of them and exits
//! non-zero on a mismatch, which is the whole answer to action-proxy's third failure: hand-written
//! config silently drifting away from the API it describes.
//!
//! # The one property everything rests on
//!
//! **Unchanged inputs reproduce the file byte for byte.** If that ever stops holding, `check` turns
//! into noise and gets disabled, and the drift it was guarding against goes back to being invisible.
//! So every field here is a pure function of committed content, and the file is a pure function of
//! its entries:
//!
//! - entries are ordered by provider id, not by discovery order, so the same providers always
//!   render in the same sequence;
//! - artifact hashes live in a [`BTreeMap`], so they render in sorted order;
//! - **no timestamp is recorded at all.** `fetched_at` is provenance the provider TOML already
//!   carries; putting it here would make a re-fetch of a byte-identical document rewrite the
//!   lockfile, which is exactly the phantom drift this file exists to rule out.
//!
//! `tests/lockfile.rs` pins all of it.
//!
//! # Each hash covers exactly one input
//!
//! That is what lets `check` report *which* input moved rather than only *that* something did:
//!
//! | Field | Hashes | Moves when |
//! |---|---|---|
//! | [`toml_sha256`](LockEntry::toml_sha256) | the `providers/<id>.toml` bytes | the file is edited at all, comments included |
//! | [`spec_sha256`](LockEntry::spec_sha256) | the vendored spec bytes under `specs/` | the vendored document changes |
//! | [`specs`](LockEntry::specs) | each vendored document separately (C-410) | any one of them changes |
//! | [`upstream_spec_sha256`](LockEntry::upstream_spec_sha256) | the *unscrubbed* upstream document | upstream moves (C-25) |
//! | [`ir_sha256`](LockEntry::ir_sha256) | [`Connector::hash_domain`] | the compiled meaning changes |
//! | [`generator`](LockEntry::generator) | — (an identity string) | the generator is rebuilt at a new version |
//! | [`artifacts`](LockEntry::artifacts) | each generated file's bytes | the emitted output changes, including from a generator bump |
//!
//! # What is never in here
//!
//! No credential, no environment-variable *value*, and no resolved endpoint URL. A lockfile is
//! reviewed in a PR diff and committed forever, so it carries hashes, ids and versions only.
//! [`source_url`](LockEntry::source_url) is the exception that proves the rule: it locates a
//! *published specification document*, not a tenant's API endpoint, and C-14 needs it to re-fetch.
//! `tests/lockfile.rs::the_lockfile_carries_no_credential_and_no_endpoint` holds the line.
//!
//! # No IO
//!
//! Like the rest of this crate: [`Lockfile::to_toml`] renders text and [`Lockfile::parse`] reads
//! it. Deciding where `connectors.lock` lives, and writing it, is `connector-cli`'s job — and since
//! C-189 it does it: the file sits at the repository root, `build` emits it on a **full** run, and
//! `diff` reports a stale one like any other artifact. `crates/connector-cli/tests/lockfile.rs` is
//! that half.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::Connector;

/// The lockfile's name at the repository root. Named here so the CLI and `check` cannot disagree.
pub const LOCKFILE_NAME: &str = "connectors.lock";

/// The lockfile format version [`Lockfile::to_toml`] writes and [`Lockfile::parse`] accepts.
///
/// It exists so that a future reshape fails loudly on an old file instead of being silently
/// misread as drift in every provider at once.
pub const LOCKFILE_VERSION: u32 = 1;

/// The banner every rendered lockfile opens with.
///
/// Deliberately carries no version and no timestamp: it is part of the file's bytes, so anything
/// varying in it would vary the whole file.
const HEADER: &str = "# connectors.lock — generated by flux-connectors. Do not edit by hand.\n\
                      # Verified by `flux-connectors check`; regenerated by `flux-connectors build`.\n";

/// Lowercase-hex SHA-256, the only hash form this repo records.
///
/// Public because `check` (C-14) recomputes hashes over bytes this crate never sees — a vendored
/// spec, a generated artifact — and must produce the identical spelling to compare against.
pub fn sha256_hex(bytes: &[u8]) -> String {
    use std::fmt::Write as _;

    let mut hex = String::with_capacity(64);
    for byte in Sha256::digest(bytes) {
        let _ = write!(hex, "{byte:02x}");
    }
    hex
}

/// The whole `connectors.lock`: a format version and one [`LockEntry`] per provider.
///
/// The entries are kept sorted by provider id by construction — [`insert`](Self::insert) maintains
/// it and [`parse`](Self::parse) restores it — so a lockfile is a function of the *set* of entries
/// it holds and never of the order a build happened to visit providers in.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Lockfile {
    /// The format version. See [`LOCKFILE_VERSION`].
    version: u32,
    /// The compiled catalog pack, when a full build recorded one — see [`LockPack`] (C-537).
    ///
    /// Between `version` and the entries so the rendering stays valid TOML: a bare value after a
    /// table would fail to serialize, and `[pack]` before the `[[provider]]` rows keeps the one
    /// whole-catalogue record where a reader of the file sees it first.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pack: Option<LockPack>,
    /// One entry per provider, ordered by [`LockEntry::id`].
    #[serde(default, rename = "provider", skip_serializing_if = "Vec::is_empty")]
    entries: Vec<LockEntry>,
}

impl Lockfile {
    /// An empty lockfile at the current format version.
    pub fn new() -> Self {
        Self {
            version: LOCKFILE_VERSION,
            pack: None,
            entries: Vec::new(),
        }
    }

    /// Records the compiled catalog pack — see [`LockPack`] (C-537).
    ///
    /// Replacement, like [`insert`](Self::insert), so a rebuild records one pack both times.
    pub fn set_pack(&mut self, pack: LockPack) {
        self.pack = Some(pack);
    }

    /// The recorded catalog pack, when a full build wrote one.
    pub fn pack(&self) -> Option<&LockPack> {
        self.pack.as_ref()
    }

    /// Records an entry, replacing any entry already held for the same provider.
    ///
    /// Replacement rather than accumulation is what makes a rebuild idempotent: running `build`
    /// twice records one entry per provider both times.
    pub fn insert(&mut self, entry: LockEntry) {
        match self.entries.binary_search_by(|held| held.id.cmp(&entry.id)) {
            Ok(index) => self.entries[index] = entry,
            Err(index) => self.entries.insert(index, entry),
        }
    }

    /// The entry for one provider, if the lockfile records it.
    pub fn entry(&self, id: &str) -> Option<&LockEntry> {
        let index = self
            .entries
            .binary_search_by(|held| held.id.as_str().cmp(id));
        index.ok().map(|index| &self.entries[index])
    }

    /// Every entry, ordered by provider id.
    pub fn entries(&self) -> &[LockEntry] {
        &self.entries
    }

    /// The format version this lockfile declares.
    pub fn version(&self) -> u32 {
        self.version
    }

    /// Renders the file's exact bytes.
    ///
    /// TOML, because it is the vocabulary the rest of this repo already speaks and it diffs a line
    /// at a time — a changed hash shows up as one changed line under a named provider, which is
    /// what a reviewer needs to see.
    ///
    /// # Errors
    ///
    /// [`Error::SerializeLock`](crate::Error::SerializeLock) — in practice unreachable, since every
    /// field here is a string, a number or a map of strings.
    pub fn to_toml(&self) -> crate::Result<String> {
        let body = toml::to_string(self).map_err(Box::new)?;
        Ok(format!("{HEADER}\n{body}"))
    }

    /// Parses a `connectors.lock`, restoring the sorted-by-id invariant.
    ///
    /// Sorting on the way in means a hand-reordered file still compares equal to a freshly built
    /// one, so `check` reports drift only for content that actually differs.
    ///
    /// # Errors
    ///
    /// [`Error::ParseLock`](crate::Error::ParseLock) when the text is not a well-formed lockfile,
    /// and [`Error::Invalid`](crate::Error::Invalid) when it declares a format version this build
    /// does not understand.
    pub fn parse(source: &str) -> crate::Result<Self> {
        let mut lockfile: Self = toml::from_str(source).map_err(Box::new)?;
        if lockfile.version != LOCKFILE_VERSION {
            return Err(crate::Error::Invalid(format!(
                "{LOCKFILE_NAME} declares format version {}, but this build of flux-connectors \
                 writes version {LOCKFILE_VERSION}",
                lockfile.version
            )));
        }
        lockfile.entries.sort_by(|a, b| a.id.cmp(&b.id));
        Ok(lockfile)
    }
}

/// The compiled catalog pack, recorded as the lockfile's one **whole-catalogue** artifact (C-537).
///
/// A [`LockEntry`] is one provider's row, so the pack — every provider's canonical document,
/// compiled into the single file the reader crate embeds — cannot live in any of them without
/// being recorded 55 times or attributed to a provider it does not belong to. It is a section of
/// its own instead, and deliberately the only one: the *other* whole-catalogue artifacts
/// (`catalog.json`, the generated index, the README images) remain covered transitively through
/// each row's `ir_sha256` and directly by `crates/connector-cli/tests/catalog_artifacts.rs`,
/// exactly as before. The pack is recorded here because it is the one whole-catalogue artifact
/// that is *distributed* — embedded in a published crate and loadable by a host from a path — so
/// "which pack does this tree produce" is a question `check` (C-14) must answer from the lockfile
/// alone.
///
/// # Two digests, one file, on purpose
///
/// [`sha256`](Self::sha256) hashes the pack file's **complete bytes**, the way every other
/// artifact hash in this file is taken — so `check` rehashes the committed file with the same
/// instrument it uses everywhere else. The digest *embedded in* the pack covers only the bytes
/// after its own digest line, because a digest cannot cover itself. Equal content implies both
/// match their regions; they are different values and neither substitutes for the other.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct LockPack {
    /// The pack, repository-relative and `/`-separated: `crates/catalog-reader/catalog.pack`.
    pub path: String,
    /// The document schema version the pack embeds — its payload's `schema_version`.
    pub schema_version: u32,
    /// Lowercase-hex SHA-256 of the pack file's bytes.
    pub sha256: String,
}

/// One provider's row: everything `check` needs to prove the committed artifacts still follow from
/// the committed inputs.
///
/// Build one with [`for_connector`](Self::for_connector) and add the generated artifacts with
/// [`with_artifact`](Self::with_artifact); the fields are public so `check` can compare them one by
/// one and name the input that moved.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct LockEntry {
    /// The provider id — [`Connector::id`], which is also the artifact file stem.
    pub id: String,
    /// The generator that produced the artifacts, e.g. `flux-connectors 0.1.0`.
    ///
    /// Recorded per provider rather than once per file: a regeneration that touches one provider
    /// must be able to say so, and a stale row is then visible next to a fresh one instead of being
    /// papered over by a single file-level stamp.
    ///
    /// It carries no hash of its own, and it does not need one — the emitter stamps its identity
    /// into what it emits, so a generator bump shows up in [`artifacts`](Self::artifacts). What it
    /// must *not* do is disturb an input hash, since none of the inputs changed.
    pub generator: String,
    /// Where the vendor spec was fetched from, so C-14 can re-fetch and diff. Absent for a
    /// hand-authored connector, which has no upstream document at all.
    ///
    /// A *specification* URL, never a resolved API endpoint — see the module docs.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_url: Option<String>,
    /// The upstream version string the vendor published for that spec.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub upstream_version: Option<String>,
    /// SHA-256 of the vendored spec bytes under `specs/` — the document builds actually read.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub spec_sha256: Option<String>,
    /// SHA-256 of the *unscrubbed* upstream document, when the vendored copy is a declared scrub of
    /// it.
    ///
    /// Additive by design, and it is C-25's requirement made room for: the babelforce document
    /// embeds credential-shaped literals that must not enter this repo, so what gets vendored is a
    /// reproducible scrub of what was fetched. Recording both hashes keeps *both* halves honest —
    /// [`spec_sha256`](Self::spec_sha256) pins what we build from, this pins what upstream served,
    /// and drift detection survives the scrub. Absent everywhere else, which is why a second hash
    /// costs one optional field rather than a reshape of every entry.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub upstream_spec_sha256: Option<String>,
    /// SHA-256 of the `providers/<id>.toml` bytes.
    ///
    /// Covers the file *as committed*, comments and whitespace included: the question it answers is
    /// "has this file been edited since the artifacts were generated", and for that a byte hash is
    /// the honest instrument.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub toml_sha256: Option<String>,
    /// SHA-256 of [`Connector::hash_domain`] — the compiled meaning of this connector.
    ///
    /// This is the hash the IR itself cannot carry: it is computed *from* the serialized IR, so
    /// storing it inside [`Provenance`](crate::Provenance) would have no fixed point. It sits here
    /// instead.
    pub ir_sha256: String,
    /// **One row per vendored document the connector compiles** — the per-document counterpart to
    /// the four scalars above, mirroring [`Provenance::specs`](crate::Provenance::specs) (C-410).
    ///
    /// The scalars describe *a* spec, which is only true while a connector compiles from exactly
    /// one; with several, [`spec_sha256`](Self::spec_sha256) is `None`, because no single value of
    /// it is true and filling it from the first document would record one document's provenance as
    /// the whole connector's. Without this list such a connector would be recorded with **no spec
    /// hash at all** — a row that looks complete and detects nothing.
    ///
    /// Filled for a single-document connector too, so `check` (C-14) has one shape to read rather
    /// than two. Empty for a hand-authored connector, and elided when empty, so a row that has no
    /// vendored document is unchanged by this field existing.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub specs: Vec<LockSpec>,
    /// SHA-256 of each generated artifact, keyed by **repository-relative path**
    /// (`connectors/zendesk.flux`, `crates/catalog/src/generated/zendesk.rs`).
    ///
    /// A path rather than a bare file name, for two reasons. `check` has to *find* the file to
    /// rehash it, and reconstructing a path from a stem means duplicating the layout rules that
    /// live in `connector-cli`'s workspace module. And a provider emits into three directories, so
    /// bare names collide: an operation named after its provider would render
    /// `crates/catalog/ops/zendesk/zendesk.flux` under the same key as `connectors/zendesk.flux`,
    /// and one of the two hashes would be silently dropped.
    ///
    /// A map rather than named fields, so a fourth artifact kind is a new key rather than a schema
    /// change, and a [`BTreeMap`] rather than a `HashMap`, so the rendering is sorted.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub artifacts: BTreeMap<String, String>,
}

/// One vendored document a connector compiles from, as `connectors.lock` records it.
///
/// Deliberately **not** [`SpecSource`](crate::provider::SpecSource), though it is the projection of
/// one: that type carries `fetched_at`, and a fetch timestamp is the one provenance field that moves
/// without any input changing. Re-vendoring a byte-identical document would rewrite the lockfile,
/// which is the phantom drift this file exists to rule out. The projection is where that field is
/// dropped, and a separate type is what keeps it dropped when `SpecSource` next grows a field.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct LockSpec {
    /// The vendored file, repository-relative — `specs/babelforce/manager-2026-07-10.openapi.yaml`.
    ///
    /// The identity of the row: `check` rehashes this path, and a document that moved is named by
    /// it rather than by an index into a list.
    pub path: String,
    /// The [`Service`](crate::Service) this document's operations join, when it names one.
    ///
    /// Absent means the reserved [`DEFAULT_SERVICE`](crate::DEFAULT_SERVICE) — what a single
    /// `[spec]` block has always meant. Recorded because an `operationId` is only unambiguous
    /// inside one document's service, so "which document moved" and "which surface it feeds" are
    /// the same question asked twice.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service: Option<String>,
    /// Where this document was fetched from, so C-14 can re-fetch and diff. Absent when the origin
    /// is private and cannot be published — see `AGENTS.md`, *Vendored specs*.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_url: Option<String>,
    /// The upstream version string the vendor published for this document (`info.version`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub upstream_version: Option<String>,
    /// SHA-256 of this document's vendored bytes.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sha256: Option<String>,
}

impl LockSpec {
    /// The service this document's operations join — [`DEFAULT_SERVICE`](crate::DEFAULT_SERVICE)
    /// when the row names none.
    pub fn service(&self) -> &str {
        self.service.as_deref().unwrap_or(crate::DEFAULT_SERVICE)
    }
}

impl From<&crate::provider::SpecSource> for LockSpec {
    /// The projection that drops `fetched_at`. Written as a `From` rather than inline at the call
    /// site so there is exactly one place the field list is decided.
    fn from(source: &crate::provider::SpecSource) -> Self {
        Self {
            path: source.path.clone(),
            service: source.service.clone(),
            source_url: source.source_url.clone(),
            upstream_version: source.upstream_version.clone(),
            sha256: source.sha256.clone(),
        }
    }
}

impl LockEntry {
    /// The entry for one loaded connector, hashing its IR and copying the provenance it carries.
    ///
    /// `generator` is the generator's identity string; `connector-cli` owns its exact spelling.
    /// Add the emitted artifacts with [`with_artifact`](Self::with_artifact).
    ///
    /// [`Provenance::fetched_at`](crate::Provenance::fetched_at) is deliberately **not** copied
    /// across: it is the one provenance field that moves without any input changing, and the
    /// lockfile is a function of content alone.
    ///
    /// # Errors
    ///
    /// [`Error::Serialize`](crate::Error::Serialize) if the IR cannot be encoded.
    pub fn for_connector(connector: &Connector, generator: &str) -> crate::Result<Self> {
        let provenance = &connector.provenance;
        Ok(Self {
            id: connector.id.clone(),
            generator: generator.to_owned(),
            source_url: provenance.source_url.clone(),
            upstream_version: provenance.upstream_version.clone(),
            spec_sha256: provenance.spec_sha256.clone(),
            upstream_spec_sha256: None,
            toml_sha256: provenance.toml_sha256.clone(),
            ir_sha256: connector.ir_sha256()?,
            specs: provenance.specs.iter().map(LockSpec::from).collect(),
            artifacts: BTreeMap::new(),
        })
    }

    /// Records the SHA-256 of one generated artifact, by file name.
    pub fn with_artifact(mut self, name: impl Into<String>, bytes: &[u8]) -> Self {
        self.artifacts.insert(name.into(), sha256_hex(bytes));
        self
    }

    /// Records the hash of the unscrubbed upstream document — see
    /// [`upstream_spec_sha256`](Self::upstream_spec_sha256).
    pub fn with_upstream_spec_sha256(mut self, sha256: impl Into<String>) -> Self {
        self.upstream_spec_sha256 = Some(sha256.into());
        self
    }
}
