//! Rendering `crates/catalog`'s generated half: one `.flux` file per operation, and the Rust table
//! that embeds them.
//!
//! `connectors/<provider>.flux` stays the artifact that ships and installs into `~/.flux/flows`.
//! What is generated here is *additional* — the catalog's unit — and it is the same text: an
//! operation's rendering is byte for byte what [`crate::seam::module`] concatenates into the
//! provider module, with no header of its own, so the two can never describe different requests.
//! `crates/connector-cli/tests/catalog_artifacts.rs` pins that.
//!
//! # Why the table is Rust rather than data
//!
//! The catalog crate has **no dependencies**, and that is a feature a consumer feels: `cargo add
//! connector-catalog` costs them one crate and no runtime work. Emitting JSON or TOML alongside the
//! Flux would mean the catalog either grows a parser dependency or parses on first use behind a
//! lock — both to reconstruct, at runtime, a table already known at build time. A generated `static`
//! is that table, laid out by the compiler in `.rodata`.
//!
//! Note what this is *not*: it is not the "no homegrown DSL" or "never string-template Flux" rule
//! being bent. Not one byte of **Flux** is assembled here. The Flux comes from
//! `connector_flux::emit_operation`, which builds real `flux_lang` AST nodes and runs flux-lang's
//! own formatter over them; this module only quotes that text into an `include_str!`.
//!
//! # Two properties this rendering must hold, and how each is held
//!
//! **Deterministic.** Equal inputs produce byte-identical output — the whole reason a rebuild
//! writes nothing. Everything below is a function of the IR alone, walked in the IR's own order,
//! with no map iteration and no timestamp.
//!
//! **rustfmt-stable.** The generated file is inside `cargo fmt --all --check`'s reach, so text
//! rustfmt would rewrite fails the gate. Rather than chase rustfmt's layout from a string builder —
//! a fixed point that would have to be rediscovered on every toolchain bump — each generated item
//! carries `#[rustfmt::skip]`, which is exactly the tool attribute's purpose. The `.flux` half is
//! held to flux-lang's formatter instead, by the emitter, and that fixed point *is* asserted
//! (`connector-flux`'s `shipped_modules.rs`).

use anyhow::{bail, Result};
use connector_spec::{Connector, Idempotency, Operation, Risk};

/// One operation's `.flux` rendering, on its way to `crates/catalog/ops/<provider>/<id>.flux`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OperationRendering {
    /// The operation id — the file stem, and the catalog's key.
    pub id: String,
    /// The formatted `op` declaration, exactly as the provider module carries it.
    pub source: String,
}

/// Render `crates/catalog/src/generated/<provider>.rs`: the provider's identity, and one
/// [`catalog::Operation`](../../catalog/src/lib.rs) entry per rendering.
///
/// `renderings` is passed in rather than recomputed so that the embedded text and the provider
/// module are emitted **once**, from one call to `connector_flux::emit_operation` per operation.
/// Emitting twice would make "the catalog agrees with the module" a coincidence rather than a
/// structural fact.
pub fn render(connector: &Connector, renderings: &[OperationRendering]) -> Result<String> {
    let host = host_of(&connector.base_url)?;

    let mut out = format!(
        "// Generated by {} — do not edit.\n\
         // Provider: {}\n\
         // Regenerate with `flux-connectors build`.\n\
         //\n\
         // The `include_str!` paths point at `crates/catalog/ops/{}/`, which the same build wrote.\n\n",
        crate::seam::generator(),
        connector.id,
        connector.id,
    );

    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub(crate) static PROVIDER: crate::Provider = crate::Provider {\n");
    out.push_str(&format!("    id: {},\n", string(&connector.id)));
    out.push_str(&format!("    vendor: {},\n", string(&connector.vendor)));
    out.push_str(&format!(
        "    description: {},\n",
        string(&connector.description)
    ));
    out.push_str(&format!("    base_url: {},\n", string(&connector.base_url)));
    out.push_str("    operations: OPERATIONS,\n");
    out.push_str("};\n\n");

    out.push_str("#[rustfmt::skip]\n");
    out.push_str("static OPERATIONS: &[crate::Operation] = &[\n");
    for rendering in renderings {
        let operation = connector.operation(&rendering.id).ok_or_else(|| {
            anyhow::anyhow!(
                "connector `{}` has no operation `{}` to describe",
                connector.id,
                rendering.id
            )
        })?;
        out.push_str(&entry(connector, operation, host));
    }
    out.push_str("];\n");

    Ok(out)
}

/// One `crate::Operation { … }` literal.
fn entry(connector: &Connector, operation: &Operation, host: &str) -> String {
    let mut out = String::from("    crate::Operation {\n");
    out.push_str(&format!("        id: {},\n", string(&operation.id)));
    out.push_str(&format!("        provider: {},\n", string(&connector.id)));
    out.push_str(&format!(
        "        description: {},\n",
        string(&operation.description)
    ));
    out.push_str(&format!("        risk: {},\n", risk(operation.risk)));
    out.push_str(&format!(
        "        idempotency: {},\n",
        idempotency(operation.idempotency)
    ));
    out.push_str(&format!(
        "        credentials: {},\n",
        credentials(connector, operation)
    ));
    out.push_str(&format!("        hosts: &[{}],\n", string(host)));
    // Escaped like every other literal here rather than interpolated raw. An id that reaches this
    // point is already constrained — the emitter refuses anything Flux cannot declare — but the
    // path is still a string literal, and one unescaped character in it is a generated file that
    // does not compile for a reason nobody can see in the provider TOML.
    out.push_str(&format!(
        "        flux: include_str!({}),\n",
        string(&format!(
            "../../ops/{}/{}.{}",
            connector.id,
            operation.id,
            crate::workspace::MODULE_EXT
        ))
    ));
    out.push_str("    },\n");
    out
}

/// The operation's credentials as alternatives (OR) of mechanisms (AND) — the IR's own shape,
/// carried across rather than flattened.
///
/// Flattening is the thing to avoid: babelforce's `accessId` + `accessToken` travel **together** on
/// one request and are an alternative to OAuth2, so a flat list of three names would tell a caller
/// that any one of them authenticates, which is false in both directions.
///
/// Resolved through [`Connector::effective_auth`], never by reading `Operation::auth` directly:
/// an operation that declares nothing inherits the connector default, and one that declares an
/// explicit empty list inherits nothing.
fn credentials(connector: &Connector, operation: &Operation) -> String {
    let mechanisms = connector.effective_auth(operation);
    if mechanisms.is_empty() {
        return "&[]".to_string();
    }
    let rendered: Vec<String> = mechanisms
        .iter()
        .map(|mechanism| {
            let names: Vec<String> = mechanism.iter().map(|name| string(name)).collect();
            format!("&[{}]", names.join(", "))
        })
        .collect();
    format!("&[{}]", rendered.join(", "))
}

/// The host a call reaches, taken from the connector's base URL with its templating intact.
///
/// `https://{subdomain}.zendesk.com` yields `{subdomain}.zendesk.com`: the tenant is the operator's
/// to choose, and substituting a placeholder here would invent one. A caller reads this to decide
/// whether their egress policy admits the call, and a pattern is the honest answer to that.
///
/// C-10 replaces this with the manifest's real `http_hosts` allowlist, which is why the catalog
/// field is a slice: today every operation reaches exactly the connector's own host.
fn host_of(base_url: &str) -> Result<&str> {
    let after_scheme = base_url
        .split_once("://")
        .map_or(base_url, |(_scheme, rest)| rest);
    let host = after_scheme
        .split(['/', '?', '#'])
        .next()
        .unwrap_or(after_scheme);
    if host.is_empty() {
        bail!("base URL `{base_url}` names no host, so nothing can say which host it reaches");
    }
    Ok(host)
}

/// `connector_spec::Risk` as the catalog's own mirror of it.
///
/// An exhaustive match, deliberately: a variant added to the IR is a compile error here rather than
/// a silent gap in the catalog.
fn risk(risk: Risk) -> &'static str {
    match risk {
        Risk::Low => "crate::Risk::Low",
        Risk::Medium => "crate::Risk::Medium",
        Risk::High => "crate::Risk::High",
        Risk::Destructive => "crate::Risk::Destructive",
    }
}

/// `connector_spec::Idempotency` as the catalog's mirror. Exhaustive for the same reason.
fn idempotency(idempotency: Idempotency) -> &'static str {
    match idempotency {
        Idempotency::Idempotent => "crate::Idempotency::Idempotent",
        Idempotency::NonIdempotent => "crate::Idempotency::NonIdempotent",
        Idempotency::Conditional => "crate::Idempotency::Conditional",
    }
}

/// A Rust string literal for `value`.
///
/// Escaping rather than a raw literal: a raw string would have to pick a hash count no content
/// collides with, and a description carrying `"#` would silently end the literal early. Every
/// character that could close or continue the literal is escaped, and the remaining control
/// characters go out as `\u{…}` so the generated file stays plain ASCII-safe text a reviewer can
/// read in a diff.
fn string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for character in value.chars() {
        match character {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\0' => out.push_str("\\0"),
            other if other.is_control() => out.push_str(&format!("\\u{{{:x}}}", other as u32)),
            other => out.push(other),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use connector_spec::{AuthMethod, AuthRequirement, HttpMethod, ParamSet, Quirks};

    fn operation(id: &str) -> Operation {
        Operation {
            id: id.to_string(),
            method: HttpMethod::Get,
            path: "/v2/things".to_string(),
            description: "Do a thing".to_string(),
            risk: Risk::Low,
            idempotency: Idempotency::Idempotent,
            auth: None,
            params: ParamSet::default(),
            response_schema: None,
            quirks: Quirks::default(),
        }
    }

    fn connector() -> Connector {
        Connector {
            id: "acme".to_string(),
            vendor: "Acme".to_string(),
            base_url: "https://{tenant}.acme.example/api".to_string(),
            description: "Acme".to_string(),
            auth: vec![
                AuthMethod::header("acme.access_id", "X-Id", vec!["ACME_ID".to_string()]),
                AuthMethod::header(
                    "acme.access_token",
                    "X-Token",
                    vec!["ACME_TOKEN".to_string()],
                ),
            ],
            default_auth: vec![AuthRequirement::all([
                "acme.access_id",
                "acme.access_token",
            ])],
            operations: vec![operation("acme-thing-list")],
            provenance: Default::default(),
        }
    }

    fn renderings() -> Vec<OperationRendering> {
        vec![OperationRendering {
            id: "acme-thing-list".to_string(),
            source: "op acme-thing-list -> Any\n".to_string(),
        }]
    }

    #[test]
    fn rendering_is_deterministic() {
        let first = render(&connector(), &renderings()).unwrap();
        let second = render(&connector(), &renderings()).unwrap();
        assert_eq!(first, second);
    }

    /// The table embeds the file the same build wrote, at the path it wrote it to. A wrong relative
    /// path is a compile error in the catalog crate, but only once someone builds it.
    #[test]
    fn each_entry_embeds_its_own_rendering() {
        let rendered = render(&connector(), &renderings()).unwrap();
        assert!(
            rendered.contains("flux: include_str!(\"../../ops/acme/acme-thing-list.flux\"),"),
            "{rendered}"
        );
    }

    /// **The AND/OR shape survives.** Two credentials on one request must not read as two ways to
    /// authenticate.
    #[test]
    fn an_and_group_stays_one_mechanism() {
        let rendered = render(&connector(), &renderings()).unwrap();
        assert!(
            rendered.contains(r#"credentials: &[&["acme.access_id", "acme.access_token"]],"#),
            "{rendered}"
        );
    }

    /// An operation that declares an explicit empty list inherits nothing — the distinction
    /// `Connector::effective_auth` exists to preserve.
    #[test]
    fn an_explicitly_unauthenticated_operation_names_no_credential() {
        let mut connector = connector();
        connector.operations[0].auth = Some(vec![]);
        let rendered = render(&connector, &renderings()).unwrap();
        assert!(rendered.contains("credentials: &[],"), "{rendered}");
    }

    #[test]
    fn the_host_keeps_its_templating_and_drops_the_path() {
        assert_eq!(
            host_of("https://{subdomain}.zendesk.com").unwrap(),
            "{subdomain}.zendesk.com"
        );
        assert_eq!(
            host_of("https://example.freshdesk.com/api/v2").unwrap(),
            "example.freshdesk.com"
        );
        assert!(host_of("https://").is_err());
    }

    /// A description carrying a quote or a backslash must not break out of its literal — the one
    /// way generated Rust stops compiling for a reason nobody can see in the provider file.
    #[test]
    fn quotes_and_backslashes_are_escaped() {
        assert_eq!(string(r#"a "b" \ c"#), r#""a \"b\" \\ c""#);
        assert_eq!(string("a\nb"), r#""a\nb""#);
    }

    /// A rendering for an operation the connector does not declare would embed a file nothing
    /// regenerates. It is a failure, not an entry that gets skipped.
    #[test]
    fn a_rendering_without_an_operation_is_refused() {
        let stray = vec![OperationRendering {
            id: "acme-thing-vanished".to_string(),
            source: String::new(),
        }];
        render(&connector(), &stray).expect_err("a stray rendering must not be rendered");
    }
}
