//! Rendering `crates/catalog`'s generated half: one `.flux` file per operation, the Rust table that
//! embeds them, and the index naming every provider's table (C-104).
//!
//! The first two are **per provider** and a scoped build regenerates exactly what it compiled. The
//! index is not — see [`render_index`], which is the whole-catalogue half and is therefore planned
//! by a full run only.
//!
//! `connectors/<provider>.flux` stays the artifact that ships and installs into `~/.flux/flows`.
//! What is generated here is *additional* — the catalog's unit — and it is the same text: an
//! operation's rendering is byte for byte what [`crate::seam::module`] concatenates into the
//! provider module, with no header of its own, so the two can never describe different requests.
//! `crates/connector-cli/tests/catalog_artifacts.rs` pins that.
//!
//! # Why the table is Rust rather than data
//!
//! The catalog crate has **no dependencies**, and that is a feature a consumer feels: `cargo add
//! connector-catalog` costs them one crate and no runtime work. Emitting JSON or TOML alongside the
//! Flux would mean the catalog either grows a parser dependency or parses on first use behind a
//! lock — both to reconstruct, at runtime, a table already known at build time. A generated `static`
//! is that table, laid out by the compiler in `.rodata`.
//!
//! Note what this is *not*: it is not the "no homegrown DSL" or "never string-template Flux" rule
//! being bent. Not one byte of **Flux** is assembled here. The Flux comes from
//! `connector_flux::emit_operation`, which builds real `flux_lang` AST nodes and runs flux-lang's
//! own formatter over them; this module only quotes that text into an `include_str!`.
//!
//! # Two properties this rendering must hold, and how each is held
//!
//! **Deterministic.** Equal inputs produce byte-identical output — the whole reason a rebuild
//! writes nothing. Everything below is a function of the IR alone, walked in the IR's own order,
//! with no map iteration and no timestamp.
//!
//! **rustfmt-stable.** The generated file is inside `cargo fmt --all --check`'s reach, so text
//! rustfmt would rewrite fails the gate. Rather than chase rustfmt's layout from a string builder —
//! a fixed point that would have to be rediscovered on every toolchain bump — each generated item
//! carries `#[rustfmt::skip]`, which is exactly the tool attribute's purpose. The `.flux` half is
//! held to flux-lang's formatter instead, by the emitter, and that fixed point *is* asserted
//! (`connector-flux`'s `shipped_modules.rs`).

use std::collections::BTreeMap;

use anyhow::{bail, Context, Result};
use connector_spec::{AuthScheme, Connector, Idempotency, Operation, Risk};

/// One operation's `.flux` rendering, on its way to `crates/catalog/ops/<provider>/<id>.flux`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OperationRendering {
    /// The operation id — the file stem, and the catalog's key.
    pub id: String,
    /// The formatted `op` declaration, exactly as the provider module carries it.
    pub source: String,
}

/// Render `crates/catalog/src/generated/<provider>.rs`: the provider's identity, and one
/// [`catalog::Operation`](../../catalog/src/lib.rs) entry per rendering.
///
/// `renderings` is passed in rather than recomputed so that the embedded text and the provider
/// module are emitted **once**, from one call to `connector_flux::emit_operation` per operation.
/// Emitting twice would make "the catalog agrees with the module" a coincidence rather than a
/// structural fact.
pub fn render(connector: &Connector, renderings: &[OperationRendering]) -> Result<String> {
    let mut out = format!(
        "// Generated by {} — do not edit.\n\
         // Provider: {}\n\
         // Regenerate with `flux-connectors build`.\n\
         //\n\
         // The `include_str!` paths point at `crates/catalog/ops/{}/`, which the same build wrote.\n\n",
        crate::seam::generator(),
        connector.id,
        connector.id,
    );

    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub(crate) static PROVIDER: crate::Provider = crate::Provider {\n");
    out.push_str(&format!("    id: {},\n", string(&connector.id)));
    out.push_str(&format!("    vendor: {},\n", string(&connector.vendor)));
    out.push_str(&format!(
        "    description: {},\n",
        string(&connector.description)
    ));
    out.push_str(&format!(
        "    authority: {},\n",
        option_string(connector.authority.as_deref())
    ));
    out.push_str(&format!("    runtime: {},\n", runtime(connector.runtime)));
    out.push_str(&format!("    base_url: {},\n", string(&connector.base_url)));
    out.push_str("    auth: AUTH,\n");
    out.push_str("    operations: OPERATIONS,\n");
    out.push_str("    config: CONFIG,\n");
    out.push_str(&format!(
        "    verify: {},\n",
        option_string(connector.verify.as_deref())
    ));
    out.push_str("    events: EVENTS,\n");
    out.push_str("    channels: CHANNELS,\n");
    out.push_str("    config_choices: CONFIG_CHOICES,\n");
    out.push_str("};\n\n");

    out.push_str(&render_auth(connector)?);
    out.push_str(&render_config(connector)?);
    out.push_str(&render_events(connector)?);
    out.push_str(&render_channels(connector)?);
    out.push_str(&render_config_choices(connector));

    out.push_str("#[rustfmt::skip]\n");
    out.push_str("static OPERATIONS: &[crate::Operation] = &[\n");
    for rendering in renderings {
        let operation = operation_for(connector, &rendering.id)?;
        // Per operation, through its service: a multi-service provider reaches a different host per
        // service, and the union would be a wider egress claim than any single call makes (C-49).
        let host = host_of(connector.base_url_of(&operation.service))?;
        out.push_str(&entry(connector, operation, host));
    }
    out.push_str("];\n");

    Ok(out)
}

/// Render `crates/catalog/src/generated.rs`: one `mod` line and one `PROVIDERS` entry per provider
/// (C-104).
///
/// `providers` is the **whole** shipped set, in discovery order — which is sorted, and is the order
/// `catalog::providers()` publishes. This is the one file in the catalog crate that is a function of
/// every provider at once rather than of one, so [`crate::pipeline::plan_selected`] plans it only on
/// a full run, exactly as it plans `catalog.json` only on a full run. A `--provider` run would have
/// to render an index naming one provider and silently dropping the rest.
///
/// Until C-104 the file was hand-written for that reason, and the cost was structural rather than
/// cosmetic: every provider story appended two lines to it, so any two provider stories conflicted
/// and the fleet shipped one connector at a time. Generating it under the full-run rule is what makes
/// two implementors' write sets disjoint.
pub fn render_index(providers: &[String]) -> Result<String> {
    let idents = providers
        .iter()
        .map(|provider| module_ident(provider))
        .collect::<Result<Vec<_>>>()?;

    let mut out = format!(
        "//! The generated catalog data, one module per provider.\n\
         //!\n\
         //! Generated by {} — do not edit. Regenerate with `flux-connectors build`.\n\
         //!\n\
         //! **A whole-catalogue artifact**, and therefore written by a *full* build only: an index\n\
         //! rendered from `build --provider zendesk` would name one provider and silently drop the\n\
         //! rest. `web/public/catalog.json` follows the same rule for the same reason\n\
         //! (`docs/designs/catalog-json.md`). The corollary is the point of C-104 — a provider-scoped\n\
         //! build writes only that provider's own files, so provider work fans out instead of\n\
         //! serialising on this one file.\n\
         //!\n\
         //! `crates/catalog/tests/embedded_operations.rs` holds this list against `providers/`, and\n\
         //! `crates/connector-cli/tests/catalog_artifacts.rs` holds the whole tree to being a fixed\n\
         //! point of a build, so a stale index is loud rather than silent.\n\n",
        crate::seam::generator(),
    );

    for ident in &idents {
        out.push_str(&format!("pub(crate) mod {ident};\n"));
    }

    out.push_str("\nuse crate::Provider;\n\n");
    out.push_str(
        "/// Every provider, ordered by id — the order [`crate::providers`] publishes and the order the\n\
         /// catalog's flat listing walks.\n",
    );
    // `#[rustfmt::skip]` for the same reason every other generated item here carries it: the file is
    // inside `cargo fmt --all --check`'s reach, and one provider would let rustfmt collapse the
    // slice onto a single line while seventeen would not. Pinning the layout is cheaper than
    // rediscovering rustfmt's fixed point on every toolchain bump.
    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub(crate) static PROVIDERS: &[&Provider] = &[\n");
    for ident in &idents {
        out.push_str(&format!("    &{ident}::PROVIDER,\n"));
    }
    out.push_str("];\n");

    Ok(out)
}

/// Every lowercase Rust keyword that `mod <name>;` rejects.
///
/// **Checked against rustc rather than written from memory**, which is how `union` came to be absent:
/// it is a *weak* keyword and `mod union {}` compiles, so refusing or escaping it would be wrong. The
/// probe is `mod <candidate> {}` for each of the strict and reserved keyword lists; anything rustc
/// answers with "expected identifier, found (reserved) keyword" is here.
///
/// `Self` is the one keyword deliberately missing: it is uppercase, and a provider name carrying an
/// uppercase letter is already refused by the character rule below.
const RUST_KEYWORDS: &[&str] = &[
    "abstract", "as", "async", "await", "become", "box", "break", "const", "continue", "crate",
    "do", "dyn", "else", "enum", "extern", "false", "final", "fn", "for", "if", "impl", "in",
    "let", "loop", "macro", "match", "mod", "move", "mut", "override", "priv", "pub", "ref",
    "return", "self", "static", "struct", "super", "trait", "true", "try", "type", "typeof",
    "unsafe", "unsized", "use", "virtual", "where", "while", "yield",
];

/// The three keywords a raw identifier cannot rescue — `r#crate`, `r#self` and `r#super` are each
/// their own error. Verified the same way as [`RUST_KEYWORDS`].
const UNESCAPABLE_KEYWORDS: &[&str] = &["crate", "self", "super"];

/// The token that names `provider`'s module: the name itself, or `r#name` when it is a keyword.
///
/// `providers/` admits `-` in a file stem — correct everywhere else a provider name goes, since it
/// becomes the artifact file name and the op-id prefix — but `pub(crate) mod google-ads;` does not
/// parse. While the index was hand-written that compile error landed on the human writing the line;
/// generated, it would ship a `crates/catalog` that does not build from an input that looks entirely
/// ordinary.
///
/// **A keyword is escaped rather than refused, and that is a deliberate difference.** `box.com` is
/// squarely inside the charter, and `mod box;` is a compile error — but the fix costs nothing a user
/// can see: `mod r#box;` resolves to the same `generated/box.rs` the build already writes, and the
/// provider id stays `box` in every address, file name and catalogue row. Refusing would force
/// `providers/boxcom.toml` instead, which changes the op-id prefix and the installable artifact
/// name — a published address rewritten to work around a detail of one generated file, which
/// AGENTS.md's "an address, once published, is not reused" exists to prevent.
///
/// What is still refused is what cannot be expressed at all: a name outside the identifier
/// character set, and the three keywords no `r#` accepts.
fn module_ident(provider: &str) -> Result<String> {
    let mut chars = provider.chars();
    let valid = match chars.next() {
        Some(first) if first.is_ascii_lowercase() || first == '_' => {
            chars.all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')
        }
        _ => false,
    };
    if !valid || provider == "_" {
        bail!(
            "provider `{provider}` cannot name a Rust module, so `crates/catalog/src/generated.rs` \
             would not compile: rename it to lowercase ASCII letters, digits and `_` (a `-` is fine \
             everywhere else a provider name goes, but not here)"
        );
    }
    if UNESCAPABLE_KEYWORDS.contains(&provider) {
        bail!(
            "provider `{provider}` cannot name a Rust module: it is one of the three keywords a raw \
             identifier cannot rescue either, so neither `mod {provider};` nor `mod r#{provider};` \
             compiles. Rename the provider file"
        );
    }
    if RUST_KEYWORDS.contains(&provider) {
        // `mod r#box;` still resolves to `generated/box.rs`, so nothing outside this file moves.
        return Ok(format!("r#{provider}"));
    }
    Ok(provider.to_string())
}

/// The operation a rendering describes — **and the refusal that keeps the third member kind out of
/// every emitted artifact** (C-83).
///
/// Both catalogue backends resolve a rendering through this one function, the same way both share
/// [`credential_mechanisms`] and [`host_of`], so neither can be talked into publishing something the
/// other refuses.
///
/// # Why an event gets its own error
///
/// A rendering whose id names nothing is a bug. A rendering whose id names an **event or a channel
/// binding** is a specific bug with a specific name, and it is the one `AGENTS.md` calls out: *"the
/// tempting wrong output is an event dressed up as a pollable op."* Both kinds are emitted into no
/// Flux module at all — flux lifts `op` declarations only, while `channel` and `trigger` are Program
/// members an operator writes — so a rendering for one could only have been produced by an emitter
/// that decided to synthesise a poll loop, which is this repository writing a runtime.
///
/// Reported separately because the two have opposite fixes. "No such operation" says a name is
/// wrong; this says the name is *right* and the pipeline is wrong, and a generic message would send
/// the reader looking for a typo that is not there.
pub(crate) fn operation_for<'a>(connector: &'a Connector, id: &str) -> Result<&'a Operation> {
    if let Some(operation) = connector.operation(id) {
        return Ok(operation);
    }
    if let Some(kind) = inbound_member_kind(connector, id) {
        bail!(
            "connector `{}`: `{id}` is {kind}, not an operation, so there is no Flux to publish for \
             it. A binding declares and never installs: it reaches the manifest and the catalogue \
             and is emitted into no module, because flux lifts `op` declarations only. Emitting one \
             would be an event dressed up as a pollable op, which this pipeline refuses rather than \
             degrades to",
            connector.id
        );
    }
    bail!(
        "connector `{}` has no operation `{id}` to describe",
        connector.id
    );
}

/// Which inbound member kind `name` denotes, or `None` when it denotes neither.
///
/// The three member kinds share one namespace per service, so at most one of these matches.
fn inbound_member_kind(connector: &Connector, name: &str) -> Option<&'static str> {
    if connector.event(name).is_some() {
        return Some("an event");
    }
    if connector.channel(name).is_some() {
        return Some("a channel binding");
    }
    None
}

/// One `crate::Operation { … }` literal.
fn entry(connector: &Connector, operation: &Operation, host: &str) -> String {
    let mut out = String::from("    crate::Operation {\n");
    out.push_str(&format!("        id: {},\n", string(&operation.id)));
    out.push_str(&format!("        provider: {},\n", string(&connector.id)));
    // The service, carried rather than elided (C-197). It is what makes `hosts` below legible — a
    // multi-service provider reaches a different host per service — and it is the key a consumer
    // needs in order to keep two services' same-named configuration variables apart. The reserved
    // `default` is written out here: elision is an *address* rule, and a consumer grouping by
    // service unconditionally needs a name in every row.
    out.push_str(&format!(
        "        service: {},\n",
        string(&operation.service)
    ));
    out.push_str(&format!(
        "        direction: crate::OperationDirection::{},\n",
        match operation.direction {
            connector_spec::OperationDirection::Read => "Read",
            connector_spec::OperationDirection::Write => "Write",
        }
    ));
    out.push_str(&format!(
        "        description: {},\n",
        string(&operation.description)
    ));
    out.push_str(&format!("        risk: {},\n", risk(operation.risk)));
    out.push_str(&format!(
        "        idempotency: {},\n",
        idempotency(operation.idempotency)
    ));
    out.push_str(&format!(
        "        semantic_effects: {},\n",
        semantic_effects(operation)
    ));
    out.push_str(&format!(
        "        credentials: {},\n",
        credentials(connector, operation)
    ));
    // Why that list is what it is — the distinction an empty slice cannot make (C-235). Emitted
    // beside the list rather than folded into it: `Operation::credentials`'s type is the catalog
    // crate's published API, and a consumer already matching on the mechanism shape must keep
    // working.
    out.push_str(&format!(
        "        credential_requirement: {},\n",
        credential_requirement(connector, operation)
    ));
    out.push_str(&format!("        hosts: &[{}],\n", string(host)));
    // Escaped like every other literal here rather than interpolated raw. An id that reaches this
    // point is already constrained — the emitter refuses anything Flux cannot declare — but the
    // path is still a string literal, and one unescaped character in it is a generated file that
    // does not compile for a reason nobody can see in the provider TOML.
    out.push_str(&format!(
        "        flux: include_str!({}),\n",
        string(&format!(
            "../../ops/{}/{}.{}",
            connector.id,
            operation.id,
            crate::workspace::MODULE_EXT
        ))
    ));
    out.push_str("    },\n");
    out
}

/// The operation's credentials as alternatives (OR) of mechanisms (AND) — the IR's own shape,
/// carried across rather than flattened.
///
/// Flattening is the thing to avoid: babelforce's `accessId` + `accessToken` travel **together** on
/// one request and are an alternative to OAuth2, so a flat list of three names would tell a caller
/// that any one of them authenticates, which is false in both directions.
fn credentials(connector: &Connector, operation: &Operation) -> String {
    let mechanisms = credential_mechanisms(connector, operation);
    let rendered: Vec<String> = mechanisms
        .iter()
        .map(|mechanism| {
            let names: Vec<String> = mechanism.iter().map(|name| string(name)).collect();
            format!("&[{}]", names.join(", "))
        })
        .collect();
    format!("&[{}]", rendered.join(", "))
}

/// The operation's credentials as alternatives (OR) of mechanisms (AND), as plain data.
///
/// The one walk both catalogue backends share: this module quotes it into Rust literals and
/// [`crate::site`] serializes it into JSON, so the crate cannot ship a `catalog.json` that
/// disagrees with `crates/catalog` about what authenticates an operation.
///
/// Resolved through [`Connector::effective_auth`], never by reading `Operation::auth` directly: an
/// operation that declares nothing inherits the connector default, and one that declares an
/// explicit empty list inherits nothing.
pub(crate) fn credential_mechanisms<'a>(
    connector: &'a Connector,
    operation: &'a Operation,
) -> Vec<Vec<&'a str>> {
    connector
        .effective_auth(operation)
        .iter()
        .map(|mechanism| mechanism.iter().map(String::as_str).collect())
        .collect()
}

/// `crate::status::CredentialRequirement` as the catalog's own mirror of it — C-235.
///
/// Exhaustive for the same reason [`risk`] is, and with the same two-sided guarantee: a state added
/// to the classification is a compile error here until someone names its counterpart, and naming a
/// counterpart `catalog::CredentialRequirement` does not have fails to compile in `crates/catalog`.
///
/// The classification itself lives in [`crate::status`], which is also what turns it into
/// `catalog.json`'s [`Issue`](crate::status::Issue) or [`Note`](crate::status::Note). One
/// derivation, two renderings — the published catalogue and the embedded one cannot answer this
/// question differently, which is the drift C-206 and C-212 each closed one surface at a time.
fn credential_requirement(connector: &Connector, operation: &Operation) -> &'static str {
    use crate::status::CredentialRequirement;
    match crate::status::credential_requirement(connector, operation) {
        CredentialRequirement::Declared => "crate::CredentialRequirement::Declared",
        CredentialRequirement::NoneRequired => "crate::CredentialRequirement::NoneRequired",
        CredentialRequirement::Withheld => "crate::CredentialRequirement::Withheld",
    }
}

/// The host a call reaches, taken from the connector's base URL with its templating intact.
///
/// `https://{subdomain}.zendesk.com` yields `{subdomain}.zendesk.com`: the tenant is the operator's
/// to choose, and substituting a placeholder here would invent one. A caller reads this to decide
/// whether their egress policy admits the call, and a pattern is the honest answer to that.
///
/// C-10 replaces this with the manifest's real `http_hosts` allowlist, which is why the catalog
/// field is a slice: today every operation reaches exactly the connector's own host.
///
/// Shared with [`crate::site`] so that `catalog.json` and `crates/catalog` name the same host — two
/// answers to "which host does this reach?" would be one answer too many.
pub(crate) fn host_of(base_url: &str) -> Result<&str> {
    let after_scheme = base_url
        .split_once("://")
        .map_or(base_url, |(_scheme, rest)| rest);
    let host = after_scheme
        .split(['/', '?', '#'])
        .next()
        .unwrap_or(after_scheme);
    if host.is_empty() {
        bail!("base URL `{base_url}` names no host, so nothing can say which host it reaches");
    }
    Ok(host)
}

/// The connector's `AUTH` table: one `crate::Credential` per declared credential (C-116).
///
/// **This is a declaration, never a value.** [`string`] quotes a credential *name*, a path leaf, a
/// header name, a placement prefix and environment-variable *keys*. That it cannot quote a value is
/// structural rather than careful: `connector_spec::AuthMethod` has no field one could live in — `env`
/// and `user_env` are key lists, and `user_suffix` is Zendesk's public `/token` marker
/// (`crates/connector-spec/src/auth.rs`) — so an emitter that wanted to leak a credential would have
/// to change the IR first, which is a reviewed change in a different crate.
///
/// It exists because the Tool pack assembles auth in Rust — the `Bearer` prefix, the basic-auth
/// base64, the query placement — and it cannot assemble what it has not been told. Until this, the
/// catalogue named the credentials an operation required and said nothing about how any of them
/// reached the wire, so the only thing a consumer could do with a credential name was ignore it.
fn render_auth(connector: &Connector) -> Result<String> {
    let mut out = String::from("#[rustfmt::skip]\n");
    out.push_str("static AUTH: &[crate::Credential] = &[\n");
    for method in &connector.auth {
        // The leaf of the credential's address. Derived by the type that owns the rule rather than
        // by stripping a prefix here: a name whose prefix disagrees with the connector id would
        // otherwise render a plausible path under the wrong vendor.
        let leaf = connector
            .local_credential_name(&method.name)
            .with_context(|| {
                format!("connector `{}`: credential `{}`", connector.id, method.name)
            })?;
        out.push_str("    crate::Credential {\n");
        out.push_str(&format!("        name: {},\n", string(&method.name)));
        out.push_str(&format!("        leaf: {},\n", string(leaf)));
        out.push_str(&format!(
            "        acquire: {},\n",
            acquisition(connector, method)
        ));
        out.push_str(&format!("        place: {},\n", placement(&method.scheme)));
        // Emitted even when unreviewed, deliberately. `Unstated` is a state a host must be able to
        // see — "nobody checked" and "this is an app token" call for different behaviour — so it is
        // published rather than skipped the way the *manifest* skips it to keep artifacts stable.
        out.push_str(&format!("        subject: {},\n", subject(method.subject)));
        out.push_str("    },\n");
    }
    out.push_str("];\n\n");
    Ok(out)
}

fn render_config(connector: &Connector) -> Result<String> {
    let mut out = String::from("#[rustfmt::skip]\nstatic CONFIG: &[crate::ConfigField] = &[\n");
    for field in &connector.config {
        let also_binds = field
            .also_binds
            .iter()
            .map(|binds| string(binds))
            .collect::<Vec<_>>()
            .join(", ");
        let also_services = field
            .also_services
            .iter()
            .map(|service| string(service))
            .collect::<Vec<_>>()
            .join(", ");
        let declaration = serde_json::to_string(field)?;
        out.push_str("    crate::ConfigField {\n");
        out.push_str(&format!("        name: {},\n", string(&field.name)));
        out.push_str(&format!("        service: {},\n", string(&field.service)));
        out.push_str(&format!("        label: {},\n", string(&field.label)));
        out.push_str(&format!("        help: {},\n", string(&field.help)));
        out.push_str(&format!(
            "        example: {},\n",
            option_string(field.example.as_deref())
        ));
        out.push_str(&format!(
            "        format: {},\n",
            string(field.format.word())
        ));
        out.push_str(&format!("        required: {},\n", field.required));
        out.push_str(&format!(
            "        default: {},\n",
            option_string(field.default.as_deref())
        ));
        out.push_str(&format!(
            "        approval: {},\n",
            approval(field.approval)
        ));
        out.push_str(&format!("        secret: {},\n", field.secret));
        out.push_str(&format!(
            "        docs_url: {},\n",
            option_string(field.docs_url.as_deref())
        ));
        out.push_str(&format!("        binds: {},\n", string(&field.binds)));
        out.push_str(&format!("        also_binds: &[{also_binds}],\n"));
        out.push_str(&format!("        also_services: &[{also_services}],\n"));
        out.push_str(&format!(
            "        declaration_json: {},\n",
            string(&declaration)
        ));
        out.push_str("    },\n");
    }
    out.push_str("];\n\n");
    Ok(out)
}

fn render_events(connector: &Connector) -> Result<String> {
    let mut out = String::from("#[rustfmt::skip]\nstatic EVENTS: &[crate::Event] = &[\n");
    for event in &connector.events {
        let schema = event
            .schema
            .as_ref()
            .map(serde_json::to_string)
            .transpose()?;
        let declaration = serde_json::to_string(event)?;
        out.push_str("    crate::Event {\n");
        out.push_str(&format!("        name: {},\n", string(&event.name)));
        out.push_str(&format!("        service: {},\n", string(&event.service)));
        out.push_str(&format!(
            "        description: {},\n",
            string(&event.description)
        ));
        out.push_str(&format!(
            "        wire_value: {},\n",
            option_string(event.wire_value.as_deref())
        ));
        out.push_str(&format!("        default: {},\n", event.default));
        out.push_str(&format!("        group: {},\n", string(&event.group)));
        out.push_str(&format!(
            "        schema: {},\n",
            option_string(schema.as_deref())
        ));
        out.push_str(&format!(
            "        declaration_json: {},\n",
            string(&declaration)
        ));
        out.push_str("    },\n");
    }
    out.push_str("];\n\n");
    Ok(out)
}

fn render_pairs(values: &BTreeMap<String, String>) -> String {
    values
        .iter()
        .map(|(name, value)| {
            format!(
                "crate::Pair {{ name: {}, value: {} }}",
                string(name),
                string(value)
            )
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn render_requirements(requirements: &[connector_spec::AuthRequirement]) -> String {
    let alternatives = requirements
        .iter()
        .map(|requirement| {
            let names = requirement
                .iter()
                .map(|name| string(name))
                .collect::<Vec<_>>();
            format!("&[{}]", names.join(", "))
        })
        .collect::<Vec<_>>();
    format!("&[{}]", alternatives.join(", "))
}

fn render_selector(selector: &connector_spec::Selector) -> String {
    let source = match selector.source {
        connector_spec::FieldSource::Header => "header",
        connector_spec::FieldSource::Body => "body",
    };
    format!(
        "crate::Selector {{ source: {}, name: {} }}",
        string(source),
        string(&selector.name)
    )
}

fn render_channels(connector: &Connector) -> Result<String> {
    let mut out = String::from("#[rustfmt::skip]\nstatic CHANNELS: &[crate::Channel] = &[\n");
    for channel in &connector.channels {
        let transport = match channel.transport {
            connector_spec::Transport::Webhook => "crate::ChannelTransport::Webhook",
            connector_spec::Transport::Socket => "crate::ChannelTransport::Socket",
            connector_spec::Transport::Poll => "crate::ChannelTransport::Poll",
        };
        let events = channel
            .events
            .iter()
            .map(|event| string(event))
            .collect::<Vec<_>>();
        let payload = render_pairs(&channel.payload);
        let connect = channel.connect.as_ref().map_or_else(
            || "None".to_owned(),
            |connect| {
                let subprotocols = connect
                    .subprotocols
                    .iter()
                    .map(|value| string(value))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!(
                    "Some(crate::SocketConnect {{ path: {}, query: &[{}], headers: &[{}], auth: {}, subprotocols: &[{}] }})",
                    string(&connect.path),
                    render_pairs(&connect.query),
                    render_pairs(&connect.headers),
                    render_requirements(&connect.auth),
                    subprotocols
                )
            },
        );
        let discriminator = channel.discriminator.as_ref().map_or_else(
            || "None".to_owned(),
            |selector| format!("Some({})", render_selector(selector)),
        );
        let delivery_id = channel.delivery_id.as_ref().map_or_else(
            || "None".to_owned(),
            |selector| format!("Some({})", render_selector(selector)),
        );
        let declaration = serde_json::to_string(channel)?;
        out.push_str("    crate::Channel {\n");
        out.push_str(&format!("        name: {},\n", string(&channel.name)));
        out.push_str(&format!("        service: {},\n", string(&channel.service)));
        out.push_str(&format!(
            "        base_url: {},\n",
            string(connector.base_url_of(&channel.service))
        ));
        out.push_str(&format!(
            "        description: {},\n",
            string(&channel.description)
        ));
        out.push_str(&format!("        transport: {transport},\n"));
        out.push_str(&format!("        events: &[{}],\n", events.join(", ")));
        out.push_str(&format!("        connect: {connect},\n"));
        out.push_str(&format!("        discriminator: {discriminator},\n"));
        out.push_str(&format!("        delivery_id: {delivery_id},\n"));
        out.push_str(&format!("        payload: &[{payload}],\n"));
        out.push_str(&format!(
            "        payload_root: {},\n",
            channel.payload_root
        ));
        out.push_str(&format!(
            "        declaration_json: {},\n",
            string(&declaration)
        ));
        out.push_str("    },\n");
    }
    out.push_str("];\n\n");
    Ok(out)
}

/// **The closed sets a connector's configuration fields declare** — C-225.
///
/// Only the fields that *have* one, so the common connector emits an empty slice and the diff of a
/// provider adopting a set is one block. This is not the whole configuration surface: labels, help,
/// `binds` and the derived level are C-87's, and this publishes exactly the part a closed set is
/// worthless without. A renderer that cannot see the choices draws a text box, which is the state
/// the story exists to leave.
///
/// The row is keyed by `(service, kind, name)` — the same address `connector-pack`'s configuration
/// port stores a value under — so a consumer joins on it without re-parsing `binds`. A field whose
/// binding is malformed contributes nothing, which cannot happen on a loaded connector: `binds` is
/// validated at load, and this runs on the IR.
fn render_config_choices(connector: &Connector) -> String {
    let mut out = String::from("#[rustfmt::skip]\n");
    out.push_str("static CONFIG_CHOICES: &[crate::ConfigChoices] = &[\n");
    for field in &connector.config {
        let Some(binding) = field.binding().filter(|_| field.is_closed()) else {
            continue;
        };
        out.push_str("    crate::ConfigChoices {\n");
        out.push_str(&format!("        service: {},\n", string(&field.service)));
        out.push_str(&format!("        field: {},\n", string(&field.name)));
        out.push_str(&format!("        label: {},\n", string(&field.label)));
        out.push_str(&format!("        kind: {},\n", string(binding.kind())));
        out.push_str(&format!("        name: {},\n", string(binding.target())));
        out.push_str("        choices: &[\n");
        for choice in &field.choices {
            out.push_str(&format!(
                "            crate::Choice {{ value: {}, label: {} }},\n",
                string(&choice.value),
                string(&choice.label)
            ));
        }
        out.push_str("        ],\n");
        out.push_str("    },\n");
    }
    out.push_str("];\n\n");
    out
}

/// The acquisition axis: how stored material becomes the value that is placed.
///
/// `Basic` is the only scheme that composes anything, and it composes the **user** half — which is
/// config rather than a gated secret, so it resolves from declared environment variables and never
/// from the secret store.
///
/// # The minting join (C-136)
///
/// One answer on this axis is not a property of the credential's own declaration at all: a
/// credential minted by one of this connector's operations is `Acquisition::Minted`, and the two
/// facts it carries — which operation, and where in that operation's answer the secret arrives —
/// are stated in the `[[operations]]` block rather than in `[[auth]]`. So this reads the whole
/// connector and joins the two sides by credential name.
///
/// The loader has already refused every arrangement that would make the join ambiguous or
/// unresolvable: a `produces_credential` naming a credential no `[[auth]]` block declares, and two
/// operations minting one credential. So the `find` below is a lookup, not a search with a
/// tie-break — and `Minted` wins over the scheme-derived answer because a minted credential's
/// *placement* is unaffected by it (`Bearer` stays `Bearer`); what changes is only the provenance.
fn acquisition(connector: &Connector, method: &connector_spec::AuthMethod) -> String {
    // OAuth2 is answered first, and the loader has already refused the one arrangement where that
    // ordering could matter: a credential declaring `[auth.oauth2]` *and* named by an operation's
    // `produces_credential` states two contradictory acquisitions, and is refused rather than
    // silently resolved here (C-525). So this is a lookup, not a precedence rule doing real work.
    if let Some(oauth2) = &method.oauth2 {
        return oauth2_acquisition(oauth2);
    }

    if let Some((operation, produced)) = connector.operations.iter().find_map(|operation| {
        operation
            .produces_credential
            .as_ref()
            .filter(|produced| produced.credential == method.name)
            .map(|produced| (operation, produced))
    }) {
        return format!(
            "crate::Acquisition::Minted {{ by: {}, from: {} }}",
            string(&operation.id),
            string(&produced.secret)
        );
    }

    match method.scheme {
        AuthScheme::Basic => format!(
            "crate::Acquisition::BasicJoin {{ user_env: &[{}], user_suffix: {} }}",
            method
                .user_env
                .iter()
                .map(|key| string(key))
                .collect::<Vec<_>>()
                .join(", "),
            string(method.user_suffix.as_deref().unwrap_or_default())
        ),
        _ => "crate::Acquisition::Static".to_string(),
    }
}

/// The subject axis: whose authority the credential carries (C-528).
///
/// Exhaustive, for the reason [`placement`] is. There are only three answers and one of them means
/// "unreviewed"; a catch-all arm would map a fourth to whichever neighbour was listed last, and on
/// this axis the wrong neighbour is either an over-grant or a silent failure.
fn subject(subject: connector_spec::Subject) -> &'static str {
    match subject {
        connector_spec::Subject::Unstated => "crate::Subject::Unstated",
        connector_spec::Subject::App => "crate::Subject::App",
        connector_spec::Subject::User => "crate::Subject::User",
    }
}

/// The OAuth2 acquisition, rendered as a `&'static` the catalogue can hold (C-525).
///
/// `&crate::OAuth2 { … }` is a borrow of a temporary, which is legal here for one specific reason:
/// every field is a constant with no `Drop` and no interior mutability, so const promotion lifts it
/// to `'static` in the `static AUTH` initializer. A field that ever stopped being const would fail
/// to compile rather than silently allocate — which is the property that keeps the catalogue
/// dependency-free.
///
/// **Nothing here can carry a value.** `client_id` is public by specification; the scopes, paths and
/// grants are vendor facts. The client secret is a `[[config]]` binding, resolved by the host from
/// its own store, and there is no field on `OAuth2Spec` it could travel in.
fn oauth2_acquisition(spec: &connector_spec::OAuth2Spec) -> String {
    let scopes = spec
        .scopes
        .iter()
        .map(|scope| string(scope))
        .collect::<Vec<_>>()
        .join(", ");
    let grants = spec
        .grants
        .iter()
        .map(|grant| {
            // Exhaustive, for the reason `placement` is: a grant mapped to the wrong variant runs
            // the wrong flow, and a catch-all arm is how a new one gets mapped to a plausible
            // neighbour instead of failing the build.
            let variant = match grant {
                connector_spec::OAuthGrant::AuthorizationCode => "AuthorizationCode",
                connector_spec::OAuthGrant::Password => "Password",
                connector_spec::OAuthGrant::RefreshToken => "RefreshToken",
                connector_spec::OAuthGrant::ClientCredentials => "ClientCredentials",
            };
            format!("crate::OAuthGrant::{variant}")
        })
        .collect::<Vec<_>>()
        .join(", ");
    let redirect = match &spec.redirect {
        Some(redirect) => format!(
            "Some(crate::OAuthRedirect {{ port: {}, path: {} }})",
            redirect.port,
            string(&redirect.path)
        ),
        None => "None".to_string(),
    };

    format!(
        "crate::Acquisition::OAuth2(&crate::OAuth2 {{ endpoint: {}, authorize_path: {}, \
         token_path: {}, client_id: {}, scopes: &[{scopes}], grants: &[{grants}], \
         redirect: {redirect} }})",
        string(&spec.endpoint),
        string(&spec.authorize_path),
        string(&spec.token_path),
        string(&spec.client_id),
    )
}

/// The placement axis: where the value goes on the request.
///
/// An exhaustive match, for the reason [`risk`] is one — and with more at stake. A scheme this did
/// not recognise would have to become *some* placement, and every wrong answer either sends a
/// credential where the vendor does not read it or sends it somewhere it should never go at all.
///
/// The `prefix` is what makes this a mapping rather than a translation table: `Bearer` and `Basic`
/// differ from a raw-value header only by the literal text in front of the value.
pub(crate) fn placement(scheme: &AuthScheme) -> String {
    match scheme {
        AuthScheme::Bearer => {
            "crate::Placement::Header { name: \"Authorization\", prefix: \"Bearer \" }".to_string()
        }
        AuthScheme::Basic => {
            "crate::Placement::Header { name: \"Authorization\", prefix: \"Basic \" }".to_string()
        }
        // The declared prefix, and the reason this arm reads like the two above it: `Bearer ` and a
        // vendor's `SSWS ` differ only in who wrote the literal. An empty prefix — every shipped
        // `header` credential before C-184 — emits exactly the string this arm emitted when it was
        // hard-coded, which is what keeps the committed catalogue byte-identical.
        AuthScheme::Header { name, prefix } => format!(
            "crate::Placement::Header {{ name: {}, prefix: {} }}",
            string(name),
            string(prefix)
        ),
        AuthScheme::Query { name } => {
            format!("crate::Placement::Query {{ name: {} }}", string(name))
        }
        // The one scheme with no outgoing answer: it verifies bytes that arrived. Carried into the
        // catalogue rather than dropped, so that one namespace still covers both directions and a
        // consumer can *refuse* to spend it on a request rather than never having heard of it.
        AuthScheme::Signing => "crate::Placement::Inbound".to_string(),
    }
}

/// A Rust `Option<&'static str>` literal for an optional declared value.
fn option_string(value: Option<&str>) -> String {
    match value {
        Some(value) => format!("Some({})", string(value)),
        None => "None".to_string(),
    }
}

/// `connector_spec::Risk` as the catalog's own mirror of it.
///
/// An exhaustive match, deliberately: a variant added to the IR is a compile error here rather than
/// a silent gap in the catalog.
fn risk(risk: Risk) -> &'static str {
    match risk {
        Risk::Low => "crate::Risk::Low",
        Risk::Medium => "crate::Risk::Medium",
        Risk::High => "crate::Risk::High",
        Risk::Destructive => "crate::Risk::Destructive",
    }
}

/// `connector_spec::Runtime` as the catalog's mirror — C-405. Exhaustive for the same reason
/// [`risk`] is, and it is the mechanical half of "the two vocabularies do not drift": a variant
/// added to the loader's enum fails to compile here until someone names its counterpart, and naming
/// a counterpart `catalog::Runtime` does not have fails to compile in `crates/catalog`.
fn runtime(runtime: connector_spec::Runtime) -> &'static str {
    use connector_spec::Runtime;
    match runtime {
        Runtime::Http => "crate::Runtime::Http",
        Runtime::Socket => "crate::Runtime::Socket",
        Runtime::Process => "crate::Runtime::Process",
        Runtime::Container => "crate::Runtime::Container",
        Runtime::Plugin => "crate::Runtime::Plugin",
        Runtime::Remote => "crate::Runtime::Remote",
    }
}

/// `connector_spec::Approval` as the catalogue's closed mirror.
///
/// Exhaustive on purpose: adding a policy to the declaration cannot silently become ordinary
/// activation in a consumer that only sees the embedded catalogue.
fn approval(approval: connector_spec::Approval) -> &'static str {
    use connector_spec::Approval;
    match approval {
        Approval::None => "crate::Approval::None",
        Approval::Operator => "crate::Approval::Operator",
    }
}

/// `connector_spec::Idempotency` as the catalog's mirror. Exhaustive for the same reason.
fn idempotency(idempotency: Idempotency) -> &'static str {
    match idempotency {
        Idempotency::Idempotent => "crate::Idempotency::Idempotent",
        Idempotency::NonIdempotent => "crate::Idempotency::NonIdempotent",
        Idempotency::Conditional => "crate::Idempotency::Conditional",
    }
}

/// Semantic effects stay string data in the dependency-free catalogue, using the exact Flux tags
/// the IR validated rather than a second enum consumers would have to translate.
fn semantic_effects(operation: &Operation) -> String {
    let values = operation
        .semantic_effects
        .iter()
        .map(|effect| string(effect.tag()))
        .collect::<Vec<_>>()
        .join(", ");
    format!("&[{values}]")
}

/// A Rust string literal for `value`.
///
/// Escaping rather than a raw literal: a raw string would have to pick a hash count no content
/// collides with, and a description carrying `"#` would silently end the literal early. Every
/// character that could close or continue the literal is escaped, and the remaining control
/// characters go out as `\u{…}` so the generated file stays plain ASCII-safe text a reviewer can
/// read in a diff.
fn string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for character in value.chars() {
        match character {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\0' => out.push_str("\\0"),
            other if other.is_control() => out.push_str(&format!("\\u{{{:x}}}", other as u32)),
            other => out.push(other),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use connector_spec::{
        Approval, AuthMethod, AuthRequirement, ConfigField, Format, HttpMethod, ParamSet, Quirks,
        DEFAULT_SERVICE,
    };

    fn operation(id: &str) -> Operation {
        Operation {
            id: id.to_string(),
            service: DEFAULT_SERVICE.to_string(),
            method: HttpMethod::Get,
            direction: connector_spec::OperationDirection::Read,
            path: "/v2/things".to_string(),
            description: "Do a thing".to_string(),
            risk: Risk::Low,
            idempotency: Idempotency::Idempotent,
            semantic_effects: Vec::new(),
            repeatable_because: None,
            expose: true,
            auth: None,
            params: ParamSet::default(),
            response_schema: None,
            credential_response: Vec::new(),
            produces_credential: None,
            quirks: Quirks::default(),
        }
    }

    fn connector() -> Connector {
        Connector {
            id: "acme".to_string(),
            authority: None,
            runtime: connector_spec::Runtime::Http,
            api_version: None,
            services: Vec::new(),
            vendor: "Acme".to_string(),
            base_url: "https://{tenant}.acme.example/api".to_string(),
            description: "Acme".to_string(),
            auth: vec![
                AuthMethod::header("acme.access_id", "X-Id", vec!["ACME_ID".to_string()]),
                AuthMethod::header(
                    "acme.access_token",
                    "X-Token",
                    vec!["ACME_TOKEN".to_string()],
                ),
            ],
            default_auth: vec![AuthRequirement::all([
                "acme.access_id",
                "acme.access_token",
            ])],
            operations: vec![operation("acme-thing-list")],
            events: Vec::new(),
            channels: Vec::new(),
            config: Vec::new(),
            verify: None,
            graphs: Vec::new(),
            provenance: Default::default(),
        }
    }

    fn renderings() -> Vec<OperationRendering> {
        vec![OperationRendering {
            id: "acme-thing-list".to_string(),
            source: "op acme-thing-list -> Any\n".to_string(),
        }]
    }

    #[test]
    fn rendering_is_deterministic() {
        let first = render(&connector(), &renderings()).unwrap();
        let second = render(&connector(), &renderings()).unwrap();
        assert_eq!(first, second);
    }

    #[test]
    fn config_approval_is_emitted_as_a_closed_catalogue_variant() {
        let mut connector = connector();
        connector.config.push(ConfigField {
            name: "tenant".to_string(),
            service: DEFAULT_SERVICE.to_string(),
            label: "Acme tenant".to_string(),
            help: "The approved Acme tenant origin.".to_string(),
            example: Some("acme".to_string()),
            format: Format::Text,
            choices: Vec::new(),
            required: true,
            default: None,
            approval: Approval::Operator,
            secret: false,
            docs_url: None,
            binds: "endpoint.tenant".to_string(),
            also_binds: Vec::new(),
            also_services: Vec::new(),
        });

        let rendered = render(&connector, &renderings()).unwrap();
        assert!(
            rendered.contains("approval: crate::Approval::Operator,"),
            "{rendered}"
        );
    }

    #[test]
    fn provider_verify_is_emitted_as_typed_catalogue_data() {
        let mut connector = connector();
        connector.verify = Some("acme-thing-list".to_string());

        let rendered = render(&connector, &renderings()).unwrap();
        assert!(
            rendered.contains("verify: Some(\"acme-thing-list\"),"),
            "{rendered}"
        );

        connector.verify = None;
        let rendered = render(&connector, &renderings()).unwrap();
        assert!(rendered.contains("verify: None,"), "{rendered}");
    }

    /// **The generated artifact carries the scheme word and a credential *reference*, and nothing
    /// that resolves to a secret (C-184).**
    ///
    /// This is the constraint the prefix axis is built around, asserted where it can actually fail:
    /// on the emitted table rather than on the IR. `SSWS ` is connector data — the vendor prints it
    /// in its own documentation — and it is *supposed* to be committed verbatim. What must never be
    /// here is the value it precedes.
    ///
    /// The positive assertions are what keep the negative ones from passing vacuously: a table that
    /// emitted neither the prefix nor the credential name would satisfy "no secret" trivially while
    /// publishing a connector that cannot authenticate.
    #[test]
    fn a_prefixed_credential_emits_its_scheme_word_and_only_a_credential_reference() {
        /// Shapes a real Okta credential carries. None is in this repository; the assertion is that
        /// the emitter has no path that could put one here.
        const VALUE_SHAPES: [&str; 3] = ["00a1b2c3", "SSWS00", "ssws_token_value"];

        let mut connector = connector();
        connector.auth = vec![AuthMethod::prefixed_header(
            "acme.api_token",
            "Authorization",
            "SSWS ",
            vec!["ACME_API_TOKEN".to_string()],
        )];
        connector.default_auth = vec![AuthRequirement::single("acme.api_token")];

        let table = render(&connector, &renderings()).unwrap();

        // The scheme word reaches the placement, spelled exactly — trailing space included, since
        // the space is part of the literal and not a separator anything inserts later.
        assert!(
            table
                .contains(r#"crate::Placement::Header { name: "Authorization", prefix: "SSWS " }"#),
            "the declared prefix must reach the emitted placement: {table}"
        );
        // A reference to the credential — its flat-namespace name and its leaf — and that is the
        // whole of what the table says about how the value is obtained.
        assert!(table.contains(r#"name: "acme.api_token""#), "{table}");
        assert!(table.contains(r#"leaf: "api_token""#), "{table}");
        // **Not even the environment variable.** A `Static` acquisition emits no `env` at all: the
        // value is addressed through the secret store, and the declared variables are a `[[config]]`
        // concern rather than something the pack reads from here. Only `BasicJoin` emits names, and
        // those are the *user* half, which is config and not a gated secret.
        assert!(
            !table.contains("ACME_API_TOKEN"),
            "a static credential's env var is not part of the emitted table: {table}"
        );
        // And nothing that is, or looks like, the value itself.
        for shape in VALUE_SHAPES {
            assert!(
                !table.contains(shape),
                "a credential value shaped {shape:?} reached the emitted catalogue: {table}"
            );
        }
    }

    /// The empty prefix emits the identical string the arm produced when it was hard-coded, which is
    /// what keeps every provider authored before C-184 byte-identical. The whole-tree version of this
    /// is `tests/catalog_artifacts.rs::the_committed_tree_is_a_fixed_point_of_a_build`; this is the
    /// one line that decides it.
    #[test]
    fn an_absent_prefix_emits_exactly_what_the_hard_coded_arm_emitted() {
        let table = render(&connector(), &renderings()).unwrap();
        assert!(
            table.contains(r#"crate::Placement::Header { name: "X-Id", prefix: "" }"#),
            "{table}"
        );
        assert_eq!(
            placement(&AuthScheme::Bearer),
            r#"crate::Placement::Header { name: "Authorization", prefix: "Bearer " }"#,
            "the two presets are prefixes with names; respelling one moves 31 credentials' artifacts"
        );
    }

    /// The table embeds the file the same build wrote, at the path it wrote it to. A wrong relative
    /// path is a compile error in the catalog crate, but only once someone builds it.
    #[test]
    fn each_entry_embeds_its_own_rendering() {
        let rendered = render(&connector(), &renderings()).unwrap();
        assert!(
            rendered.contains("flux: include_str!(\"../../ops/acme/acme-thing-list.flux\"),"),
            "{rendered}"
        );
    }

    /// **The AND/OR shape survives.** Two credentials on one request must not read as two ways to
    /// authenticate.
    #[test]
    fn an_and_group_stays_one_mechanism() {
        let rendered = render(&connector(), &renderings()).unwrap();
        assert!(
            rendered.contains(r#"credentials: &[&["acme.access_id", "acme.access_token"]],"#),
            "{rendered}"
        );
    }

    /// An operation that declares an explicit empty list inherits nothing — the distinction
    /// `Connector::effective_auth` exists to preserve.
    #[test]
    fn an_explicitly_unauthenticated_operation_names_no_credential() {
        let mut connector = connector();
        connector.operations[0].auth = Some(vec![]);
        let rendered = render(&connector, &renderings()).unwrap();
        assert!(rendered.contains("credentials: &[],"), "{rendered}");
    }

    /// **The three states reach the table** — C-235.
    ///
    /// The mechanism list is unchanged in all three; what moves is the field beside it, which is
    /// the whole of the story: `credentials: &[]` had two opposite meanings and the table said
    /// neither of them.
    #[test]
    fn the_table_says_why_an_operation_names_no_credential() {
        let mut connector = connector();

        // Authenticated: the connector's default applies.
        assert!(render(&connector, &renderings())
            .unwrap()
            .contains("credential_requirement: crate::CredentialRequirement::Declared,"));

        // Positively public: the operation declares that the vendor needs nothing.
        let mut public = connector.clone();
        public.operations[0].auth = Some(vec![]);
        let public = render(&public, &renderings()).unwrap();
        assert!(
            public.contains("credential_requirement: crate::CredentialRequirement::NoneRequired,"),
            "{public}"
        );

        // Withheld: nothing is declared, and nothing declares that nothing is needed. Freshdesk.
        connector.auth.clear();
        connector.default_auth.clear();
        let withheld = render(&connector, &renderings()).unwrap();
        assert!(
            withheld.contains("credential_requirement: crate::CredentialRequirement::Withheld,"),
            "{withheld}"
        );

        // And the two empty ones are told apart while naming the same (absent) credentials.
        assert_ne!(public, withheld);
        for rendered in [&public, &withheld] {
            assert!(rendered.contains("credentials: &[],"), "{rendered}");
        }
    }

    /// **One derivation, two renderings.** The table's requirement is `crate::status`'s
    /// classification and not a second walk of the same two fields, so the embedded catalogue and
    /// `catalog.json` cannot answer this question differently — which is the drift C-206 closed on
    /// one surface and C-212 on another.
    #[test]
    fn the_table_and_the_published_status_read_the_same_classification() {
        use crate::status::{self, CredentialRequirement, NO_CREDENTIAL, NO_CREDENTIAL_REQUIRED};

        let mut connector = connector();
        connector.auth.clear();
        connector.default_auth.clear();

        let withheld = &connector.operations[0];
        assert_eq!(
            status::credential_requirement(&connector, withheld),
            CredentialRequirement::Withheld
        );
        // The credential codes only: this fixture's base URL is templated, so it also carries
        // `unbound-base-url-template`, which is a different rule and not what is under test.
        assert!(
            status::of(&connector, withheld)
                .issues
                .iter()
                .any(|issue| issue.code == NO_CREDENTIAL),
            "the published issue and the emitted requirement must name the same state"
        );

        let mut public = connector.clone();
        public.operations[0].auth = Some(vec![]);
        assert_eq!(
            status::credential_requirement(&public, &public.operations[0]),
            CredentialRequirement::NoneRequired
        );
        assert_eq!(
            status::of(&public, &public.operations[0])
                .notes
                .iter()
                .map(|note| note.code)
                .collect::<Vec<_>>(),
            vec![NO_CREDENTIAL_REQUIRED]
        );

        // And the classification carries the published codes rather than restating them.
        assert_eq!(
            CredentialRequirement::NoneRequired.code(),
            Some(NO_CREDENTIAL_REQUIRED)
        );
        assert_eq!(CredentialRequirement::Withheld.code(), Some(NO_CREDENTIAL));
        assert_eq!(CredentialRequirement::Declared.code(), None);
    }

    #[test]
    fn the_host_keeps_its_templating_and_drops_the_path() {
        assert_eq!(
            host_of("https://{subdomain}.zendesk.com").unwrap(),
            "{subdomain}.zendesk.com"
        );
        assert_eq!(
            host_of("https://example.freshdesk.com/api/v2").unwrap(),
            "example.freshdesk.com"
        );
        assert!(host_of("https://").is_err());
    }

    /// A description carrying a quote or a backslash must not break out of its literal — the one
    /// way generated Rust stops compiling for a reason nobody can see in the provider file.
    #[test]
    fn quotes_and_backslashes_are_escaped() {
        assert_eq!(string(r#"a "b" \ c"#), r#""a \"b\" \\ c""#);
        assert_eq!(string("a\nb"), r#""a\nb""#);
    }

    fn ids(names: &[&str]) -> Vec<String> {
        names.iter().map(|name| name.to_string()).collect()
    }

    /// The index names every provider it was given, in the order it was given them — which is
    /// discovery order, which is sorted. A `PROVIDERS` slice that did not match the `mod` lines
    /// would compile only by accident.
    #[test]
    fn the_index_names_every_provider_once() {
        let rendered = render_index(&ids(&["acme", "beacon"])).unwrap();
        for provider in ["acme", "beacon"] {
            assert_eq!(
                rendered
                    .matches(&format!("pub(crate) mod {provider};"))
                    .count(),
                1,
                "{rendered}"
            );
            assert_eq!(
                rendered.matches(&format!("&{provider}::PROVIDER,")).count(),
                1,
                "{rendered}"
            );
        }
        assert!(rendered.find("mod acme").unwrap() < rendered.find("mod beacon").unwrap());
    }

    #[test]
    fn the_index_is_deterministic() {
        let providers = ids(&["acme", "beacon", "cinder"]);
        assert_eq!(
            render_index(&providers).unwrap(),
            render_index(&providers).unwrap()
        );
    }

    /// A hyphen is legal in a provider file stem and illegal in a `mod` declaration, so the emitter
    /// refuses rather than writing a `crates/catalog` that does not compile.
    #[test]
    fn a_name_that_cannot_be_a_module_is_refused() {
        for name in ["google-ads", "2fa", "Acme", "acme.core", "", "_"] {
            let error = render_index(&ids(&[name]))
                .expect_err("a name that cannot be a module must not render");
            assert!(
                format!("{error:#}").contains("cannot name a Rust module"),
                "`{name}` was refused for the wrong reason: {error:#}"
            );
        }
        render_index(&ids(&["acme_core2"])).expect("an ordinary identifier renders");
    }

    /// **A keyword provider name is escaped, not refused.** `box.com` is inside the charter, and
    /// `mod box;` is a compile error while `mod r#box;` resolves to the same `generated/box.rs`.
    ///
    /// Every keyword is exercised rather than a sample: the list is the thing that can be wrong, and
    /// a spot check of three would not notice a missing entry.
    #[test]
    fn a_keyword_provider_name_is_escaped() {
        for keyword in RUST_KEYWORDS {
            if UNESCAPABLE_KEYWORDS.contains(keyword) {
                continue;
            }
            let rendered = render_index(&ids(&[keyword])).unwrap_or_else(|error| {
                panic!("`{keyword}` must render as a raw identifier, not fail: {error:#}")
            });
            assert!(
                rendered.contains(&format!("pub(crate) mod r#{keyword};")),
                "`{keyword}` was not escaped:\n{rendered}"
            );
            assert!(
                rendered.contains(&format!("&r#{keyword}::PROVIDER,")),
                "`{keyword}`'s PROVIDERS entry was not escaped:\n{rendered}"
            );
        }
    }

    /// `union` is a *weak* keyword: `mod union {}` compiles, so escaping it would be gratuitous.
    /// This pins the one name the keyword list must not grow.
    #[test]
    fn a_weak_keyword_is_left_alone() {
        let rendered = render_index(&ids(&["union"])).expect("`union` is a legal module name");
        assert!(
            rendered.contains("pub(crate) mod union;"),
            "`union` should not be escaped:\n{rendered}"
        );
    }

    /// The three a raw identifier cannot rescue are still refused, and say so specifically rather
    /// than rendering `r#crate` — which is its own compile error.
    #[test]
    fn a_keyword_that_cannot_be_raw_is_refused() {
        for keyword in UNESCAPABLE_KEYWORDS {
            let error = render_index(&ids(&[keyword]))
                .expect_err("a keyword no raw identifier accepts must be refused");
            let rendered = format!("{error:#}");
            assert!(
                rendered.contains("cannot name a Rust module") && rendered.contains(keyword),
                "`{keyword}` was refused for the wrong reason: {rendered}"
            );
        }
    }

    /// A rendering for an operation the connector does not declare would embed a file nothing
    /// regenerates. It is a failure, not an entry that gets skipped.
    #[test]
    fn a_rendering_without_an_operation_is_refused() {
        let stray = vec![OperationRendering {
            id: "acme-thing-vanished".to_string(),
            source: String::new(),
        }];
        render(&connector(), &stray).expect_err("a stray rendering must not be rendered");
    }

    /// An `[auth.oauth2]` credential reaches the **published Rust catalogue** (C-525).
    ///
    /// The IR has modelled `OAuth2Spec` since C-90 and the manifest and `catalog.json` both carry
    /// it, but `crates/catalog` had no representation at all — which is the artifact Exchange and
    /// autodev link. Every field is asserted rather than a sample: a field silently dropped here is
    /// a grant a host cannot run, and it would look exactly like a connector that declared nothing.
    #[test]
    fn an_oauth2_credential_renders_its_whole_acquisition() {
        let mut connector = connector();
        connector.auth[0].oauth2 = Some(connector_spec::OAuth2Spec {
            endpoint: "login".to_string(),
            authorize_path: "/oauth/authorize".to_string(),
            token_path: "/oauth/token".to_string(),
            client_id: "acme-client".to_string(),
            scopes: vec!["read:thing".to_string(), "write:thing".to_string()],
            grants: vec![
                connector_spec::OAuthGrant::AuthorizationCode,
                connector_spec::OAuthGrant::RefreshToken,
            ],
            redirect: Some(connector_spec::OAuthRedirect {
                port: 8976,
                path: "/callback".to_string(),
            }),
        });

        let rendered = render_auth(&connector).expect("an oauth2 credential must render");

        assert!(
            rendered.contains("crate::Acquisition::OAuth2"),
            "the oauth2 acquisition did not reach the catalogue:\n{rendered}"
        );
        for expected in [
            r#"endpoint: "login""#,
            r#"authorize_path: "/oauth/authorize""#,
            r#"token_path: "/oauth/token""#,
            r#"client_id: "acme-client""#,
            r#"scopes: &["read:thing", "write:thing"]"#,
            "grants: &[crate::OAuthGrant::AuthorizationCode, crate::OAuthGrant::RefreshToken]",
            r#"redirect: Some(crate::OAuthRedirect { port: 8976, path: "/callback" })"#,
        ] {
            assert!(
                rendered.contains(expected),
                "`{expected}` is missing from the rendered acquisition:\n{rendered}"
            );
        }
    }

    /// **Whose authority a credential carries reaches the catalogue** (C-528).
    ///
    /// Same argument as C-525's: a declaration that stops at the IR is one Exchange and autodev
    /// cannot act on, and this axis exists precisely so a host can bound a credential's reach. The
    /// unreviewed default is published too — a host must be able to see the difference between
    /// "this is an app token" and "nobody checked", because those call for different behaviour.
    #[test]
    fn every_credential_publishes_its_subject() {
        let mut reviewed = connector();
        reviewed.auth[0].subject = connector_spec::Subject::App;
        reviewed.auth[1].subject = connector_spec::Subject::User;

        let rendered = render_auth(&reviewed).expect("subjects must render");
        assert!(
            rendered.contains("subject: crate::Subject::App"),
            "an app subject did not reach the catalogue:\n{rendered}"
        );
        assert!(
            rendered.contains("subject: crate::Subject::User"),
            "a user subject did not reach the catalogue:\n{rendered}"
        );

        let unreviewed = render_auth(&connector()).expect("the plain fixture must render");
        assert!(
            unreviewed.contains("subject: crate::Subject::Unstated"),
            "an unreviewed credential must publish `Unstated`, not nothing:\n{unreviewed}"
        );
    }

    /// A credential with no `[auth.oauth2]` block is untouched — the whole catalogue depends on it.
    #[test]
    fn a_plain_credential_is_still_static() {
        let rendered = render_auth(&connector()).expect("the plain fixture must render");
        assert!(
            rendered.contains("crate::Acquisition::Static"),
            "a plain credential stopped being Static:\n{rendered}"
        );
        assert!(
            !rendered.contains("OAuth2"),
            "a plain credential gained an oauth2 acquisition:\n{rendered}"
        );
    }
}
