//! Rendering `crates/catalog`'s generated half: one `.flux` file per operation, the Rust table that
//! embeds them, and the index naming every provider's table (C-104).
//!
//! The first two are **per provider** and a scoped build regenerates exactly what it compiled. The
//! index is not — see [`render_index`], which is the whole-catalogue half and is therefore planned
//! by a full run only.
//!
//! `connectors/<provider>.flux` stays the artifact that ships and installs into `~/.flux/flows`.
//! What is generated here is *additional* — the catalog's unit — and it is the same text: an
//! operation's rendering is byte for byte what [`crate::seam::module`] concatenates into the
//! provider module, with no header of its own, so the two can never describe different requests.
//! `crates/connector-cli/tests/catalog_artifacts.rs` pins that.
//!
//! # Why the table is Rust rather than data
//!
//! The catalog crate has **no dependencies**, and that is a feature a consumer feels: `cargo add
//! connector-catalog` costs them one crate and no runtime work. Emitting JSON or TOML alongside the
//! Flux would mean the catalog either grows a parser dependency or parses on first use behind a
//! lock — both to reconstruct, at runtime, a table already known at build time. A generated `static`
//! is that table, laid out by the compiler in `.rodata`.
//!
//! Note what this is *not*: it is not the "no homegrown DSL" or "never string-template Flux" rule
//! being bent. Not one byte of **Flux** is assembled here. The Flux comes from
//! `connector_flux::emit_operation`, which builds real `flux_lang` AST nodes and runs flux-lang's
//! own formatter over them; this module only quotes that text into an `include_str!`.
//!
//! # Two properties this rendering must hold, and how each is held
//!
//! **Deterministic.** Equal inputs produce byte-identical output — the whole reason a rebuild
//! writes nothing. Everything below is a function of the IR alone, walked in the IR's own order,
//! with no map iteration and no timestamp.
//!
//! **rustfmt-stable.** The generated file is inside `cargo fmt --all --check`'s reach, so text
//! rustfmt would rewrite fails the gate. Rather than chase rustfmt's layout from a string builder —
//! a fixed point that would have to be rediscovered on every toolchain bump — each generated item
//! carries `#[rustfmt::skip]`, which is exactly the tool attribute's purpose. The `.flux` half is
//! held to flux-lang's formatter instead, by the emitter, and that fixed point *is* asserted
//! (`connector-flux`'s `shipped_modules.rs`).

use anyhow::{bail, Result};
use connector_spec::{Connector, Idempotency, Operation, Risk};

/// One operation's `.flux` rendering, on its way to `crates/catalog/ops/<provider>/<id>.flux`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OperationRendering {
    /// The operation id — the file stem, and the catalog's key.
    pub id: String,
    /// The formatted `op` declaration, exactly as the provider module carries it.
    pub source: String,
}

/// Render `crates/catalog/src/generated/<provider>.rs`: the provider's identity, and one
/// [`catalog::Operation`](../../catalog/src/lib.rs) entry per rendering.
///
/// `renderings` is passed in rather than recomputed so that the embedded text and the provider
/// module are emitted **once**, from one call to `connector_flux::emit_operation` per operation.
/// Emitting twice would make "the catalog agrees with the module" a coincidence rather than a
/// structural fact.
pub fn render(connector: &Connector, renderings: &[OperationRendering]) -> Result<String> {
    let mut out = format!(
        "// Generated by {} — do not edit.\n\
         // Provider: {}\n\
         // Regenerate with `flux-connectors build`.\n\
         //\n\
         // The `include_str!` paths point at `crates/catalog/ops/{}/`, which the same build wrote.\n\n",
        crate::seam::generator(),
        connector.id,
        connector.id,
    );

    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub(crate) static PROVIDER: crate::Provider = crate::Provider {\n");
    out.push_str(&format!("    id: {},\n", string(&connector.id)));
    out.push_str(&format!("    vendor: {},\n", string(&connector.vendor)));
    out.push_str(&format!(
        "    description: {},\n",
        string(&connector.description)
    ));
    out.push_str(&format!("    base_url: {},\n", string(&connector.base_url)));
    out.push_str("    operations: OPERATIONS,\n");
    out.push_str("};\n\n");

    out.push_str("#[rustfmt::skip]\n");
    out.push_str("static OPERATIONS: &[crate::Operation] = &[\n");
    for rendering in renderings {
        let operation = operation_for(connector, &rendering.id)?;
        // Per operation, through its service: a multi-service provider reaches a different host per
        // service, and the union would be a wider egress claim than any single call makes (C-49).
        let host = host_of(connector.base_url_of(&operation.service))?;
        out.push_str(&entry(connector, operation, host));
    }
    out.push_str("];\n");

    Ok(out)
}

/// Render `crates/catalog/src/generated.rs`: one `mod` line and one `PROVIDERS` entry per provider
/// (C-104).
///
/// `providers` is the **whole** shipped set, in discovery order — which is sorted, and is the order
/// `catalog::providers()` publishes. This is the one file in the catalog crate that is a function of
/// every provider at once rather than of one, so [`crate::pipeline::plan_selected`] plans it only on
/// a full run, exactly as it plans `catalog.json` only on a full run. A `--provider` run would have
/// to render an index naming one provider and silently dropping the rest.
///
/// Until C-104 the file was hand-written for that reason, and the cost was structural rather than
/// cosmetic: every provider story appended two lines to it, so any two provider stories conflicted
/// and the fleet shipped one connector at a time. Generating it under the full-run rule is what makes
/// two implementors' write sets disjoint.
pub fn render_index(providers: &[String]) -> Result<String> {
    let idents = providers
        .iter()
        .map(|provider| module_ident(provider))
        .collect::<Result<Vec<_>>>()?;

    let mut out = format!(
        "//! The generated catalog data, one module per provider.\n\
         //!\n\
         //! Generated by {} — do not edit. Regenerate with `flux-connectors build`.\n\
         //!\n\
         //! **A whole-catalogue artifact**, and therefore written by a *full* build only: an index\n\
         //! rendered from `build --provider zendesk` would name one provider and silently drop the\n\
         //! rest. `web/public/catalog.json` follows the same rule for the same reason\n\
         //! (`docs/designs/catalog-json.md`). The corollary is the point of C-104 — a provider-scoped\n\
         //! build writes only that provider's own files, so provider work fans out instead of\n\
         //! serialising on this one file.\n\
         //!\n\
         //! `crates/catalog/tests/embedded_operations.rs` holds this list against `providers/`, and\n\
         //! `crates/connector-cli/tests/catalog_artifacts.rs` holds the whole tree to being a fixed\n\
         //! point of a build, so a stale index is loud rather than silent.\n\n",
        crate::seam::generator(),
    );

    for ident in &idents {
        out.push_str(&format!("pub(crate) mod {ident};\n"));
    }

    out.push_str("\nuse crate::Provider;\n\n");
    out.push_str(
        "/// Every provider, ordered by id — the order [`crate::providers`] publishes and the order the\n\
         /// catalog's flat listing walks.\n",
    );
    // `#[rustfmt::skip]` for the same reason every other generated item here carries it: the file is
    // inside `cargo fmt --all --check`'s reach, and one provider would let rustfmt collapse the
    // slice onto a single line while seventeen would not. Pinning the layout is cheaper than
    // rediscovering rustfmt's fixed point on every toolchain bump.
    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub(crate) static PROVIDERS: &[&Provider] = &[\n");
    for ident in &idents {
        out.push_str(&format!("    &{ident}::PROVIDER,\n"));
    }
    out.push_str("];\n");

    Ok(out)
}

/// Every lowercase Rust keyword that `mod <name>;` rejects.
///
/// **Checked against rustc rather than written from memory**, which is how `union` came to be absent:
/// it is a *weak* keyword and `mod union {}` compiles, so refusing or escaping it would be wrong. The
/// probe is `mod <candidate> {}` for each of the strict and reserved keyword lists; anything rustc
/// answers with "expected identifier, found (reserved) keyword" is here.
///
/// `Self` is the one keyword deliberately missing: it is uppercase, and a provider name carrying an
/// uppercase letter is already refused by the character rule below.
const RUST_KEYWORDS: &[&str] = &[
    "abstract", "as", "async", "await", "become", "box", "break", "const", "continue", "crate",
    "do", "dyn", "else", "enum", "extern", "false", "final", "fn", "for", "if", "impl", "in",
    "let", "loop", "macro", "match", "mod", "move", "mut", "override", "priv", "pub", "ref",
    "return", "self", "static", "struct", "super", "trait", "true", "try", "type", "typeof",
    "unsafe", "unsized", "use", "virtual", "where", "while", "yield",
];

/// The three keywords a raw identifier cannot rescue — `r#crate`, `r#self` and `r#super` are each
/// their own error. Verified the same way as [`RUST_KEYWORDS`].
const UNESCAPABLE_KEYWORDS: &[&str] = &["crate", "self", "super"];

/// The token that names `provider`'s module: the name itself, or `r#name` when it is a keyword.
///
/// `providers/` admits `-` in a file stem — correct everywhere else a provider name goes, since it
/// becomes the artifact file name and the op-id prefix — but `pub(crate) mod google-ads;` does not
/// parse. While the index was hand-written that compile error landed on the human writing the line;
/// generated, it would ship a `crates/catalog` that does not build from an input that looks entirely
/// ordinary.
///
/// **A keyword is escaped rather than refused, and that is a deliberate difference.** `box.com` is
/// squarely inside the charter, and `mod box;` is a compile error — but the fix costs nothing a user
/// can see: `mod r#box;` resolves to the same `generated/box.rs` the build already writes, and the
/// provider id stays `box` in every address, file name and catalogue row. Refusing would force
/// `providers/boxcom.toml` instead, which changes the op-id prefix and the installable artifact
/// name — a published address rewritten to work around a detail of one generated file, which
/// AGENTS.md's "an address, once published, is not reused" exists to prevent.
///
/// What is still refused is what cannot be expressed at all: a name outside the identifier
/// character set, and the three keywords no `r#` accepts.
fn module_ident(provider: &str) -> Result<String> {
    let mut chars = provider.chars();
    let valid = match chars.next() {
        Some(first) if first.is_ascii_lowercase() || first == '_' => {
            chars.all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')
        }
        _ => false,
    };
    if !valid || provider == "_" {
        bail!(
            "provider `{provider}` cannot name a Rust module, so `crates/catalog/src/generated.rs` \
             would not compile: rename it to lowercase ASCII letters, digits and `_` (a `-` is fine \
             everywhere else a provider name goes, but not here)"
        );
    }
    if UNESCAPABLE_KEYWORDS.contains(&provider) {
        bail!(
            "provider `{provider}` cannot name a Rust module: it is one of the three keywords a raw \
             identifier cannot rescue either, so neither `mod {provider};` nor `mod r#{provider};` \
             compiles. Rename the provider file"
        );
    }
    if RUST_KEYWORDS.contains(&provider) {
        // `mod r#box;` still resolves to `generated/box.rs`, so nothing outside this file moves.
        return Ok(format!("r#{provider}"));
    }
    Ok(provider.to_string())
}

/// The operation a rendering describes — **and the refusal that keeps the third member kind out of
/// every emitted artifact** (C-83).
///
/// Both catalogue backends resolve a rendering through this one function, the same way both share
/// [`credential_mechanisms`] and [`host_of`], so neither can be talked into publishing something the
/// other refuses.
///
/// # Why an event gets its own error
///
/// A rendering whose id names nothing is a bug. A rendering whose id names an **event or a channel
/// binding** is a specific bug with a specific name, and it is the one `AGENTS.md` calls out: *"the
/// tempting wrong output is an event dressed up as a pollable op."* Both kinds are emitted into no
/// Flux module at all — flux lifts `op` declarations only, while `channel` and `trigger` are Program
/// members an operator writes — so a rendering for one could only have been produced by an emitter
/// that decided to synthesise a poll loop, which is this repository writing a runtime.
///
/// Reported separately because the two have opposite fixes. "No such operation" says a name is
/// wrong; this says the name is *right* and the pipeline is wrong, and a generic message would send
/// the reader looking for a typo that is not there.
pub(crate) fn operation_for<'a>(connector: &'a Connector, id: &str) -> Result<&'a Operation> {
    if let Some(operation) = connector.operation(id) {
        return Ok(operation);
    }
    if let Some(kind) = inbound_member_kind(connector, id) {
        bail!(
            "connector `{}`: `{id}` is {kind}, not an operation, so there is no Flux to publish for \
             it. A binding declares and never installs: it reaches the manifest and the catalogue \
             and is emitted into no module, because flux lifts `op` declarations only. Emitting one \
             would be an event dressed up as a pollable op, which this pipeline refuses rather than \
             degrades to",
            connector.id
        );
    }
    bail!(
        "connector `{}` has no operation `{id}` to describe",
        connector.id
    );
}

/// Which inbound member kind `name` denotes, or `None` when it denotes neither.
///
/// The three member kinds share one namespace per service, so at most one of these matches.
fn inbound_member_kind(connector: &Connector, name: &str) -> Option<&'static str> {
    if connector.event(name).is_some() {
        return Some("an event");
    }
    if connector.channel(name).is_some() {
        return Some("a channel binding");
    }
    None
}

/// One `crate::Operation { … }` literal.
fn entry(connector: &Connector, operation: &Operation, host: &str) -> String {
    let mut out = String::from("    crate::Operation {\n");
    out.push_str(&format!("        id: {},\n", string(&operation.id)));
    out.push_str(&format!("        provider: {},\n", string(&connector.id)));
    out.push_str(&format!(
        "        description: {},\n",
        string(&operation.description)
    ));
    out.push_str(&format!("        risk: {},\n", risk(operation.risk)));
    out.push_str(&format!(
        "        idempotency: {},\n",
        idempotency(operation.idempotency)
    ));
    out.push_str(&format!(
        "        credentials: {},\n",
        credentials(connector, operation)
    ));
    out.push_str(&format!("        hosts: &[{}],\n", string(host)));
    // Escaped like every other literal here rather than interpolated raw. An id that reaches this
    // point is already constrained — the emitter refuses anything Flux cannot declare — but the
    // path is still a string literal, and one unescaped character in it is a generated file that
    // does not compile for a reason nobody can see in the provider TOML.
    out.push_str(&format!(
        "        flux: include_str!({}),\n",
        string(&format!(
            "../../ops/{}/{}.{}",
            connector.id,
            operation.id,
            crate::workspace::MODULE_EXT
        ))
    ));
    out.push_str("    },\n");
    out
}

/// The operation's credentials as alternatives (OR) of mechanisms (AND) — the IR's own shape,
/// carried across rather than flattened.
///
/// Flattening is the thing to avoid: babelforce's `accessId` + `accessToken` travel **together** on
/// one request and are an alternative to OAuth2, so a flat list of three names would tell a caller
/// that any one of them authenticates, which is false in both directions.
fn credentials(connector: &Connector, operation: &Operation) -> String {
    let mechanisms = credential_mechanisms(connector, operation);
    let rendered: Vec<String> = mechanisms
        .iter()
        .map(|mechanism| {
            let names: Vec<String> = mechanism.iter().map(|name| string(name)).collect();
            format!("&[{}]", names.join(", "))
        })
        .collect();
    format!("&[{}]", rendered.join(", "))
}

/// The operation's credentials as alternatives (OR) of mechanisms (AND), as plain data.
///
/// The one walk both catalogue backends share: this module quotes it into Rust literals and
/// [`crate::site`] serializes it into JSON, so the crate cannot ship a `catalog.json` that
/// disagrees with `crates/catalog` about what authenticates an operation.
///
/// Resolved through [`Connector::effective_auth`], never by reading `Operation::auth` directly: an
/// operation that declares nothing inherits the connector default, and one that declares an
/// explicit empty list inherits nothing.
pub(crate) fn credential_mechanisms<'a>(
    connector: &'a Connector,
    operation: &'a Operation,
) -> Vec<Vec<&'a str>> {
    connector
        .effective_auth(operation)
        .iter()
        .map(|mechanism| mechanism.iter().map(String::as_str).collect())
        .collect()
}

/// The host a call reaches, taken from the connector's base URL with its templating intact.
///
/// `https://{subdomain}.zendesk.com` yields `{subdomain}.zendesk.com`: the tenant is the operator's
/// to choose, and substituting a placeholder here would invent one. A caller reads this to decide
/// whether their egress policy admits the call, and a pattern is the honest answer to that.
///
/// C-10 replaces this with the manifest's real `http_hosts` allowlist, which is why the catalog
/// field is a slice: today every operation reaches exactly the connector's own host.
///
/// Shared with [`crate::site`] so that `catalog.json` and `crates/catalog` name the same host — two
/// answers to "which host does this reach?" would be one answer too many.
pub(crate) fn host_of(base_url: &str) -> Result<&str> {
    let after_scheme = base_url
        .split_once("://")
        .map_or(base_url, |(_scheme, rest)| rest);
    let host = after_scheme
        .split(['/', '?', '#'])
        .next()
        .unwrap_or(after_scheme);
    if host.is_empty() {
        bail!("base URL `{base_url}` names no host, so nothing can say which host it reaches");
    }
    Ok(host)
}

/// `connector_spec::Risk` as the catalog's own mirror of it.
///
/// An exhaustive match, deliberately: a variant added to the IR is a compile error here rather than
/// a silent gap in the catalog.
fn risk(risk: Risk) -> &'static str {
    match risk {
        Risk::Low => "crate::Risk::Low",
        Risk::Medium => "crate::Risk::Medium",
        Risk::High => "crate::Risk::High",
        Risk::Destructive => "crate::Risk::Destructive",
    }
}

/// `connector_spec::Idempotency` as the catalog's mirror. Exhaustive for the same reason.
fn idempotency(idempotency: Idempotency) -> &'static str {
    match idempotency {
        Idempotency::Idempotent => "crate::Idempotency::Idempotent",
        Idempotency::NonIdempotent => "crate::Idempotency::NonIdempotent",
        Idempotency::Conditional => "crate::Idempotency::Conditional",
    }
}

/// A Rust string literal for `value`.
///
/// Escaping rather than a raw literal: a raw string would have to pick a hash count no content
/// collides with, and a description carrying `"#` would silently end the literal early. Every
/// character that could close or continue the literal is escaped, and the remaining control
/// characters go out as `\u{…}` so the generated file stays plain ASCII-safe text a reviewer can
/// read in a diff.
fn string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for character in value.chars() {
        match character {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\0' => out.push_str("\\0"),
            other if other.is_control() => out.push_str(&format!("\\u{{{:x}}}", other as u32)),
            other => out.push(other),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use connector_spec::{
        AuthMethod, AuthRequirement, HttpMethod, ParamSet, Quirks, DEFAULT_SERVICE,
    };

    fn operation(id: &str) -> Operation {
        Operation {
            id: id.to_string(),
            service: DEFAULT_SERVICE.to_string(),
            method: HttpMethod::Get,
            path: "/v2/things".to_string(),
            description: "Do a thing".to_string(),
            risk: Risk::Low,
            idempotency: Idempotency::Idempotent,
            auth: None,
            params: ParamSet::default(),
            response_schema: None,
            quirks: Quirks::default(),
        }
    }

    fn connector() -> Connector {
        Connector {
            id: "acme".to_string(),
            authority: None,
            api_version: None,
            services: Vec::new(),
            vendor: "Acme".to_string(),
            base_url: "https://{tenant}.acme.example/api".to_string(),
            description: "Acme".to_string(),
            auth: vec![
                AuthMethod::header("acme.access_id", "X-Id", vec!["ACME_ID".to_string()]),
                AuthMethod::header(
                    "acme.access_token",
                    "X-Token",
                    vec!["ACME_TOKEN".to_string()],
                ),
            ],
            default_auth: vec![AuthRequirement::all([
                "acme.access_id",
                "acme.access_token",
            ])],
            operations: vec![operation("acme-thing-list")],
            events: Vec::new(),
            channels: Vec::new(),
            config: Vec::new(),
            verify: None,
            graphs: Vec::new(),
            provenance: Default::default(),
        }
    }

    fn renderings() -> Vec<OperationRendering> {
        vec![OperationRendering {
            id: "acme-thing-list".to_string(),
            source: "op acme-thing-list -> Any\n".to_string(),
        }]
    }

    #[test]
    fn rendering_is_deterministic() {
        let first = render(&connector(), &renderings()).unwrap();
        let second = render(&connector(), &renderings()).unwrap();
        assert_eq!(first, second);
    }

    /// The table embeds the file the same build wrote, at the path it wrote it to. A wrong relative
    /// path is a compile error in the catalog crate, but only once someone builds it.
    #[test]
    fn each_entry_embeds_its_own_rendering() {
        let rendered = render(&connector(), &renderings()).unwrap();
        assert!(
            rendered.contains("flux: include_str!(\"../../ops/acme/acme-thing-list.flux\"),"),
            "{rendered}"
        );
    }

    /// **The AND/OR shape survives.** Two credentials on one request must not read as two ways to
    /// authenticate.
    #[test]
    fn an_and_group_stays_one_mechanism() {
        let rendered = render(&connector(), &renderings()).unwrap();
        assert!(
            rendered.contains(r#"credentials: &[&["acme.access_id", "acme.access_token"]],"#),
            "{rendered}"
        );
    }

    /// An operation that declares an explicit empty list inherits nothing — the distinction
    /// `Connector::effective_auth` exists to preserve.
    #[test]
    fn an_explicitly_unauthenticated_operation_names_no_credential() {
        let mut connector = connector();
        connector.operations[0].auth = Some(vec![]);
        let rendered = render(&connector, &renderings()).unwrap();
        assert!(rendered.contains("credentials: &[],"), "{rendered}");
    }

    #[test]
    fn the_host_keeps_its_templating_and_drops_the_path() {
        assert_eq!(
            host_of("https://{subdomain}.zendesk.com").unwrap(),
            "{subdomain}.zendesk.com"
        );
        assert_eq!(
            host_of("https://example.freshdesk.com/api/v2").unwrap(),
            "example.freshdesk.com"
        );
        assert!(host_of("https://").is_err());
    }

    /// A description carrying a quote or a backslash must not break out of its literal — the one
    /// way generated Rust stops compiling for a reason nobody can see in the provider file.
    #[test]
    fn quotes_and_backslashes_are_escaped() {
        assert_eq!(string(r#"a "b" \ c"#), r#""a \"b\" \\ c""#);
        assert_eq!(string("a\nb"), r#""a\nb""#);
    }

    fn ids(names: &[&str]) -> Vec<String> {
        names.iter().map(|name| name.to_string()).collect()
    }

    /// The index names every provider it was given, in the order it was given them — which is
    /// discovery order, which is sorted. A `PROVIDERS` slice that did not match the `mod` lines
    /// would compile only by accident.
    #[test]
    fn the_index_names_every_provider_once() {
        let rendered = render_index(&ids(&["acme", "beacon"])).unwrap();
        for provider in ["acme", "beacon"] {
            assert_eq!(
                rendered
                    .matches(&format!("pub(crate) mod {provider};"))
                    .count(),
                1,
                "{rendered}"
            );
            assert_eq!(
                rendered.matches(&format!("&{provider}::PROVIDER,")).count(),
                1,
                "{rendered}"
            );
        }
        assert!(rendered.find("mod acme").unwrap() < rendered.find("mod beacon").unwrap());
    }

    #[test]
    fn the_index_is_deterministic() {
        let providers = ids(&["acme", "beacon", "cinder"]);
        assert_eq!(
            render_index(&providers).unwrap(),
            render_index(&providers).unwrap()
        );
    }

    /// A hyphen is legal in a provider file stem and illegal in a `mod` declaration, so the emitter
    /// refuses rather than writing a `crates/catalog` that does not compile.
    #[test]
    fn a_name_that_cannot_be_a_module_is_refused() {
        for name in ["google-ads", "2fa", "Acme", "acme.core", "", "_"] {
            let error = render_index(&ids(&[name]))
                .expect_err("a name that cannot be a module must not render");
            assert!(
                format!("{error:#}").contains("cannot name a Rust module"),
                "`{name}` was refused for the wrong reason: {error:#}"
            );
        }
        render_index(&ids(&["acme_core2"])).expect("an ordinary identifier renders");
    }

    /// **A keyword provider name is escaped, not refused.** `box.com` is inside the charter, and
    /// `mod box;` is a compile error while `mod r#box;` resolves to the same `generated/box.rs`.
    ///
    /// Every keyword is exercised rather than a sample: the list is the thing that can be wrong, and
    /// a spot check of three would not notice a missing entry.
    #[test]
    fn a_keyword_provider_name_is_escaped() {
        for keyword in RUST_KEYWORDS {
            if UNESCAPABLE_KEYWORDS.contains(keyword) {
                continue;
            }
            let rendered = render_index(&ids(&[keyword])).unwrap_or_else(|error| {
                panic!("`{keyword}` must render as a raw identifier, not fail: {error:#}")
            });
            assert!(
                rendered.contains(&format!("pub(crate) mod r#{keyword};")),
                "`{keyword}` was not escaped:\n{rendered}"
            );
            assert!(
                rendered.contains(&format!("&r#{keyword}::PROVIDER,")),
                "`{keyword}`'s PROVIDERS entry was not escaped:\n{rendered}"
            );
        }
    }

    /// `union` is a *weak* keyword: `mod union {}` compiles, so escaping it would be gratuitous.
    /// This pins the one name the keyword list must not grow.
    #[test]
    fn a_weak_keyword_is_left_alone() {
        let rendered = render_index(&ids(&["union"])).expect("`union` is a legal module name");
        assert!(
            rendered.contains("pub(crate) mod union;"),
            "`union` should not be escaped:\n{rendered}"
        );
    }

    /// The three a raw identifier cannot rescue are still refused, and say so specifically rather
    /// than rendering `r#crate` — which is its own compile error.
    #[test]
    fn a_keyword_that_cannot_be_raw_is_refused() {
        for keyword in UNESCAPABLE_KEYWORDS {
            let error = render_index(&ids(&[keyword]))
                .expect_err("a keyword no raw identifier accepts must be refused");
            let rendered = format!("{error:#}");
            assert!(
                rendered.contains("cannot name a Rust module") && rendered.contains(keyword),
                "`{keyword}` was refused for the wrong reason: {rendered}"
            );
        }
    }

    /// A rendering for an operation the connector does not declare would embed a file nothing
    /// regenerates. It is a failure, not an entry that gets skipped.
    #[test]
    fn a_rendering_without_an_operation_is_refused() {
        let stray = vec![OperationRendering {
            id: "acme-thing-vanished".to_string(),
            source: String::new(),
        }];
        render(&connector(), &stray).expect_err("a stray rendering must not be rendered");
    }
}
