# Generated by flux-connectors 0.14.0 — do not edit.
# Provider: algolia
# Regenerate with `flux-connectors build`.

op algolia-index-list -> Any
  description "List the indices in this Algolia application, with each index's record count and size. This is the call that discovers the index names every other operation here takes. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/message` in the response body."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://{app_id}.algolia.net"
  X_Algolia_Application_Id = "{app_id}"
  url = fmt("{base}/1/indexes")
  response = http.request(headers: { "X-Algolia-Application-Id": X_Algolia_Application_Id }, method: "GET", url)
  return response

op algolia-index-search(index_name: String, query: String, hits_per_page: Number, page: Number, filters: String) -> Any
  description "Search one index and return the matching records. Algolia ranks results by its own configured relevance, so the order is the index's, not this connector's; `hits_per_page` and `page` walk the result set, and `filters` narrows it with Algolia's filter syntax over the index's own attributes. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/message` in the response body."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://{app_id}.algolia.net"
  X_Algolia_Application_Id = "{app_id}"
  url = fmt("{base}/1/indexes/{index_name}?query={query}")
  sep = "&"
  when hits_per_page
    url = fmt("{url}{sep}hitsPerPage={hits_per_page}")
    sep = "&"
  when page
    url = fmt("{url}{sep}page={page}")
    sep = "&"
  when filters
    url = fmt("{url}{sep}filters={filters}")
  response = http.request(headers: { "X-Algolia-Application-Id": X_Algolia_Application_Id }, method: "GET", url)
  return response

op algolia-object-get(index_name: String, object_id: String) -> Any
  description "Read one record from an index by its object id. Returns the stored record as it is; its attributes are this index's own content model, so nothing here can name them. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/message` in the response body."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://{app_id}.algolia.net"
  X_Algolia_Application_Id = "{app_id}"
  url = fmt("{base}/1/indexes/{index_name}/{object_id}")
  response = http.request(headers: { "X-Algolia-Application-Id": X_Algolia_Application_Id }, method: "GET", url)
  return response

op algolia-object-save(index_name: String, object_id: String, body: Any) -> Any
  description "Save one record at a known object id, creating it if it does not exist and REPLACING it wholesale if it does. This is not a partial update: attributes absent from the body are removed from the stored record. Algolia applies the write asynchronously, so the response's `taskID` is an acknowledgement of acceptance rather than of visibility, and a search run immediately afterwards may still return the old record. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/message` in the response body."
  risk "high"
  idempotency "conditional"
  effects ["network"]
  expose true

  base = "https://{app_id}.algolia.net"
  X_Algolia_Application_Id = "{app_id}"
  url = fmt("{base}/1/indexes/{index_name}/{object_id}")
  content_type = "application/json"
  payload = parse(body, as: "json")
  response = http.request(body: payload, headers: { "X-Algolia-Application-Id": X_Algolia_Application_Id, "content-type": content_type }, method: "PUT", url)
  return response

op algolia-object-delete(index_name: String, object_id: String) -> Any
  description "Delete one record from an index by its object id. The record is gone with no undo route in the API — restoring it means re-indexing it from the source of truth. Algolia applies the delete asynchronously, so the `taskID` acknowledges acceptance rather than visibility. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/message` in the response body."
  risk "destructive"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://{app_id}.algolia.net"
  X_Algolia_Application_Id = "{app_id}"
  url = fmt("{base}/1/indexes/{index_name}/{object_id}")
  response = http.request(headers: { "X-Algolia-Application-Id": X_Algolia_Application_Id }, method: "DELETE", url)
  return response
