# Generated by flux-connectors 0.15.0 — do not edit.
# Provider: asterisk
# Regenerate with `flux-connectors build`.

op asterisk-ari-applications-list -> Any
  description "List all applications."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://{host}:8089/ari"
  url = fmt("{base}/applications")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-asterisk-ping -> Any
  description "Response pong message."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://{host}:8089/ari"
  url = fmt("{base}/asterisk/ping")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-bridges-list -> Any
  description "List all active bridges in Asterisk."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://{host}:8089/ari"
  url = fmt("{base}/bridges")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-bridges-create(type: String, bridgeId: String, name: String, variables: Any) -> Any
  description "Create a new bridge."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://{host}:8089/ari"
  url = fmt("{base}/bridges")
  sep = "?"
  when type
    url = fmt("{url}{sep}type={type}")
    sep = "&"
  when bridgeId
    url = fmt("{url}{sep}bridgeId={bridgeId}")
    sep = "&"
  when name
    url = fmt("{url}{sep}name={name}")
  content_type = "application/json"
  payload = { variables }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op asterisk-ari-bridges-destroy(bridgeId: String) -> Any
  description "Shut down a bridge."
  risk "destructive"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://{host}:8089/ari"
  url = fmt("{base}/bridges/{bridgeId}")
  response = http.request(method: "DELETE", url)
  return response

op asterisk-ari-channels-list -> Any
  description "List all active channels in Asterisk."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-channels-originate(endpoint: String, extension: String, context: String, priority: Number, label: String, app: String, appArgs: String, callerId: String, timeout: Number, channelId: String, otherChannelId: String, originator: String, formats: String, variables: Any) -> Any
  description "Create a new channel (originate)."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels?endpoint={endpoint}")
  sep = "&"
  when extension
    url = fmt("{url}{sep}extension={extension}")
    sep = "&"
  when context
    url = fmt("{url}{sep}context={context}")
    sep = "&"
  when priority
    url = fmt("{url}{sep}priority={priority}")
    sep = "&"
  when label
    url = fmt("{url}{sep}label={label}")
    sep = "&"
  when app
    url = fmt("{url}{sep}app={app}")
    sep = "&"
  when appArgs
    url = fmt("{url}{sep}appArgs={appArgs}")
    sep = "&"
  when callerId
    url = fmt("{url}{sep}callerId={callerId}")
    sep = "&"
  when $timeout
    url = fmt("{url}{sep}timeout={timeout}")
    sep = "&"
  when channelId
    url = fmt("{url}{sep}channelId={channelId}")
    sep = "&"
  when otherChannelId
    url = fmt("{url}{sep}otherChannelId={otherChannelId}")
    sep = "&"
  when originator
    url = fmt("{url}{sep}originator={originator}")
    sep = "&"
  when formats
    url = fmt("{url}{sep}formats={formats}")
  content_type = "application/json"
  payload = { variables }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op asterisk-ari-channels-hangup(channelId: String, reason_code: String, reason: String) -> Any
  description "Delete (i.e. hangup) a channel."
  risk "destructive"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}")
  sep = "?"
  when reason_code
    url = fmt("{url}{sep}reason_code={reason_code}")
    sep = "&"
  when reason
    url = fmt("{url}{sep}reason={reason}")
  response = http.request(method: "DELETE", url)
  return response

op asterisk-ari-device-states-list -> Any
  description "List all ARI controlled device states."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://{host}:8089/ari"
  url = fmt("{base}/deviceStates")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-endpoints-list -> Any
  description "List all endpoints."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://{host}:8089/ari"
  url = fmt("{base}/endpoints")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-mailboxes-list -> Any
  description "List all mailboxes."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://{host}:8089/ari"
  url = fmt("{base}/mailboxes")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-playbacks-get(playbackId: String) -> Any
  description "Get a playback's details."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://{host}:8089/ari"
  url = fmt("{base}/playbacks/{playbackId}")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-playbacks-stop(playbackId: String) -> Any
  description "Stop a playback."
  risk "destructive"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://{host}:8089/ari"
  url = fmt("{base}/playbacks/{playbackId}")
  response = http.request(method: "DELETE", url)
  return response

op asterisk-ari-recordings-list-stored -> Any
  description "List recordings that are complete."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://{host}:8089/ari"
  url = fmt("{base}/recordings/stored")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-sounds-list(lang: String, format: String) -> Any
  description "List all sounds."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://{host}:8089/ari"
  url = fmt("{base}/sounds")
  sep = "?"
  when lang
    url = fmt("{url}{sep}lang={lang}")
    sep = "&"
  when format
    url = fmt("{url}{sep}format={format}")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-applications-get(applicationName: String) -> Any
  description "Get details of an application."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/applications/{applicationName}")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-applications-filter(applicationName: String, body: Any) -> Any
  description "Filter application events types."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/applications/{applicationName}/eventFilter")
  content_type = "application/json"
  payload = parse(body, as: "json")
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "PUT", url)
  return response

op asterisk-ari-applications-subscribe(applicationName: String, eventSource: List<String>) -> Any
  description "Subscribe an application to a event source."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/applications/{applicationName}/subscription?eventSource={eventSource}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-applications-unsubscribe(applicationName: String, eventSource: List<String>) -> Any
  description "Unsubscribe an application from an event source."
  risk "destructive"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/applications/{applicationName}/subscription?eventSource={eventSource}")
  response = http.request(method: "DELETE", url)
  return response

op asterisk-ari-asterisk-get-object(configClass: String, objectType: String, id: String) -> Any
  description "Retrieve a dynamic configuration object."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/asterisk/config/dynamic/{configClass}/{objectType}/{id}")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-asterisk-update-object(configClass: String, objectType: String, id: String, fields: Any) -> Any
  description "Create or update a dynamic configuration object."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/asterisk/config/dynamic/{configClass}/{objectType}/{id}")
  content_type = "application/json"
  payload = { fields }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "PUT", url)
  return response

op asterisk-ari-asterisk-delete-object(configClass: String, objectType: String, id: String) -> Any
  description "Delete a dynamic configuration object."
  risk "destructive"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/asterisk/config/dynamic/{configClass}/{objectType}/{id}")
  response = http.request(method: "DELETE", url)
  return response

op asterisk-ari-asterisk-get-info(only: List<String>) -> Any
  description "Gets Asterisk system information."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/asterisk/info")
  sep = "?"
  when only
    url = fmt("{url}{sep}only={only}")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-asterisk-list-log-channels -> Any
  description "Gets Asterisk log channel information."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/asterisk/logging")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-asterisk-add-log(logChannelName: String, configuration: String) -> Any
  description "Adds a log channel."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/asterisk/logging/{logChannelName}?configuration={configuration}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-asterisk-delete-log(logChannelName: String) -> Any
  description "Deletes a log channel."
  risk "destructive"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/asterisk/logging/{logChannelName}")
  response = http.request(method: "DELETE", url)
  return response

op asterisk-ari-asterisk-rotate-log(logChannelName: String) -> Any
  description "Rotates a log channel."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/asterisk/logging/{logChannelName}/rotate")
  response = http.request(method: "PUT", url)
  return response

op asterisk-ari-asterisk-list-modules -> Any
  description "List Asterisk modules."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/asterisk/modules")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-asterisk-get-module(moduleName: String) -> Any
  description "Get Asterisk module information."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/asterisk/modules/{moduleName}")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-asterisk-load-module(moduleName: String) -> Any
  description "Load an Asterisk module."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/asterisk/modules/{moduleName}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-asterisk-reload-module(moduleName: String) -> Any
  description "Reload an Asterisk module."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/asterisk/modules/{moduleName}")
  response = http.request(method: "PUT", url)
  return response

op asterisk-ari-asterisk-unload-module(moduleName: String) -> Any
  description "Unload an Asterisk module."
  risk "destructive"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/asterisk/modules/{moduleName}")
  response = http.request(method: "DELETE", url)
  return response

op asterisk-ari-asterisk-get-global-var(variable: String) -> Any
  description "Get the value of a global variable."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/asterisk/variable?variable={variable}")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-asterisk-set-global-var(variable: String, value: String) -> Any
  description "Set the value of a global variable."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/asterisk/variable?variable={variable}")
  sep = "&"
  when value
    url = fmt("{url}{sep}value={value}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-bridges-get(bridgeId: String) -> Any
  description "Get bridge details."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/bridges/{bridgeId}")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-bridges-create-with-id(bridgeId: String, type: String, name: String, variables: Any) -> Any
  description "Create a new bridge."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/bridges/{bridgeId}")
  sep = "?"
  when type
    url = fmt("{url}{sep}type={type}")
    sep = "&"
  when name
    url = fmt("{url}{sep}name={name}")
  content_type = "application/json"
  payload = { variables }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op asterisk-ari-bridges-add-channel(bridgeId: String, channel: List<String>, role: String, absorbDTMF: Bool, mute: Bool, inhibitConnectedLineUpdates: Bool) -> Any
  description "Add a channel to a bridge."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/bridges/{bridgeId}/addChannel?channel={channel}")
  sep = "&"
  when role
    url = fmt("{url}{sep}role={role}")
    sep = "&"
  when absorbDTMF
    url = fmt("{url}{sep}absorbDTMF={absorbDTMF}")
    sep = "&"
  when mute
    url = fmt("{url}{sep}mute={mute}")
    sep = "&"
  when inhibitConnectedLineUpdates
    url = fmt("{url}{sep}inhibitConnectedLineUpdates={inhibitConnectedLineUpdates}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-bridges-start-moh(bridgeId: String, mohClass: String) -> Any
  description "Play music on hold to a bridge or change the MOH class that is playing."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/bridges/{bridgeId}/moh")
  sep = "?"
  when mohClass
    url = fmt("{url}{sep}mohClass={mohClass}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-bridges-stop-moh(bridgeId: String) -> Any
  description "Stop playing music on hold to a bridge."
  risk "destructive"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/bridges/{bridgeId}/moh")
  response = http.request(method: "DELETE", url)
  return response

op asterisk-ari-bridges-play(bridgeId: String, media: List<String>, announcer_format: String, lang: String, offsetms: Number, skipms: Number, playbackId: String) -> Any
  description "Start playback of media on a bridge."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/bridges/{bridgeId}/play?media={media}")
  sep = "&"
  when announcer_format
    url = fmt("{url}{sep}announcer_format={announcer_format}")
    sep = "&"
  when lang
    url = fmt("{url}{sep}lang={lang}")
    sep = "&"
  when offsetms
    url = fmt("{url}{sep}offsetms={offsetms}")
    sep = "&"
  when skipms
    url = fmt("{url}{sep}skipms={skipms}")
    sep = "&"
  when playbackId
    url = fmt("{url}{sep}playbackId={playbackId}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-bridges-play-with-id(bridgeId: String, playbackId: String, media: List<String>, announcer_format: String, lang: String, offsetms: Number, skipms: Number) -> Any
  description "Start playback of media on a bridge."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/bridges/{bridgeId}/play/{playbackId}?media={media}")
  sep = "&"
  when announcer_format
    url = fmt("{url}{sep}announcer_format={announcer_format}")
    sep = "&"
  when lang
    url = fmt("{url}{sep}lang={lang}")
    sep = "&"
  when offsetms
    url = fmt("{url}{sep}offsetms={offsetms}")
    sep = "&"
  when skipms
    url = fmt("{url}{sep}skipms={skipms}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-bridges-record(bridgeId: String, name: String, format: String, recorder_format: String, maxDurationSeconds: Number, maxSilenceSeconds: Number, ifExists: String, beep: Bool, terminateOn: String) -> Any
  description "Start a recording."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/bridges/{bridgeId}/record?name={name}&format={format}")
  sep = "&"
  when recorder_format
    url = fmt("{url}{sep}recorder_format={recorder_format}")
    sep = "&"
  when maxDurationSeconds
    url = fmt("{url}{sep}maxDurationSeconds={maxDurationSeconds}")
    sep = "&"
  when maxSilenceSeconds
    url = fmt("{url}{sep}maxSilenceSeconds={maxSilenceSeconds}")
    sep = "&"
  when ifExists
    url = fmt("{url}{sep}ifExists={ifExists}")
    sep = "&"
  when beep
    url = fmt("{url}{sep}beep={beep}")
    sep = "&"
  when terminateOn
    url = fmt("{url}{sep}terminateOn={terminateOn}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-bridges-remove-channel(bridgeId: String, channel: List<String>) -> Any
  description "Remove a channel from a bridge."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/bridges/{bridgeId}/removeChannel?channel={channel}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-bridges-get-bridge-var(bridgeId: String, variable: String) -> Any
  description "Get the value of a bridge variable or function."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/bridges/{bridgeId}/variable?variable={variable}")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-bridges-set-bridge-var(bridgeId: String, variable: String, value: String, report_events: Bool) -> Any
  description "Set the value of a bridge variable or function."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/bridges/{bridgeId}/variable?variable={variable}")
  sep = "&"
  when value
    url = fmt("{url}{sep}value={value}")
    sep = "&"
  when report_events
    url = fmt("{url}{sep}report_events={report_events}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-bridges-get-bridge-vars(bridgeId: String, variables: List<String>) -> Any
  description "Get the value of multiple bridge variables or functions."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/bridges/{bridgeId}/variables?variables={variables}")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-bridges-set-bridge-vars(bridgeId: String, variables: Any) -> Any
  description "Set the values of multiple bridge variables or functions."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/bridges/{bridgeId}/variables")
  content_type = "application/json"
  payload = { variables }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op asterisk-ari-bridges-clear-video-source(bridgeId: String) -> Any
  description "Removes any explicit video source in a multi-party mixing bridge. This operation has no effect on bridges with two or fewer participants. When no explicit video source is set, talk detection will be used to determine the active video stream."
  risk "destructive"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/bridges/{bridgeId}/videoSource")
  response = http.request(method: "DELETE", url)
  return response

op asterisk-ari-bridges-set-video-source(bridgeId: String, channelId: String) -> Any
  description "Set a channel as the video source in a multi-party mixing bridge. This operation has no effect on bridges with two or fewer participants."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/bridges/{bridgeId}/videoSource/{channelId}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-channels-create(endpoint: String, app: String, appArgs: String, channelId: String, otherChannelId: String, originator: String, formats: String, variables: Any) -> Any
  description "Create channel."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/create?endpoint={endpoint}&app={app}")
  sep = "&"
  when appArgs
    url = fmt("{url}{sep}appArgs={appArgs}")
    sep = "&"
  when channelId
    url = fmt("{url}{sep}channelId={channelId}")
    sep = "&"
  when otherChannelId
    url = fmt("{url}{sep}otherChannelId={otherChannelId}")
    sep = "&"
  when originator
    url = fmt("{url}{sep}originator={originator}")
    sep = "&"
  when formats
    url = fmt("{url}{sep}formats={formats}")
  content_type = "application/json"
  payload = { variables }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op asterisk-ari-channels-external-media(channelId: String, app: String, external_host: String, encapsulation: String, transport: String, connection_type: String, format: String, direction: String, data: String, transport_data: String, variables: Any) -> Any
  description "Start an External Media session."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/externalMedia?app={app}&format={format}")
  sep = "&"
  when channelId
    url = fmt("{url}{sep}channelId={channelId}")
    sep = "&"
  when external_host
    url = fmt("{url}{sep}external_host={external_host}")
    sep = "&"
  when encapsulation
    url = fmt("{url}{sep}encapsulation={encapsulation}")
    sep = "&"
  when transport
    url = fmt("{url}{sep}transport={transport}")
    sep = "&"
  when connection_type
    url = fmt("{url}{sep}connection_type={connection_type}")
    sep = "&"
  when direction
    url = fmt("{url}{sep}direction={direction}")
    sep = "&"
  when data
    url = fmt("{url}{sep}data={data}")
    sep = "&"
  when transport_data
    url = fmt("{url}{sep}transport_data={transport_data}")
  content_type = "application/json"
  payload = { variables }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op asterisk-ari-channels-get(channelId: String) -> Any
  description "Channel details."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-channels-originate-with-id(channelId: String, endpoint: String, extension: String, context: String, priority: Number, label: String, app: String, appArgs: String, callerId: String, timeout: Number, otherChannelId: String, originator: String, formats: String, variables: Any) -> Any
  description "Create a new channel (originate with id)."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}?endpoint={endpoint}")
  sep = "&"
  when extension
    url = fmt("{url}{sep}extension={extension}")
    sep = "&"
  when context
    url = fmt("{url}{sep}context={context}")
    sep = "&"
  when priority
    url = fmt("{url}{sep}priority={priority}")
    sep = "&"
  when label
    url = fmt("{url}{sep}label={label}")
    sep = "&"
  when app
    url = fmt("{url}{sep}app={app}")
    sep = "&"
  when appArgs
    url = fmt("{url}{sep}appArgs={appArgs}")
    sep = "&"
  when callerId
    url = fmt("{url}{sep}callerId={callerId}")
    sep = "&"
  when $timeout
    url = fmt("{url}{sep}timeout={timeout}")
    sep = "&"
  when otherChannelId
    url = fmt("{url}{sep}otherChannelId={otherChannelId}")
    sep = "&"
  when originator
    url = fmt("{url}{sep}originator={originator}")
    sep = "&"
  when formats
    url = fmt("{url}{sep}formats={formats}")
  content_type = "application/json"
  payload = { variables }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op asterisk-ari-channels-answer(channelId: String) -> Any
  description "Answer a channel."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/answer")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-channels-continue-in-dialplan(channelId: String, context: String, extension: String, priority: Number, label: String) -> Any
  description "Exit application; continue execution in the dialplan."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/continue")
  sep = "?"
  when context
    url = fmt("{url}{sep}context={context}")
    sep = "&"
  when extension
    url = fmt("{url}{sep}extension={extension}")
    sep = "&"
  when priority
    url = fmt("{url}{sep}priority={priority}")
    sep = "&"
  when label
    url = fmt("{url}{sep}label={label}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-channels-dial(channelId: String, caller: String, timeout: Number) -> Any
  description "Dial a created channel."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/dial")
  sep = "?"
  when caller
    url = fmt("{url}{sep}caller={caller}")
    sep = "&"
  when $timeout
    url = fmt("{url}{sep}timeout={timeout}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-channels-send-dtmf(channelId: String, dtmf: String, before: Number, between: Number, duration: Number, after: Number) -> Any
  description "Send provided DTMF to a given channel."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/dtmf")
  sep = "?"
  when dtmf
    url = fmt("{url}{sep}dtmf={dtmf}")
    sep = "&"
  when before
    url = fmt("{url}{sep}before={before}")
    sep = "&"
  when between
    url = fmt("{url}{sep}between={between}")
    sep = "&"
  when duration
    url = fmt("{url}{sep}duration={duration}")
    sep = "&"
  when after
    url = fmt("{url}{sep}after={after}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-channels-hold(channelId: String) -> Any
  description "Hold a channel."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/hold")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-channels-unhold(channelId: String) -> Any
  description "Remove a channel from hold."
  risk "destructive"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/hold")
  response = http.request(method: "DELETE", url)
  return response

op asterisk-ari-channels-start-moh(channelId: String, mohClass: String) -> Any
  description "Play music on hold to a channel."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/moh")
  sep = "?"
  when mohClass
    url = fmt("{url}{sep}mohClass={mohClass}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-channels-stop-moh(channelId: String) -> Any
  description "Stop playing music on hold to a channel."
  risk "destructive"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/moh")
  response = http.request(method: "DELETE", url)
  return response

op asterisk-ari-channels-move(channelId: String, app: String, appArgs: String) -> Any
  description "Move the channel from one Stasis application to another."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/move?app={app}")
  sep = "&"
  when appArgs
    url = fmt("{url}{sep}appArgs={appArgs}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-channels-mute(channelId: String, direction: String) -> Any
  description "Mute a channel."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/mute")
  sep = "?"
  when direction
    url = fmt("{url}{sep}direction={direction}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-channels-unmute(channelId: String, direction: String) -> Any
  description "Unmute a channel."
  risk "destructive"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/mute")
  sep = "?"
  when direction
    url = fmt("{url}{sep}direction={direction}")
  response = http.request(method: "DELETE", url)
  return response

op asterisk-ari-channels-play(channelId: String, media: List<String>, lang: String, offsetms: Number, skipms: Number, playbackId: String) -> Any
  description "Start playback of media."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/play?media={media}")
  sep = "&"
  when lang
    url = fmt("{url}{sep}lang={lang}")
    sep = "&"
  when offsetms
    url = fmt("{url}{sep}offsetms={offsetms}")
    sep = "&"
  when skipms
    url = fmt("{url}{sep}skipms={skipms}")
    sep = "&"
  when playbackId
    url = fmt("{url}{sep}playbackId={playbackId}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-channels-play-with-id(channelId: String, playbackId: String, media: List<String>, lang: String, offsetms: Number, skipms: Number) -> Any
  description "Start playback of media and specify the playbackId."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/play/{playbackId}?media={media}")
  sep = "&"
  when lang
    url = fmt("{url}{sep}lang={lang}")
    sep = "&"
  when offsetms
    url = fmt("{url}{sep}offsetms={offsetms}")
    sep = "&"
  when skipms
    url = fmt("{url}{sep}skipms={skipms}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-channels-progress(channelId: String) -> Any
  description "Indicate progress on a channel."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/progress")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-channels-record(channelId: String, name: String, format: String, maxDurationSeconds: Number, maxSilenceSeconds: Number, ifExists: String, beep: Bool, terminateOn: String) -> Any
  description "Start a recording."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/record?name={name}&format={format}")
  sep = "&"
  when maxDurationSeconds
    url = fmt("{url}{sep}maxDurationSeconds={maxDurationSeconds}")
    sep = "&"
  when maxSilenceSeconds
    url = fmt("{url}{sep}maxSilenceSeconds={maxSilenceSeconds}")
    sep = "&"
  when ifExists
    url = fmt("{url}{sep}ifExists={ifExists}")
    sep = "&"
  when beep
    url = fmt("{url}{sep}beep={beep}")
    sep = "&"
  when terminateOn
    url = fmt("{url}{sep}terminateOn={terminateOn}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-channels-redirect(channelId: String, endpoint: String) -> Any
  description "Redirect the channel to a different location."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/redirect?endpoint={endpoint}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-channels-ring(channelId: String) -> Any
  description "Indicate ringing to a channel."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/ring")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-channels-ring-stop(channelId: String) -> Any
  description "Stop ringing indication on a channel if locally generated."
  risk "destructive"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/ring")
  response = http.request(method: "DELETE", url)
  return response

op asterisk-ari-channels-rtpstatistics(channelId: String) -> Any
  description "RTP stats on a channel."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/rtp_statistics")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-channels-start-silence(channelId: String) -> Any
  description "Play silence to a channel."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/silence")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-channels-stop-silence(channelId: String) -> Any
  description "Stop playing silence to a channel."
  risk "destructive"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/silence")
  response = http.request(method: "DELETE", url)
  return response

op asterisk-ari-channels-snoop-channel(channelId: String, spy: String, whisper: String, app: String, appArgs: String, snoopId: String) -> Any
  description "Start snooping."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/snoop?app={app}")
  sep = "&"
  when spy
    url = fmt("{url}{sep}spy={spy}")
    sep = "&"
  when whisper
    url = fmt("{url}{sep}whisper={whisper}")
    sep = "&"
  when appArgs
    url = fmt("{url}{sep}appArgs={appArgs}")
    sep = "&"
  when snoopId
    url = fmt("{url}{sep}snoopId={snoopId}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-channels-snoop-channel-with-id(channelId: String, snoopId: String, spy: String, whisper: String, app: String, appArgs: String) -> Any
  description "Start snooping."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/snoop/{snoopId}?app={app}")
  sep = "&"
  when spy
    url = fmt("{url}{sep}spy={spy}")
    sep = "&"
  when whisper
    url = fmt("{url}{sep}whisper={whisper}")
    sep = "&"
  when appArgs
    url = fmt("{url}{sep}appArgs={appArgs}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-channels-transfer_progress(channelId: String, states: String) -> Any
  description "Inform the channel about the progress of the attended/blind transfer."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/transfer_progress?states={states}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-channels-get-channel-var(channelId: String, variable: String) -> Any
  description "Get the value of a channel variable or function."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/variable?variable={variable}")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-channels-set-channel-var(channelId: String, variable: String, value: String, report_events: Bool) -> Any
  description "Set the value of a channel variable or function."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/variable?variable={variable}")
  sep = "&"
  when value
    url = fmt("{url}{sep}value={value}")
    sep = "&"
  when report_events
    url = fmt("{url}{sep}report_events={report_events}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-channels-get-channel-vars(channelId: String, variables: List<String>) -> Any
  description "Get the value of multiple channel variables or functions."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/variables?variables={variables}")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-channels-set-channel-vars(channelId: String, variables: Any) -> Any
  description "Set the values of multiple channel variables or functions."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/channels/{channelId}/variables")
  content_type = "application/json"
  payload = { variables }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op asterisk-ari-device-states-get(deviceName: String) -> Any
  description "Retrieve the current state of a device."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/deviceStates/{deviceName}")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-device-states-update(deviceName: String, deviceState: String) -> Any
  description "Change the state of a device controlled by ARI. (Note - implicitly creates the device state)."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/deviceStates/{deviceName}?deviceState={deviceState}")
  response = http.request(method: "PUT", url)
  return response

op asterisk-ari-device-states-delete(deviceName: String) -> Any
  description "Destroy a device-state controlled by ARI."
  risk "destructive"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/deviceStates/{deviceName}")
  response = http.request(method: "DELETE", url)
  return response

op asterisk-ari-endpoints-refer(to: String, from: String, refer_to: String, to_self: Bool, variables: Any) -> Any
  description "Refer an endpoint or technology URI to some technology URI or endpoint."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/endpoints/refer?to={to}&from={from}&refer_to={refer_to}")
  sep = "&"
  when to_self
    url = fmt("{url}{sep}to_self={to_self}")
  content_type = "application/json"
  payload = { variables }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op asterisk-ari-endpoints-send-message(to: String, from: String, body: String, variables: Any) -> Any
  description "Send a message to some technology URI or endpoint."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/endpoints/sendMessage?to={to}&from={from}")
  sep = "&"
  when body
    url = fmt("{url}{sep}body={body}")
  content_type = "application/json"
  payload = { variables }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "PUT", url)
  return response

op asterisk-ari-endpoints-list-by-tech(tech: String) -> Any
  description "List available endoints for a given endpoint technology."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/endpoints/{tech}")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-endpoints-get(tech: String, resource: String) -> Any
  description "Details for an endpoint."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/endpoints/{tech}/{resource}")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-endpoints-refer-to-endpoint(tech: String, resource: String, from: String, refer_to: String, to_self: Bool, variables: Any) -> Any
  description "Refer an endpoint or technology URI to some technology URI or endpoint."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/endpoints/{tech}/{resource}/refer?from={from}&refer_to={refer_to}")
  sep = "&"
  when to_self
    url = fmt("{url}{sep}to_self={to_self}")
  content_type = "application/json"
  payload = { variables }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op asterisk-ari-endpoints-send-message-to-endpoint(tech: String, resource: String, from: String, body: String, variables: Any) -> Any
  description "Send a message to some endpoint in a technology."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/endpoints/{tech}/{resource}/sendMessage?from={from}")
  sep = "&"
  when body
    url = fmt("{url}{sep}body={body}")
  content_type = "application/json"
  payload = { variables }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "PUT", url)
  return response

op asterisk-ari-events-claim-channel(channelId: String, application: String) -> Any
  description "Claim a broadcast channel for this application."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/events/claim?channelId={channelId}&application={application}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-events-user-event(eventName: String, application: String, source: List<String>, variables: Any) -> Any
  description "Generate a user event."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/events/user/{eventName}?application={application}")
  sep = "&"
  when source
    url = fmt("{url}{sep}source={source}")
  content_type = "application/json"
  payload = { variables }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op asterisk-ari-mailboxes-get(mailboxName: String) -> Any
  description "Retrieve the current state of a mailbox."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/mailboxes/{mailboxName}")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-mailboxes-update(mailboxName: String, oldMessages: Number, newMessages: Number) -> Any
  description "Change the state of a mailbox. (Note - implicitly creates the mailbox)."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/mailboxes/{mailboxName}?oldMessages={oldMessages}&newMessages={newMessages}")
  response = http.request(method: "PUT", url)
  return response

op asterisk-ari-mailboxes-delete(mailboxName: String) -> Any
  description "Destroy a mailbox."
  risk "destructive"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/mailboxes/{mailboxName}")
  response = http.request(method: "DELETE", url)
  return response

op asterisk-ari-playbacks-control(playbackId: String, operation: String) -> Any
  description "Control a playback."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/playbacks/{playbackId}/control?operation={operation}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-recordings-get-live(recordingName: String) -> Any
  description "List live recordings."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/recordings/live/{recordingName}")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-recordings-cancel(recordingName: String) -> Any
  description "Stop a live recording and discard it."
  risk "destructive"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/recordings/live/{recordingName}")
  response = http.request(method: "DELETE", url)
  return response

op asterisk-ari-recordings-mute(recordingName: String) -> Any
  description "Mute a live recording."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/recordings/live/{recordingName}/mute")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-recordings-unmute(recordingName: String) -> Any
  description "Unmute a live recording."
  risk "destructive"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/recordings/live/{recordingName}/mute")
  response = http.request(method: "DELETE", url)
  return response

op asterisk-ari-recordings-pause(recordingName: String) -> Any
  description "Pause a live recording."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/recordings/live/{recordingName}/pause")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-recordings-unpause(recordingName: String) -> Any
  description "Unpause a live recording."
  risk "destructive"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/recordings/live/{recordingName}/pause")
  response = http.request(method: "DELETE", url)
  return response

op asterisk-ari-recordings-stop(recordingName: String) -> Any
  description "Stop a live recording and store it."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/recordings/live/{recordingName}/stop")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-recordings-get-stored(recordingName: String) -> Any
  description "Get a stored recording's details."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/recordings/stored/{recordingName}")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-recordings-delete-stored(recordingName: String) -> Any
  description "Delete a stored recording."
  risk "destructive"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/recordings/stored/{recordingName}")
  response = http.request(method: "DELETE", url)
  return response

op asterisk-ari-recordings-copy-stored(recordingName: String, destinationRecordingName: String) -> Any
  description "Copy a stored recording."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/recordings/stored/{recordingName}/copy?destinationRecordingName={destinationRecordingName}")
  response = http.request(method: "POST", url)
  return response

op asterisk-ari-recordings-get-stored-file(recordingName: String) -> Any
  description "Get the file associated with the stored recording."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/recordings/stored/{recordingName}/file")
  response = http.request(method: "GET", url)
  return response

op asterisk-ari-sounds-get(soundId: String) -> Any
  description "Get a sound's details."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose false

  base = "https://{host}:8089/ari"
  url = fmt("{base}/sounds/{soundId}")
  response = http.request(method: "GET", url)
  return response
