# Generated by flux-connectors 0.8.0 — do not edit.
# Provider: babelforce
# Service: auth
# Regenerate with `flux-connectors build`.

op babelforce-authorize(response_type: String, client_id: String, redirect_uri: String, scope: String, state: String, code_challenge: String, code_challenge_method: String) -> Any
  description "OAuth 2.0 authorization endpoint"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/oauth/authorize?response_type={response_type}&client_id={client_id}&redirect_uri={redirect_uri}&scope={scope}")
  sep = "&"
  when state
    url = fmt("{url}{sep}state={state}")
    sep = "&"
  when code_challenge
    url = fmt("{url}{sep}code_challenge={code_challenge}")
    sep = "&"
  when code_challenge_method
    url = fmt("{url}{sep}code_challenge_method={code_challenge_method}")
  response = http.request(method: "GET", url)
  return response

op babelforce-revoke(client_id: String, client_secret: String, token: String, token_type_hint: String) -> Any
  description "OAuth 2.0 token revocation (RFC 7009)"
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/oauth/revoke")
  content_type = "application/x-www-form-urlencoded"
  payload = fmt("token={token}")
  when client_id
    payload = fmt("{payload}&client_id={client_id}")
  when client_secret
    payload = fmt("{payload}&client_secret={client_secret}")
  when token_type_hint
    payload = fmt("{payload}&token_type_hint={token_type_hint}")
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response
