# Generated by flux-connectors 0.15.0 — do not edit.
# Provider: babelforce
# Service: task-schedule
# Regenerate with `flux-connectors build`.

op babelforce-get-task-schedules(page: Number, page_size: Number) -> Any
  description "List cron scheduled tasks"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/schedules")
  sep = "?"
  when page
    url = fmt("{url}{sep}page={page}")
    sep = "&"
  when page_size
    url = fmt("{url}{sep}page_size={page_size}")
  response = http.request(method: "GET", url)
  return response

op babelforce-submit-task-schedule(cron: String, name: String, task: Any, template_id: String, template_style: String, timezone: String) -> Any
  description "Schedule new task"
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/schedules")
  content_type = "application/json"
  payload = { cron, name, task, template_id, template_style, timezone }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op babelforce-get-task-schedule(taskScheduleName: String) -> Any
  description "Get cron schedule task by name"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/schedules/{taskScheduleName}")
  response = http.request(method: "GET", url)
  return response

op babelforce-delete-schedule-task(taskScheduleName: String) -> Any
  description "Delete scheduled task"
  risk "destructive"
  idempotency "non_idempotent"
  effects ["network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/schedules/{taskScheduleName}")
  response = http.request(method: "DELETE", url)
  return response
