# Generated by flux-connectors 0.25.0 — do not edit.
# Provider: babelforce
# Service: task-automation
# Regenerate with `flux-connectors build`.

op babelforce-change-agent-lock(lockState: String) -> Any
  risk "high"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/agent/tasks/locking/{lockState}")
  response = http.request(method: "POST", url)
  return response

op babelforce-agent-action-on-task(taskId: String, agentAction: String, reason: String) -> Any
  risk "high"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/agent/tasks/{taskId}/{agentAction}")
  content_type = "application/json"
  payload = { reason }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op babelforce-tasks(filter: String, page: Number, page_size: Number) -> Any
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks")
  response = http.request(method: "GET", query: { filter, page, page_size }, url)
  return response

op babelforce-submit-task(actions: Any, body: Any, id: String, queue_id: String, scheduled_at: String, selection_settings: Any, task_completion: Any, type: String) -> Any
  risk "high"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks")
  content_type = "application/json"
  payload = { actions, body, id, queue_id, scheduled_at, selection_settings, task_completion, type }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op babelforce-testing(actions: Any, input: Any) -> Any
  risk "high"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/action/test")
  content_type = "application/json"
  payload = { actions, input }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op babelforce-list-secret-prefixes -> Any
  description "Retrieves a list of secret prefixes"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/configurations/secrets")
  response = http.request(method: "GET", url)
  return response

op babelforce-list-secret-keys(prefix: String) -> Any
  description "Retrieves a list of secret keys"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/configurations/secrets/{prefix}")
  response = http.request(method: "GET", url)
  return response

op babelforce-create-secrets(prefix: String, body: Any) -> Any
  description "Creates a map of secrets. Only supported values are strings"
  risk "high"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/configurations/secrets/{prefix}")
  content_type = "application/json"
  payload = parse(body, as: "json")
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op babelforce-patch-secrets(prefix: String, body: Any) -> Any
  description "Appends values to an existing secret prefix. Only supported values are strings"
  risk "high"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/configurations/secrets/{prefix}")
  content_type = "application/json"
  payload = parse(body, as: "json")
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "PATCH", url)
  return response

op babelforce-delete-secret-keys(prefix: String, body: List<String>) -> Any
  description "Delete a list of secrets"
  risk "destructive"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/configurations/secrets/{prefix}")
  content_type = "application/json"
  payload = parse(body, as: "json")
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "DELETE", url)
  return response

op babelforce-read-selection-configuration -> Any
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/configurations/selection")
  response = http.request(method: "GET", url)
  return response

op babelforce-create-selection-configuration(accept_timeout: Number, complete_timeout: Number, expire_in: Number, reschedule_delay: Number, selection_engine: String) -> Any
  risk "high"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/configurations/selection")
  content_type = "application/json"
  payload = { accept_timeout, complete_timeout, expire_in, reschedule_delay, selection_engine }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op babelforce-update-selection-configuration(accept_timeout: Number, complete_timeout: Number, expire_in: Number, reschedule_delay: Number, selection_engine: String) -> Any
  risk "high"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/configurations/selection")
  content_type = "application/json"
  payload = { accept_timeout, complete_timeout, expire_in, reschedule_delay, selection_engine }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "PUT", url)
  return response

op babelforce-delete-selection-configuration -> Any
  risk "destructive"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/configurations/selection")
  response = http.request(method: "DELETE", url)
  return response

op babelforce-list(filter: String, type: String, details: String, page_size: Number, page: Number, context: Bool) -> Any
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/logs/customer")
  response = http.request(method: "GET", query: { context, details, filter, page, page_size, type }, url)
  return response

op babelforce-agent-interaction-duration(agentId: String) -> Any
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/metrics/agent/{agentId}/interactions")
  response = http.request(method: "GET", url)
  return response

op babelforce-agent-interactions(agentId: String) -> Any
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/metrics/agent/{agentId}/journal")
  response = http.request(method: "GET", url)
  return response

op babelforce-task-journal(taskId: String) -> Any
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/metrics/{taskId}/journal")
  response = http.request(method: "GET", url)
  return response

op babelforce-list-scripts(type: String, filter: String, page: Number, page_size: Number) -> Any
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/scripts/{type}")
  response = http.request(method: "GET", query: { filter, page, page_size }, url)
  return response

op babelforce-submit-script(type: String, file: String, metadata: Any) -> Any
  risk "high"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/scripts/{type}")
  content_type = "application/json"
  payload = { file, metadata }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op babelforce-get-script(codeId: String, type: String, response_2: String) -> Any
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/scripts/{type}/{codeId}")
  response = http.request(method: "GET", query: { response: response_2 }, url)
  return response

op babelforce-update-script(codeId: String, type: String, file: String, metadata: Any) -> Any
  risk "high"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/scripts/{type}/{codeId}")
  content_type = "application/json"
  payload = { file, metadata }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "PUT", url)
  return response

op babelforce-delete-script(codeId: String, type: String) -> Any
  risk "destructive"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/scripts/{type}/{codeId}")
  response = http.request(method: "DELETE", url)
  return response

op babelforce-submit-task-template(template: String, style: String, body: Any) -> Any
  risk "high"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/template/{template}")
  content_type = "application/json"
  payload = parse(body, as: "json")
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", query: { style }, url)
  return response

op babelforce-task-usage(type: String, start: String, end: String, rate: String) -> Any
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/usage")
  response = http.request(method: "GET", query: { end, rate, start, type }, url)
  return response

op babelforce-task-usage-types(start: String, end: String) -> Any
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/usage/types")
  response = http.request(method: "GET", query: { end, start }, url)
  return response

op babelforce-task(taskId: String) -> Any
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/{taskId}")
  response = http.request(method: "GET", url)
  return response

op babelforce-update-task(taskId: String, body: Any) -> Any
  risk "high"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/{taskId}")
  content_type = "application/json"
  payload = parse(body, as: "json")
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "PUT", url)
  return response

op babelforce-manager-interrupt-on-task(taskId: String, interruptTo: String, reason: String) -> Any
  description "Interrupts execution of a task by requesting that the task is moved to an end state."
  risk "high"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/{taskId}/interrupt/{interruptTo}")
  content_type = "application/json"
  payload = { reason }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op babelforce-change-task-state(taskId: String, taskState: String) -> Any
  description "this endpoint is deprecated, use /api/v3/tasks/{taskId}/interrupt/{interruptTo} instead."
  risk "high"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v3/tasks/{taskId}/{taskState}")
  response = http.request(method: "PUT", url)
  return response
