# Generated by flux-connectors 0.23.0 — do not edit.
# Provider: babelforce
# Service: user
# Regenerate with `flux-connectors build`.

op babelforce-user-me-get -> Any
  description "Get the current User"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v2/user/me")
  response = http.request(method: "GET", url)
  return response

op babelforce-list-accounts -> Any
  description "Get List of available Accounts"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v2/user/accounts")
  response = http.request(method: "GET", url)
  return response

op babelforce-reset-password -> Any
  description "Request a Password Change"
  risk "high"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose false

  base = "https://services.babelforce.com"
  url = fmt("{base}/api/v2/user/reset-password")
  response = http.request(method: "POST", url)
  return response
