# Generated by flux-connectors 0.6.0 — do not edit.
# Provider: box
# Regenerate with `flux-connectors build`.

op box-user-me -> Any
  description "Get the user this access token authenticates as, confirming the token resolves and naming the account it belongs to. Takes no parameters. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/message`, its error code at `/code` in the response body."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://api.box.com"
  url = fmt("{base}/2.0/users/me")
  response = http.request(method: "GET", url)
  return response

op box-folder-get(folder_id: String) -> Any
  description "Get one folder's metadata: name, size, timestamps and parent. Does not return its contents — use box-folder-items-list for that. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/message`, its error code at `/code` in the response body."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://api.box.com"
  url = fmt("{base}/2.0/folders/{folder_id}")
  response = http.request(method: "GET", url)
  return response

op box-folder-items-list(folder_id: String) -> Any
  description "List the files and folders directly inside a folder, first page only (Box's own default page size). Each entry is a mini item representation — its type, id and name — not the full metadata box-file-get or box-folder-get returns. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/message`, its error code at `/code` in the response body."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://api.box.com"
  url = fmt("{base}/2.0/folders/{folder_id}/items")
  response = http.request(method: "GET", url)
  return response

op box-file-get(file_id: String) -> Any
  description "Get one file's metadata: name, size, timestamps and parent folder. This does NOT return the file's content — Box serves file content from a signed, time-limited URL reached only through a 302 redirect this connector does not follow, so file content is out of scope entirely. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/message`, its error code at `/code` in the response body."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://api.box.com"
  url = fmt("{base}/2.0/files/{file_id}")
  response = http.request(method: "GET", url)
  return response

op box-folder-create(name: String, parent_id: String) -> Any
  description "Create a new, empty folder as a child of an existing folder. Naming a folder that already exists under the same parent answers 409 conflict rather than creating a duplicate. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/message`, its error code at `/code` in the response body."
  risk "medium"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://api.box.com"
  url = fmt("{base}/2.0/folders")
  content_type = "application/json"
  payload = { name, parent: { id: parent_id } }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op box-file-copy(file_id: String, parent_id: String) -> Any
  description "Copy an existing file into a different folder, keeping its original name. Each call creates a new, independent file — copying the same file twice produces two copies, not one. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/message`, its error code at `/code` in the response body."
  risk "medium"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://api.box.com"
  url = fmt("{base}/2.0/files/{file_id}/copy")
  content_type = "application/json"
  payload = { parent: { id: parent_id } }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response
