# Generated by flux-connectors 0.8.0 — do not edit.
# Provider: clickup
# Regenerate with `flux-connectors build`.

op clickup-team-list -> Any
  description "List the workspaces (called \"teams\" in ClickUp's API) the token can see. Takes no parameters; used as the verify read to prove a token resolves, and as the source of the workspace-level context a space id is nested under"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://api.clickup.com/api/v2"
  url = fmt("{base}/team")
  response = http.request(method: "GET", url)
  return response

op clickup-space-folder-list(space_id: String, archived: Bool) -> Any
  description "List a space's folders. Each folder's own lists are nested inline in the response — read a folder's `lists` field for the list ids clickup-list-task-list and clickup-task-create take, rather than looking for a separate folder-to-list operation"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://api.clickup.com/api/v2"
  url = fmt("{base}/space/{space_id}/folder")
  sep = "?"
  when archived
    url = fmt("{url}{sep}archived={archived}")
  response = http.request(method: "GET", url)
  return response

op clickup-list-task-list(list_id: String, archived: Bool, page: Number, order_by: String, reverse: Bool, include_closed: Bool) -> Any
  description "List tasks in a list, most recently created first by default"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://api.clickup.com/api/v2"
  url = fmt("{base}/list/{list_id}/task")
  sep = "?"
  when archived
    url = fmt("{url}{sep}archived={archived}")
    sep = "&"
  when page
    url = fmt("{url}{sep}page={page}")
    sep = "&"
  when order_by
    url = fmt("{url}{sep}order_by={order_by}")
    sep = "&"
  when reverse
    url = fmt("{url}{sep}reverse={reverse}")
    sep = "&"
  when include_closed
    url = fmt("{url}{sep}include_closed={include_closed}")
  response = http.request(method: "GET", url)
  return response

op clickup-task-get(task_id: String, include_subtasks: Bool) -> Any
  description "Get one task by id"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://api.clickup.com/api/v2"
  url = fmt("{base}/task/{task_id}")
  sep = "?"
  when include_subtasks
    url = fmt("{url}{sep}include_subtasks={include_subtasks}")
  response = http.request(method: "GET", url)
  return response

op clickup-task-create(list_id: String, name: String, description: String, status: String, priority: Number, due_date: Number) -> Any
  description "Create a task in a list. Created with `notify_all` left at its default (false), so nobody is emailed by this call"
  risk "medium"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://api.clickup.com/api/v2"
  url = fmt("{base}/list/{list_id}/task")
  content_type = "application/json"
  payload = { description, due_date, name, priority, status }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op clickup-task-update(task_id: String, name: String, description: String, status: String, priority: Number, due_date: Number) -> Any
  description "Update a task's plain fields (name, description, status, priority, due date). Every field below is optional and ClickUp's update is sparse: an omitted field is left unchanged. Reassigning or rewatching the task is not supported by this operation — ClickUp takes those as {add, rem} deltas naming specific people, which this connector does not declare"
  risk "medium"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://api.clickup.com/api/v2"
  url = fmt("{base}/task/{task_id}")
  content_type = "application/json"
  payload = { description, due_date, name, priority, status }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "PUT", url)
  return response
