# Generated by flux-connectors 0.10.1 — do not edit.
# Provider: cloudflare
# Regenerate with `flux-connectors build`.

op cloudflare-zone-list -> Any
  description "List the zones (domains) this API token can see, with each zone's id, name, status and assigned Cloudflare name servers. Returns Cloudflare's first page only; this connector declares no page or filter parameters (see the connector's header note). The zone `id` returned here is the value an operator pins as this connection's `zone_id`; every other operation in this connector is already scoped to that one zone and does not take it as an argument. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/errors/0/message`, its error code at `/errors/0/code` in the response body."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://api.cloudflare.com/client/v4"
  url = fmt("{base}/zones")
  response = http.request(method: "GET", url)
  return response

op cloudflare-dns-record-list -> Any
  description "List the DNS records in a zone: each record's id, type, name, content, TTL and whether it is proxied through Cloudflare. Returns Cloudflare's first page only; this connector declares no page or filter parameters (see the connector's header note). A non-2xx response is returned as data, not a failure: the vendor's error message is at `/errors/0/message`, its error code at `/errors/0/code` in the response body."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://api.cloudflare.com/client/v4"
  zone_id = "{zone_id}"
  url = fmt("{base}/zones/{zone_id}/dns_records")
  response = http.request(method: "GET", url)
  return response

op cloudflare-dns-record-create(type: String, name: String, content: String) -> Any
  description "Create a DNS record in a zone. Cloudflare does not deduplicate: creating the same name/type/content pair twice makes two records, so this is not idempotent. The created record, with its assigned id, is in the response. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/errors/0/message`, its error code at `/errors/0/code` in the response body."
  risk "medium"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://api.cloudflare.com/client/v4"
  zone_id = "{zone_id}"
  url = fmt("{base}/zones/{zone_id}/dns_records")
  content_type = "application/json"
  payload = { content, name, type }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op cloudflare-dns-record-delete(dns_record_id: String) -> Any
  description "Delete one DNS record. There is no API route back: Cloudflare's dashboard \"recently deleted\" surface is a retention-window UI feature, not an endpoint, so a flux run cannot undo this. Responds with just the deleted record's id. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/errors/0/message`, its error code at `/errors/0/code` in the response body."
  risk "destructive"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://api.cloudflare.com/client/v4"
  zone_id = "{zone_id}"
  url = fmt("{base}/zones/{zone_id}/dns_records/{dns_record_id}")
  response = http.request(method: "DELETE", url)
  return response

op cloudflare-cache-purge -> Any
  description "Purge every cached asset for a zone, immediately, for every visitor worldwide. There is no partial or selective purge in this connector (see its header note) — every call empties the whole zone's edge cache. Repeating it changes nothing further, but each call can spike load on the origin as the cache refills, so it should not be called more often than a real cache-affecting change warrants. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/errors/0/message`, its error code at `/errors/0/code` in the response body."
  risk "high"
  idempotency "conditional"
  effects ["network"]
  expose true

  base = "https://api.cloudflare.com/client/v4"
  zone_id = "{zone_id}"
  url = fmt("{base}/zones/{zone_id}/purge_cache")
  content_type = "application/json"
  purge_everything = true
  payload = { purge_everything }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response
