# Generated by flux-connectors 0.18.0 — do not edit.
# Provider: datadog
# Regenerate with `flux-connectors build`.

op datadog-monitor-list -> Any
  description "List every monitor visible to this API key. Also this connector's `verify` — a bounded read that runs unattended, needing no argument"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://api.datadoghq.com"
  url = fmt("{base}/api/v1/monitor")
  response = http.request(method: "GET", url)
  return response

op datadog-monitor-get(monitor_id: Number) -> Any
  description "Get one monitor by id"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://api.datadoghq.com"
  url = fmt("{base}/api/v1/monitor/{monitor_id}")
  response = http.request(method: "GET", url)
  return response

op datadog-incident-list -> Any
  description "List the organization's incidents"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://api.datadoghq.com"
  url = fmt("{base}/api/v2/incidents")
  response = http.request(method: "GET", url)
  return response

op datadog-incident-get(incident_id: String) -> Any
  description "Get one incident by id"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://api.datadoghq.com"
  url = fmt("{base}/api/v2/incidents/{incident_id}")
  response = http.request(method: "GET", url)
  return response
