# Generated by flux-connectors 0.14.0 — do not edit.
# Provider: freshdesk
# Regenerate with `flux-connectors build`.

op freshdesk-test(per_page: Number) -> Any
  description "Verify credentials with a bounded contact read"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://{domain}/api/v2"
  url = fmt("{base}/contacts")
  sep = "?"
  when per_page
    url = fmt("{url}{sep}per_page={per_page}")
  response = http.request(method: "GET", url)
  return response

op freshdesk-ticket-list(req_id: String, req_email: String, company_id: String, updated: String) -> Any
  description "List and filter tickets"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://{domain}/api/v2"
  url = fmt("{base}/tickets")
  sep = "?"
  when req_id
    url = fmt("{url}{sep}requester_id={req_id}")
    sep = "&"
  when req_email
    url = fmt("{url}{sep}email={req_email}")
    sep = "&"
  when company_id
    url = fmt("{url}{sep}company_id={company_id}")
    sep = "&"
  when updated
    url = fmt("{url}{sep}updated_since={updated}")
  response = http.request(method: "GET", url)
  return response

op freshdesk-ticket-get(id: String) -> Any
  description "View one ticket"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://{domain}/api/v2"
  url = fmt("{base}/tickets/{id}")
  response = http.request(method: "GET", url)
  return response

op freshdesk-ticket-create(phone: String, name: String, requester_id: Number, subject: String, description: String, status: Number, priority: Number, source: Number, responder_id: Number, type: String, email_config_id: Number, group_id: Number, product_id: Number, tags: List<String>, cc_emails: List<String>, custom_fields: Any) -> Any
  description "Create a ticket. The requester must be identified either by requester_id, or by phone together with name — Freshdesk states this only in prose and its required flags do not capture it"
  risk "medium"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://{domain}/api/v2"
  url = fmt("{base}/tickets")
  content_type = "application/json"
  payload = { cc_emails, custom_fields, description, email_config_id, group_id, name, phone, priority, product_id, requester_id, responder_id, source, status, subject, tags, type }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op freshdesk-ticket-update(id: Number, subject: String, description: String, status: Number, priority: Number, requester_id: Number, responder_id: Number, name: String, phone: String, email: String, type: String, email_config_id: Number, group_id: Number, product_id: Number, tags: List<String>, custom_fields: Any) -> Any
  description "Update a ticket's fields"
  risk "medium"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://{domain}/api/v2"
  url = fmt("{base}/tickets/{id}")
  content_type = "application/json"
  payload = { custom_fields, description, email, email_config_id, group_id, name, phone, priority, product_id, requester_id, responder_id, status, subject, tags, type }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "PUT", url)
  return response

op freshdesk-ticket-note-add(id: Number, body: String, private: Bool, incoming: Bool, notify_emails: List<String>) -> Any
  description "Add a note to a ticket; the note is private unless explicitly made public"
  risk "medium"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://{domain}/api/v2"
  url = fmt("{base}/tickets/{id}/notes")
  content_type = "application/json"
  payload = { body, incoming, notify_emails, private }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op freshdesk-contact-list(phone: String, email: String, mobile: String, company_id: String, state: String) -> Any
  description "List and filter contacts, e.g. to resolve a caller before filing a ticket"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://{domain}/api/v2"
  url = fmt("{base}/contacts")
  sep = "?"
  when phone
    url = fmt("{url}{sep}phone={phone}")
    sep = "&"
  when email
    url = fmt("{url}{sep}email={email}")
    sep = "&"
  when mobile
    url = fmt("{url}{sep}mobile={mobile}")
    sep = "&"
  when company_id
    url = fmt("{url}{sep}company_id={company_id}")
    sep = "&"
  when state
    url = fmt("{url}{sep}state={state}")
  response = http.request(method: "GET", url)
  return response

op freshdesk-contact-get(id: String) -> Any
  description "Get one contact"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://{domain}/api/v2"
  url = fmt("{base}/contacts/{id}")
  response = http.request(method: "GET", url)
  return response

op freshdesk-contact-create(name: String, email: String, phone: String) -> Any
  description "Create a contact"
  risk "medium"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://{domain}/api/v2"
  url = fmt("{base}/contacts")
  content_type = "application/json"
  payload = { email, name, phone }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response
