# Generated by flux-connectors 0.1.0 — do not edit.
# Provider: github
# Regenerate with `flux-connectors build`.

op github-repo-get(owner: String, repo: String) -> Any
  description "Get one repository's metadata, including its default branch, visibility and permissions"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  $base = "https://api.github.com"
  $url = fmt("{base}/repos/{owner}/{repo}")
  $response = http.request({ method: "GET", url: $url })
  return $response

op github-issue-get(owner: String, repo: String, issue_number: Number) -> Any
  description "Get one issue by number. GitHub treats a pull request as an issue, so a PR number returns that PR's issue view; use github-pull-get for its merge and review state"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  $base = "https://api.github.com"
  $url = fmt("{base}/repos/{owner}/{repo}/issues/{issue_number}")
  $response = http.request({ method: "GET", url: $url })
  return $response

op github-pull-get(owner: String, repo: String, pull_number: Number) -> Any
  description "Get one pull request by number, with its merge state, head and base refs and review counts"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  $base = "https://api.github.com"
  $url = fmt("{base}/repos/{owner}/{repo}/pulls/{pull_number}")
  $response = http.request({ method: "GET", url: $url })
  return $response

op github-issue-create(owner: String, repo: String, title: String, body: String, labels: List<String>, assignees: List<String>) -> Any
  description "Open a new issue on a repository. The issue is immediately visible to everyone who can see the repository and notifies its subscribers"
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  $base = "https://api.github.com"
  $url = fmt("{base}/repos/{owner}/{repo}/issues")
  $content_type = "application/json"
  $payload = { assignees: $assignees, body: $body, labels: $labels, title: $title }
  $response = http.request({ body: $payload, headers: { "content-type": $content_type }, method: "POST", url: $url })
  return $response

op github-issue-comment-add(owner: String, repo: String, issue_number: Number, body: String) -> Any
  description "Add a comment to an issue or pull request. The comment is public to everyone who can see the repository and notifies its participants; GitHub has no private or internal comment here"
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  $base = "https://api.github.com"
  $url = fmt("{base}/repos/{owner}/{repo}/issues/{issue_number}/comments")
  $content_type = "application/json"
  $payload = { body: $body }
  $response = http.request({ body: $payload, headers: { "content-type": $content_type }, method: "POST", url: $url })
  return $response
