# Generated by flux-connectors 0.24.0 — do not edit.
# Provider: github
# Regenerate with `flux-connectors build`.

op github-repo-get(owner: String, repo: String) -> Any
  description "Get one repository's metadata, including its default branch, visibility and permissions"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.github.com"
  url = fmt("{base}/repos/{owner}/{repo}")
  Accept = "application/vnd.github+json"
  response = http.request(headers: { Accept }, method: "GET", url)
  return response

op github-issue-get(owner: String, repo: String, issue_number: Number) -> Any
  description "Get one issue by number. GitHub treats a pull request as an issue, so a PR number returns that PR's issue view; use github-pull-get for its merge and review state"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.github.com"
  url = fmt("{base}/repos/{owner}/{repo}/issues/{issue_number}")
  Accept = "application/vnd.github+json"
  response = http.request(headers: { Accept }, method: "GET", url)
  return response

op github-pull-get(owner: String, repo: String, pull_number: Number) -> Any
  description "Get one pull request by number, with its merge state, head and base refs and review counts"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.github.com"
  url = fmt("{base}/repos/{owner}/{repo}/pulls/{pull_number}")
  Accept = "application/vnd.github+json"
  response = http.request(headers: { Accept }, method: "GET", url)
  return response

op github-issue-create(owner: String, repo: String, title: String, body: String, labels: List<String>, assignees: List<String>) -> Any
  description "Open a new issue on a repository. The issue is immediately visible to everyone who can see the repository and notifies its subscribers"
  risk "high"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose true

  base = "https://api.github.com"
  url = fmt("{base}/repos/{owner}/{repo}/issues")
  content_type = "application/json"
  Accept = "application/vnd.github+json"
  payload = { assignees, body, labels, title }
  response = http.request(body: payload, headers: { Accept, "content-type": content_type }, method: "POST", url)
  return response

op github-issue-comment-add(owner: String, repo: String, issue_number: Number, body: String) -> Any
  description "Add a comment to an issue or pull request. The comment is public to everyone who can see the repository and notifies its participants; GitHub has no private or internal comment here"
  risk "high"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose true

  base = "https://api.github.com"
  url = fmt("{base}/repos/{owner}/{repo}/issues/{issue_number}/comments")
  content_type = "application/json"
  Accept = "application/vnd.github+json"
  payload = { body }
  response = http.request(body: payload, headers: { Accept, "content-type": content_type }, method: "POST", url)
  return response

op github-issue-list(owner: String, repo: String, per_page: Number, page: Number) -> Any
  description "List a repository's issues and pull requests with bounded integer pagination"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.github.com"
  url = fmt("{base}/repos/{owner}/{repo}/issues")
  Accept = "application/vnd.github+json"
  response = http.request(headers: { Accept }, method: "GET", query: { page, per_page }, url)
  return response

op github-pull-files-list(owner: String, repo: String, pull_number: Number, per_page: Number, page: Number) -> Any
  description "List the files changed by one pull request with bounded integer pagination"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.github.com"
  url = fmt("{base}/repos/{owner}/{repo}/pulls/{pull_number}/files")
  Accept = "application/vnd.github+json"
  response = http.request(headers: { Accept }, method: "GET", query: { page, per_page }, url)
  return response

op github-workflow-run-list(owner: String, repo: String, per_page: Number, page: Number) -> Any
  description "List a repository's GitHub Actions workflow runs with bounded integer pagination"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.github.com"
  url = fmt("{base}/repos/{owner}/{repo}/actions/runs")
  Accept = "application/vnd.github+json"
  response = http.request(headers: { Accept }, method: "GET", query: { page, per_page }, url)
  return response

op github-commit-list(owner: String, repo: String, per_page: Number, page: Number) -> Any
  description "List commits in a repository with bounded integer pagination"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.github.com"
  url = fmt("{base}/repos/{owner}/{repo}/commits")
  Accept = "application/vnd.github+json"
  response = http.request(headers: { Accept }, method: "GET", query: { page, per_page }, url)
  return response

op github-user-get -> Any
  description "Get the authenticated user — the identity the configured token acts as"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.github.com"
  url = fmt("{base}/user")
  Accept = "application/vnd.github+json"
  response = http.request(headers: { Accept }, method: "GET", url)
  return response

op github-org-list(per_page: Number, page: Number) -> Any
  description "List the organisations the authenticated user belongs to, with bounded integer pagination"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.github.com"
  url = fmt("{base}/user/orgs")
  Accept = "application/vnd.github+json"
  response = http.request(headers: { Accept }, method: "GET", query: { page, per_page }, url)
  return response

op github-org-repo-list(org: String, type: String, sort: String, direction: String, per_page: Number, page: Number) -> Any
  description "List an organisation's repositories, filtered by type and ordered, with bounded integer pagination"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.github.com"
  url = fmt("{base}/orgs/{org}/repos")
  Accept = "application/vnd.github+json"
  response = http.request(headers: { Accept }, method: "GET", query: { direction, page, per_page, sort, type }, url)
  return response

op github-user-repo-list(visibility: String, affiliation: String, type: String, sort: String, direction: String, per_page: Number, page: Number) -> Any
  description "List the repositories the authenticated user can access, filtered by visibility, affiliation and type"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.github.com"
  url = fmt("{base}/user/repos")
  Accept = "application/vnd.github+json"
  response = http.request(headers: { Accept }, method: "GET", query: { affiliation, direction, page, per_page, sort, type, visibility }, url)
  return response
