# Generated by flux-connectors 0.13.0 — do not edit.
# Provider: gitlab
# Regenerate with `flux-connectors build`.

op gitlab-user-get -> Any
  description "Get the currently authenticated user. Takes no parameters; used as the verify read to prove a token resolves"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://gitlab.com/api/v4"
  url = fmt("{base}/user")
  response = http.request(method: "GET", url)
  return response

op gitlab-issue-list(project_id: Number, state: String, page: Number, per_page: Number) -> Any
  description "List issues in a project, optionally filtered by state, newest activity first"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://gitlab.com/api/v4"
  url = fmt("{base}/projects/{project_id}/issues")
  sep = "?"
  when state
    url = fmt("{url}{sep}state={state}")
    sep = "&"
  when page
    url = fmt("{url}{sep}page={page}")
    sep = "&"
  when per_page
    url = fmt("{url}{sep}per_page={per_page}")
  response = http.request(method: "GET", url)
  return response

op gitlab-issue-get(project_id: Number, issue_iid: Number) -> Any
  description "Get one issue by its project-scoped number (iid), not its global id"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://gitlab.com/api/v4"
  url = fmt("{base}/projects/{project_id}/issues/{issue_iid}")
  response = http.request(method: "GET", url)
  return response

op gitlab-issue-create(project_id: Number, title: String, description: String, labels: String) -> Any
  description "Open a new issue on a project. Visible immediately to everyone with access to the project (the whole world, if the project is public) and notifies its watchers"
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://gitlab.com/api/v4"
  url = fmt("{base}/projects/{project_id}/issues")
  content_type = "application/json"
  payload = { description, labels, title }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op gitlab-merge-request-list(project_id: Number, state: String, page: Number, per_page: Number) -> Any
  description "List merge requests in a project, optionally filtered by state, newest activity first"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://gitlab.com/api/v4"
  url = fmt("{base}/projects/{project_id}/merge_requests")
  sep = "?"
  when state
    url = fmt("{url}{sep}state={state}")
    sep = "&"
  when page
    url = fmt("{url}{sep}page={page}")
    sep = "&"
  when per_page
    url = fmt("{url}{sep}per_page={per_page}")
  response = http.request(method: "GET", url)
  return response

op gitlab-pipeline-get(project_id: Number, pipeline_id: Number) -> Any
  description "Get one CI/CD pipeline's status and timing by its id"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://gitlab.com/api/v4"
  url = fmt("{base}/projects/{project_id}/pipelines/{pipeline_id}")
  response = http.request(method: "GET", url)
  return response

op gitlab-branch-list(project_id: Number, page: Number, per_page: Number) -> Any
  description "List a project's repository branches"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://gitlab.com/api/v4"
  url = fmt("{base}/projects/{project_id}/repository/branches")
  sep = "?"
  when page
    url = fmt("{url}{sep}page={page}")
    sep = "&"
  when per_page
    url = fmt("{url}{sep}per_page={per_page}")
  response = http.request(method: "GET", url)
  return response
