# Generated by flux-connectors 0.9.0 — do not edit.
# Provider: hubspot
# Regenerate with `flux-connectors build`.

op hubspot-contact-get(contact_id: Number) -> Any
  description "Read one contact by record id. Returns only HubSpot's default contact properties — name, email and record timestamps; a custom property needs a `properties` projection this connector cannot express yet. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/message`, its error code at `/category` in the response body."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://api.hubapi.com"
  url = fmt("{base}/crm/v3/objects/contacts/{contact_id}")
  response = http.request(method: "GET", url)
  return response

op hubspot-contact-create(email: String) -> Any
  description "Create a contact from an email address. HubSpot treats email as the contact's unique identifier and rejects a duplicate with 409. The new record is visible to everyone in the portal and can be enrolled by a workflow, which may send it marketing email. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/message`, its error code at `/category` in the response body."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://api.hubapi.com"
  url = fmt("{base}/crm/v3/objects/contacts")
  content_type = "application/json"
  payload = { properties: { email } }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op hubspot-contact-update(contact_id: Number, firstname: String, lastname: String) -> Any
  description "Overwrite a contact's first and last name. Both are written on every call — this operation replaces them rather than merging, so re-send the one you are not changing (read it first with hubspot-contact-get). The change is visible to everyone in the portal and can trigger a workflow. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/message`, its error code at `/category` in the response body."
  risk "high"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://api.hubapi.com"
  url = fmt("{base}/crm/v3/objects/contacts/{contact_id}")
  content_type = "application/json"
  payload = { properties: { firstname, lastname } }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "PATCH", url)
  return response

op hubspot-company-get(company_id: Number) -> Any
  description "Read one company by record id. Returns only HubSpot's default company properties — name, domain and record timestamps. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/message`, its error code at `/category` in the response body."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://api.hubapi.com"
  url = fmt("{base}/crm/v3/objects/companies/{company_id}")
  response = http.request(method: "GET", url)
  return response

op hubspot-deal-get(deal_id: Number) -> Any
  description "Read one deal by record id. Returns only HubSpot's default deal properties — name, amount, stage, pipeline and close date. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/message`, its error code at `/category` in the response body."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://api.hubapi.com"
  url = fmt("{base}/crm/v3/objects/deals/{deal_id}")
  response = http.request(method: "GET", url)
  return response
