# Generated by flux-connectors 0.25.0 — do not edit.
# Provider: klaviyo
# Regenerate with `flux-connectors build`.

op klaviyo-account-list -> Any
  description "Read the Klaviyo account this API key belongs to, with its timezone, currency, industry and contact details. Returns exactly one account — a private key is scoped to one — so this is the call that answers 'which account am I connected to'. Also this connector's verify: it takes no argument and needs only the accounts:read scope"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://a.klaviyo.com/api"
  url = fmt("{base}/accounts")
  revision = "2026-07-15"
  response = http.request(headers: { revision }, method: "GET", url)
  return response

op klaviyo-profile-list -> Any
  description "List customer profiles in the account, newest first. Returns the FIRST PAGE ONLY — Klaviyo pages with an opaque `page[cursor]` query parameter this connector cannot send, so there is no way to reach later pages and no way to filter. Every profile carries personal data: an email address, often a phone number and a postal location"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://a.klaviyo.com/api"
  url = fmt("{base}/profiles")
  revision = "2026-07-15"
  response = http.request(headers: { revision }, method: "GET", url)
  return response

op klaviyo-profile-get(id: String) -> Any
  description "Read one customer profile by its Klaviyo id, with its identifiers, custom properties, consent state and location. Returns personal data about a named individual"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://a.klaviyo.com/api"
  url = fmt("{base}/profiles/{id}")
  revision = "2026-07-15"
  response = http.request(headers: { revision }, method: "GET", url)
  return response

op klaviyo-profile-create(email: String, phone_number: String, external_id: String, first_name: String, last_name: String, organization: String, title: String) -> Any
  description "Create a customer profile. At least one identifier is required — email, phone number or external id — and Klaviyo answers 409 Conflict if a profile with that identifier already exists, so this creates and never updates. The created profile can be marketed to only once it is subscribed, which this connector does not do"
  risk "medium"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose true

  base = "https://a.klaviyo.com/api"
  url = fmt("{base}/profiles")
  content_type = "application/json"
  revision = "2026-07-15"
  resource_type = "profile"
  payload = { data: { attributes: { email, external_id, first_name, last_name, organization, phone_number, title }, type: resource_type } }
  response = http.request(body: payload, headers: { "content-type": content_type, revision }, method: "POST", url)
  return response

op klaviyo-list-list -> Any
  description "List the account's lists — static, opt-in collections of profiles, as opposed to segments, which are live queries and are not shipped here. Returns the FIRST PAGE ONLY; Klaviyo's `page[cursor]` query parameter cannot be sent by this connector. Returns the lists themselves, not their members"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://a.klaviyo.com/api"
  url = fmt("{base}/lists")
  revision = "2026-07-15"
  response = http.request(headers: { revision }, method: "GET", url)
  return response

op klaviyo-event-create(metric_name: String, profile_email: String, properties: Any, value: Number, value_currency: String, unique_id: String) -> Any
  description "Post an event about a customer — a purchase, a page view, anything the account measures. THIS CAN CAUSE A MESSAGE TO BE SENT: an event triggers any Klaviyo flow built on its metric, so an email or SMS may reach the named profile immediately. Klaviyo creates the metric and the profile on first use if they do not exist. Answers 202 Accepted with no body: the event is queued, not confirmed. Pass unique_id to make a retry safe — Klaviyo records only the first event with a given unique_id for the same profile and metric"
  risk "high"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose true

  base = "https://a.klaviyo.com/api"
  url = fmt("{base}/events")
  content_type = "application/json"
  revision = "2026-07-15"
  resource_type = "event"
  metric_type = "metric"
  profile_type = "profile"
  payload = { data: { attributes: { metric: { data: { attributes: { name: metric_name }, type: metric_type } }, profile: { data: { attributes: { email: profile_email }, type: profile_type } }, properties, unique_id, value, value_currency }, type: resource_type } }
  response = http.request(body: payload, headers: { "content-type": content_type, revision }, method: "POST", url)
  return response
