# Generated by flux-connectors 0.21.0 — do not edit.
# Provider: launchdarkly
# Regenerate with `flux-connectors build`.

op launchdarkly-project-list(limit: Number, offset: Number) -> Any
  description "List every project in the LaunchDarkly account. A project is the top-level grouping that owns environments and feature flags"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://app.launchdarkly.com/api/v2"
  url = fmt("{base}/projects")
  response = http.request(method: "GET", query: { limit, offset }, url)
  return response

op launchdarkly-environment-list(project_key: String, limit: Number, offset: Number) -> Any
  description "List the environments (e.g. production, staging) that belong to one project"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://app.launchdarkly.com/api/v2"
  url = fmt("{base}/projects/{project_key}/environments")
  response = http.request(method: "GET", query: { limit, offset }, url)
  return response

op launchdarkly-flag-list(project_key: String, env: String, limit: Number, offset: Number) -> Any
  description "List the feature flags defined in one project"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://app.launchdarkly.com/api/v2"
  url = fmt("{base}/flags/{project_key}")
  response = http.request(method: "GET", query: { env, limit, offset }, url)
  return response

op launchdarkly-flag-get(project_key: String, feature_flag_key: String, env: String) -> Any
  description "Get one feature flag's full definition, including its current on/off state and targeting per environment"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://app.launchdarkly.com/api/v2"
  url = fmt("{base}/flags/{project_key}/{feature_flag_key}")
  response = http.request(method: "GET", query: { env }, url)
  return response

op launchdarkly-flag-toggle(project_key: String, feature_flag_key: String, body: List<Any>) -> Any
  description "Turn a feature flag on or off in one environment. This is a live production change: every SDK instance currently evaluating this flag in this environment — web, mobile and backend alike — switches to the other branch as soon as this call returns, for every real user it serves. It is reversible by toggling back, but it is not a private or staged edit"
  risk "high"
  idempotency "conditional"
  effects ["write", "network"]
  expose true

  base = "https://app.launchdarkly.com/api/v2"
  url = fmt("{base}/flags/{project_key}/{feature_flag_key}")
  content_type = "application/json"
  payload = parse(body, as: "json")
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "PATCH", url)
  return response
