# Generated by flux-connectors 0.6.0 — do not edit.
# Provider: linear
# Regenerate with `flux-connectors build`.

op linear-viewer -> Any
  description "Read the Linear user this connection's API key belongs to: their id, name, email and admin flag. Takes no arguments. Use it to confirm the key works and to learn whose access this connection actually has, since a Linear personal key cannot be narrowed below its owner's permissions. Also this connector's verify operation. Linear answers every failure with HTTP 200 and an `errors` array beside a null `data`, so check `errors` before reading `data`"
  risk "medium"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://api.linear.app"
  url = fmt("{base}/graphql")
  content_type = "application/json"
  query = """query Viewer {
  viewer {
    id
    name
    displayName
    email
    admin
  }
}
"""
  payload = { query }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op linear-team-list(first: Number) -> Any
  description "List the teams in this workspace with each one's id, key and name. The `id` returned here is what linear-issue-create takes as `teamId`, and the `key` is the prefix in an issue's identifier — the ENG in ENG-42. Returns the first page only; raise `first` to widen it. Linear answers every failure with HTTP 200 and an `errors` array beside a null `data`, so check `errors` before reading `data`"
  risk "medium"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://api.linear.app"
  url = fmt("{base}/graphql")
  content_type = "application/json"
  query = """query Teams($first: Int!) {
  teams(first: $first) {
    nodes {
      id
      key
      name
      description
    }
  }
}
"""
  payload = { query, variables: { first } }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op linear-issue-get(id: String) -> Any
  description "Read one issue by its id or by its human identifier such as ENG-42, including its title, description, priority, state, assignee, team and URL. Use it to confirm an issue exists and to read its current state before updating it. Linear answers every failure with HTTP 200 and an `errors` array beside a null `data`, so check `errors` before reading `data`; a missing issue comes back that way rather than as a 404"
  risk "medium"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://api.linear.app"
  url = fmt("{base}/graphql")
  content_type = "application/json"
  query = """query Issue($id: String!) {
  issue(id: $id) {
    id
    identifier
    title
    description
    url
    priority
    createdAt
    updatedAt
    state {
      id
      name
      type
    }
    assignee {
      id
      name
    }
    team {
      id
      key
    }
  }
}
"""
  payload = { query, variables: { id } }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op linear-issue-list(first: Number, after: String) -> Any
  description "List issues in the workspace, most recently updated first, with a page cursor. Pass `after` with the previous response's `pageInfo.endCursor` to get the next page, and stop when `pageInfo.hasNextPage` is false. Note that the cursor travels as a GraphQL variable rather than a query parameter, so this connector declares no pagination quirk and a host cannot page it automatically. Linear answers every failure with HTTP 200 and an `errors` array beside a null `data`, so check `errors` before reading `data`"
  risk "medium"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://api.linear.app"
  url = fmt("{base}/graphql")
  content_type = "application/json"
  query = """query Issues($first: Int!, $after: String) {
  issues(first: $first, after: $after, orderBy: updatedAt) {
    nodes {
      id
      identifier
      title
      url
      priority
      updatedAt
      state {
        name
        type
      }
      assignee {
        id
        name
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
"""
  payload = { query, variables: { after, first } }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op linear-issue-create(teamId: String, title: String, description: String, priority: Number, assigneeId: String) -> Any
  description "Create an issue on a team. Linear does not deduplicate: creating the same title twice makes two issues and notifies the team twice. The created issue, with its assigned identifier and URL, is in the response. `teamId` comes from linear-team-list. Linear answers every failure with HTTP 200 and an `errors` array beside a null `data`, so check `errors` and the payload's `success` flag before treating the issue as created"
  risk "medium"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://api.linear.app"
  url = fmt("{base}/graphql")
  content_type = "application/json"
  query = """mutation IssueCreate($teamId: String!, $title: String!, $description: String, $priority: Int, $assigneeId: String) {
  issueCreate(
    input: {teamId: $teamId, title: $title, description: $description, priority: $priority, assigneeId: $assigneeId}
  ) {
    success
    issue {
      id
      identifier
      title
      url
    }
  }
}
"""
  payload = { query, variables: { assigneeId, description, priority, teamId, title } }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op linear-issue-update(id: String, title: String, description: String, priority: Number, stateId: String, assigneeId: String) -> Any
  description "Change an existing issue's title, description, priority, workflow state or assignee. Every argument except `id` is optional and only the ones supplied are changed. Reassigning or moving an issue notifies the people watching it. Read the issue first with linear-issue-get if the current values matter. Linear answers every failure with HTTP 200 and an `errors` array beside a null `data`, so check `errors` and the payload's `success` flag before treating the change as applied"
  risk "medium"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://api.linear.app"
  url = fmt("{base}/graphql")
  content_type = "application/json"
  query = """mutation IssueUpdate($id: String!, $title: String, $description: String, $priority: Int, $stateId: String, $assigneeId: String) {
  issueUpdate(
    id: $id
    input: {title: $title, description: $description, priority: $priority, stateId: $stateId, assigneeId: $assigneeId}
  ) {
    success
    issue {
      id
      identifier
      title
      url
      priority
      state {
        id
        name
      }
    }
  }
}
"""
  payload = { query, variables: { assigneeId, description, id, priority, stateId, title } }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op linear-comment-create(issueId: String, body: String) -> Any
  description "Add a comment to an issue. The comment is attributed to the user the API key belongs to and notifies everyone watching the issue; Linear sends no un-notification, so a comment posted in error can be deleted but not un-seen. Linear answers every failure with HTTP 200 and an `errors` array beside a null `data`, so check `errors` and the payload's `success` flag before treating the comment as posted"
  risk "medium"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://api.linear.app"
  url = fmt("{base}/graphql")
  content_type = "application/json"
  query = """mutation CommentCreate($issueId: String!, $body: String!) {
  commentCreate(input: {issueId: $issueId, body: $body}) {
    success
    comment {
      id
      url
      createdAt
    }
  }
}
"""
  payload = { query, variables: { body, issueId } }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op linear-issue-archive(id: String) -> Any
  description "Archive an issue. It leaves every list, board and search in Linear and stops appearing to the team. This is Linear's form of deletion; it can be undone from Linear's own UI but not by this connector, which declares no unarchive operation. Linear answers every failure with HTTP 200 and an `errors` array beside a null `data`, so check `errors` and the payload's `success` flag before treating the issue as archived"
  risk "destructive"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://api.linear.app"
  url = fmt("{base}/graphql")
  content_type = "application/json"
  query = """mutation IssueArchive($id: String!) {
  issueArchive(id: $id) {
    success
  }
}
"""
  payload = { query, variables: { id } }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response
