# Generated by flux-connectors 0.19.0 — do not edit.
# Provider: microsoft_graph
# Service: calendar
# Regenerate with `flux-connectors build`.

op microsoft_graph-calendar-event-get(event_id: String) -> Any
  description "Get one calendar event: its subject, start and end, organizer, attendee list and cancellation state. Returned in UTC unless a `Prefer: outlook.timezone` header is sent, which this connector does not do. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/error/message`, its error code at `/error/code` in the response body."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://graph.microsoft.com"
  url = fmt("{base}/v1.0/me/events/{event_id}")
  response = http.request(method: "GET", url)
  return response

op microsoft_graph-calendar-event-create(subject: String, start_date_time: String, start_time_zone: String, end_date_time: String, end_time_zone: String) -> Any
  description "Create a single-instance event on the signed-in user's default calendar. No attendees can be declared yet (C-56), so nobody is invited and nobody is notified — the event appears only on the calendar it was created on. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/error/message`, its error code at `/error/code` in the response body."
  risk "medium"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://graph.microsoft.com"
  url = fmt("{base}/v1.0/me/events")
  content_type = "application/json"
  payload = { end: { dateTime: end_date_time, timeZone: end_time_zone }, start: { dateTime: start_date_time, timeZone: start_time_zone }, subject }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op microsoft_graph-calendar-calendar-get -> Any
  description "Get the signed-in user's own default calendar: its name, colour and sharing/editing permissions. This is the calendar, not its events — use microsoft_graph-calendar-event-get for one of those. Takes no argument: `/me/calendar` always resolves to the token's own default calendar. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/error/message`, its error code at `/error/code` in the response body."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://graph.microsoft.com"
  url = fmt("{base}/v1.0/me/calendar")
  response = http.request(method: "GET", url)
  return response

op microsoft_graph-calendar-category-list(_top: Number, _skip: Number) -> Any
  description "List the signed-in user's Outlook master categories with the Microsoft Graph MailboxSettings.Read permission"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://graph.microsoft.com"
  url = fmt("{base}/v1.0/me/outlook/masterCategories")
  response = http.request(method: "GET", query: { "$skip": _skip, "$top": _top }, url)
  return response

op microsoft_graph-calendar-time-zone-list(_top: Number, _skip: Number) -> Any
  description "List the mailbox server's supported time zones with the Microsoft Graph MailboxSettings.Read permission"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://graph.microsoft.com"
  url = fmt("{base}/v1.0/me/outlook/supportedTimeZones()")
  response = http.request(method: "GET", query: { "$skip": _skip, "$top": _top }, url)
  return response

op microsoft_graph-calendar-language-list(_top: Number, _skip: Number) -> Any
  description "List the mailbox server's supported languages and locales with the Microsoft Graph MailboxSettings.Read permission"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://graph.microsoft.com"
  url = fmt("{base}/v1.0/me/outlook/supportedLanguages()")
  response = http.request(method: "GET", query: { "$skip": _skip, "$top": _top }, url)
  return response
