# Generated by flux-connectors 0.8.0 — do not edit.
# Provider: microsoft_graph
# Service: files
# Regenerate with `flux-connectors build`.

op microsoft_graph-files-item-get(item_id: String) -> Any
  description "Get one OneDrive item's metadata by id: its name, size and where it lives. This never returns file content — downloading needs the separate /content endpoint, which returns a binary body and is not shipped by this connector. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/error/message`, its error code at `/error/code` in the response body."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://graph.microsoft.com"
  url = fmt("{base}/v1.0/me/drive/items/{item_id}")
  response = http.request(method: "GET", url)
  return response

op microsoft_graph-files-item-update(item_id: String, name: String) -> Any
  description "Rename a OneDrive item: sets its name and changes nothing else. Does not move it — moving is a PATCH to the separate parentReference field, which this operation deliberately does not declare (C-56). A non-2xx response is returned as data, not a failure: the vendor's error message is at `/error/message`, its error code at `/error/code` in the response body."
  risk "medium"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://graph.microsoft.com"
  url = fmt("{base}/v1.0/me/drive/items/{item_id}")
  content_type = "application/json"
  payload = { name }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "PATCH", url)
  return response
