# Generated by flux-connectors 0.26.0 — do not edit.
# Provider: miro
# Regenerate with `flux-connectors build`.

op miro-board-list -> Any
  description "List the boards this access token can see, with each board's id, name and description. Returns Miro's first page only; this connector declares no cursor or limit parameter (see the connector's header note). The board `id` returned here is what every other operation in this connector needs as `board_id`"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.miro.com/v2"
  url = fmt("{base}/boards")
  response = http.request(method: "GET", url)
  return response

op miro-board-item-list(board_id: String) -> Any
  description "List the items on a board, of any type (sticky note, shape, text or frame). Each item's shape depends on its `type`: sticky notes and text carry `data.content`, shapes carry `data.content` and `data.shape`, frames carry `data.title`. Returns Miro's first page only; this connector declares no cursor or limit parameter (see the connector's header note)"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.miro.com/v2"
  url = fmt("{base}/boards/{board_id}/items")
  response = http.request(method: "GET", url)
  return response

op miro-board-item-get(board_id: String, item_id: String) -> Any
  description "Get one item from a board, of any type (sticky note, shape, text or frame). Its shape depends on its `type` — see miro-board-item-list's description for what each carries"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.miro.com/v2"
  url = fmt("{base}/boards/{board_id}/items/{item_id}")
  response = http.request(method: "GET", url)
  return response

op miro-sticky-note-create(board_id: String, content: String) -> Any
  description "Create a sticky note on a board. Miro does not deduplicate: creating the same content twice makes two sticky notes, so this is not idempotent. The created note, with its assigned id, is in the response"
  risk "medium"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose true

  base = "https://api.miro.com/v2"
  url = fmt("{base}/boards/{board_id}/sticky_notes")
  content_type = "application/json"
  payload = { data: { content } }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op miro-sticky-note-update(board_id: String, item_id: String, content: String) -> Any
  description "Update a sticky note's text content. The content sent replaces what was there, so setting the same content twice ends in the same state. The updated note is in the response"
  risk "medium"
  idempotency "conditional"
  effects ["write", "network"]
  expose true

  base = "https://api.miro.com/v2"
  url = fmt("{base}/boards/{board_id}/sticky_notes/{item_id}")
  content_type = "application/json"
  payload = { data: { content } }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "PATCH", url)
  return response

op miro-sticky-note-delete(board_id: String, item_id: String) -> Any
  description "Delete one sticky note. There is no undo route in the API. Responds with no content"
  risk "destructive"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose true

  base = "https://api.miro.com/v2"
  url = fmt("{base}/boards/{board_id}/sticky_notes/{item_id}")
  response = http.request(method: "DELETE", url)
  return response
