# Generated by flux-connectors 0.18.0 — do not edit.
# Provider: newrelic
# Regenerate with `flux-connectors build`.

op newrelic-application-list -> Any
  description "List every application this account is monitoring with APM, each with its current health status and a summary of its response time, throughput and error rate. Takes no argument. Also this connector's `verify`: a bounded read that runs unattended and needs nothing beyond the configured host and key"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://{host}/v2"
  url = fmt("{base}/applications.json")
  response = http.request(method: "GET", url)
  return response

op newrelic-application-get(application_id: String) -> Any
  description "Get one application by id, with its current health status and the same summary figures the list returns. Use this to re-read one application after a deploy rather than listing the whole account"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://{host}/v2"
  url = fmt("{base}/applications/{application_id}.json")
  response = http.request(method: "GET", url)
  return response

op newrelic-alert-policy-list -> Any
  description "List the account's alert policies — the groupings New Relic evaluates conditions under, each with its incident rollup preference. Takes no argument. This lists the policies themselves, not the conditions inside them and not anything currently alerting; for that, read newrelic-alert-violation-list"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://{host}/v2"
  url = fmt("{base}/alerts_policies.json")
  response = http.request(method: "GET", url)
  return response

op newrelic-alert-violation-list -> Any
  description "List the account's alert violations from New Relic's default recent window. READ `closed_at` ON EVERY ENTRY: this returns closed violations as well as open ones, and a violation with a non-null `closed_at` has already resolved. Each entry names the policy and condition that fired and the entity that broke"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://{host}/v2"
  url = fmt("{base}/alerts_violations.json")
  response = http.request(method: "GET", url)
  return response

op newrelic-deployment-list(application_id: String) -> Any
  description "List the deployment markers recorded against one application, most recent first. These are the markers New Relic overlays on its charts — read them to answer \"what shipped before this went wrong\""
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://{host}/v2"
  url = fmt("{base}/applications/{application_id}/deployments.json")
  response = http.request(method: "GET", url)
  return response

op newrelic-deployment-create(application_id: String, revision: String, changelog: String, description: String, user: String) -> Any
  description "Record a deployment marker against an application, timestamped now. The marker appears on every chart for that application and is visible to everyone on the account; this connector cannot remove one once recorded. Calling this twice records two deployments"
  risk "medium"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://{host}/v2"
  url = fmt("{base}/applications/{application_id}/deployments.json")
  content_type = "application/json"
  payload = { deployment: { changelog, description, revision, user } }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response
