# Generated by flux-connectors 0.16.0 — do not edit.
# Provider: openrouter
# Regenerate with `flux-connectors build`.

op openrouter-models-list -> Any
  description "List every model OpenRouter routes to, with its context length, modalities and per-token pricing"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://openrouter.ai"
  url = fmt("{base}/api/v1/models")
  response = http.request(method: "GET", url)
  return response

op openrouter-model-endpoints-list(author: String, slug: String) -> Any
  description "List the upstream provider endpoints serving one model, with each one's pricing, context length and quantization"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://openrouter.ai"
  url = fmt("{base}/api/v1/models/{author}/{slug}/endpoints")
  response = http.request(method: "GET", url)
  return response

op openrouter-chat-completion(model: String, messages: List<Any>, max_completion_tokens: Number) -> Any
  description "Create a chat completion through OpenRouter, routed to the named model. Billed per input and output token, so the caller must state a token budget via max_completion_tokens"
  risk "medium"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://openrouter.ai"
  url = fmt("{base}/api/v1/chat/completions")
  content_type = "application/json"
  payload = { max_completion_tokens, messages, model }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op openrouter-credits-get -> Any
  description "Read the account's total purchased credits and total usage, in credit units"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://openrouter.ai"
  url = fmt("{base}/api/v1/credits")
  response = http.request(method: "GET", url)
  return response
