# Generated by flux-connectors 0.24.0 — do not edit.
# Provider: postmark
# Service: server
# Regenerate with `flux-connectors build`.

op postmark-email-send(from: String, to: String, cc: String, bcc: String, subject: String, text_body: String, html_body: String, reply_to: String, tag: String) -> Any
  description "Send a single email immediately from the token's server. Delivered within seconds and cannot be recalled. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/Message`, its error code at `/ErrorCode` in the response body."
  risk "high"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose true

  base = "https://api.postmarkapp.com"
  url = fmt("{base}/email")
  content_type = "application/json"
  payload = { Bcc: bcc, Cc: cc, From: from, HtmlBody: html_body, ReplyTo: reply_to, Subject: subject, Tag: tag, TextBody: text_body, To: to }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op postmark-deliverystats-get -> Any
  description "Get delivery statistics for this server: total inactive addresses and a breakdown of bounces by type. Also this connector's `verify` — a bounded read that runs unattended, needing no argument. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/Message`, its error code at `/ErrorCode` in the response body."
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.postmarkapp.com"
  url = fmt("{base}/deliverystats")
  response = http.request(method: "GET", url)
  return response

op postmark-bounce-list(count: Number, offset: Number) -> Any
  description "List bounces recorded on this server, most recent first. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/Message`, its error code at `/ErrorCode` in the response body."
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.postmarkapp.com"
  url = fmt("{base}/bounces")
  response = http.request(method: "GET", query: { count, offset }, url)
  return response

op postmark-bounce-get(bounce_id: Number) -> Any
  description "Get one recorded bounce by id. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/Message`, its error code at `/ErrorCode` in the response body."
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.postmarkapp.com"
  url = fmt("{base}/bounces/{bounce_id}")
  response = http.request(method: "GET", url)
  return response
