# Generated by flux-connectors 0.26.0 — do not edit.
# Provider: statuspage
# Regenerate with `flux-connectors build`.

op statuspage-incident-list -> Any
  description "List this status page's incidents, most recent first — both unresolved and already-resolved ones. Returns Statuspage's own first page of results; this connector declares no paging parameters, so a page with a long incident history is not enumerated exhaustively here. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/error` in the response body."
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.statuspage.io/v1/pages/{page_id}"
  url = fmt("{base}/incidents")
  response = http.request(method: "GET", url)
  return response

op statuspage-incident-get(incident_id: String) -> Any
  description "Get one incident on this status page, including every update posted to it so far. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/error` in the response body."
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.statuspage.io/v1/pages/{page_id}"
  url = fmt("{base}/incidents/{incident_id}")
  response = http.request(method: "GET", url)
  return response

op statuspage-incident-create(name: String, status: String, body: String, deliver_notifications: Bool) -> Any
  description "Open a new incident on this status page. It is public the moment this call returns — anyone loading the page sees it, and with deliver_notifications true Statuspage emails and texts every subscriber the page has. The incident itself is reversible (resolve it, or delete it), but a notification that has been sent cannot be recalled, so treat deliver_notifications as the irreversible half of this call. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/error` in the response body."
  risk "high"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose true

  base = "https://api.statuspage.io/v1/pages/{page_id}"
  url = fmt("{base}/incidents")
  content_type = "application/json"
  payload = { incident: { body, deliver_notifications, name, status } }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op statuspage-incident-update(incident_id: String, status: String, body: String, deliver_notifications: Bool) -> Any
  description "Post an update to an existing incident on this status page, moving it to a new lifecycle stage and adding a publicly visible message. The update appears on the page immediately, and with deliver_notifications true Statuspage emails and texts every subscriber. The incident's status can be moved again afterwards, but a notification that has been sent cannot be recalled. Does not rename the incident — this operation cannot change its title. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/error` in the response body."
  risk "high"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose true

  base = "https://api.statuspage.io/v1/pages/{page_id}"
  url = fmt("{base}/incidents/{incident_id}")
  content_type = "application/json"
  payload = { incident: { body, deliver_notifications, status } }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "PATCH", url)
  return response

op statuspage-component-list -> Any
  description "List the components this status page publishes — the individual services whose operational state the page shows. Takes no parameter at all and succeeds for any page the API key can administer, which is what makes it the connection check for a settings page's Test Connection button. Returns Statuspage's own first page of results; this connector declares no paging parameters. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/error` in the response body."
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.statuspage.io/v1/pages/{page_id}"
  url = fmt("{base}/components")
  response = http.request(method: "GET", url)
  return response
