# Generated by flux-connectors 0.22.0 — do not edit.
# Provider: trello
# Regenerate with `flux-connectors build`.

op trello-board-list -> Any
  description "List every board the token's own member can see, newest activity first. Takes no argument — `me` resolves to whoever the token belongs to. Also this connector's `verify`: a bounded read that runs unattended and needs nothing configured beyond the credential pair"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.trello.com/1"
  url = fmt("{base}/members/me/boards")
  response = http.request(method: "GET", url)
  return response

op trello-board-get(id: String) -> Any
  description "Get one board by id, with its settings and current state"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.trello.com/1"
  url = fmt("{base}/boards/{id}")
  response = http.request(method: "GET", url)
  return response

op trello-board-lists(id: String) -> Any
  description "List the open lists (columns) on a board, left to right. Each carries the `id` trello-list-cards and trello-card-create take"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.trello.com/1"
  url = fmt("{base}/boards/{id}/lists")
  response = http.request(method: "GET", url)
  return response

op trello-list-cards(id: String) -> Any
  description "List the open cards in one list, in board order. Archived cards are not returned"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.trello.com/1"
  url = fmt("{base}/lists/{id}/cards")
  response = http.request(method: "GET", url)
  return response

op trello-card-create(list_id: String, name: String, description: String) -> Any
  description "Create a card at the bottom of a list. The card is created unassigned, with no due date and no labels; Trello notifies whoever watches the list"
  risk "medium"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose true

  base = "https://api.trello.com/1"
  url = fmt("{base}/cards")
  content_type = "application/json"
  payload = { desc: description, idList: list_id, name }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response

op trello-card-archive(id: String, closed: Bool) -> Any
  description "Archive a card, or restore an archived one. Archiving is reversible and destroys nothing: the card leaves its list and stays readable in the board's archive"
  risk "medium"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose true

  base = "https://api.trello.com/1"
  url = fmt("{base}/cards/{id}")
  content_type = "application/json"
  payload = { closed }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "PUT", url)
  return response
