# Generated by flux-connectors 0.7.0 — do not edit.
# Provider: twilio
# Regenerate with `flux-connectors build`.

op twilio-account-get(account_sid: String) -> Any
  description "Verify credentials by fetching the authenticated Twilio account"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://api.twilio.com/2010-04-01"
  url = fmt("{base}/Accounts/{account_sid}.json")
  response = http.request(method: "GET", url)
  return response

op twilio-message-list(account_sid: String, page: Number, page_size: Number) -> Any
  description "List messages sent from or received by this account"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://api.twilio.com/2010-04-01"
  url = fmt("{base}/Accounts/{account_sid}/Messages.json")
  sep = "?"
  when page
    url = fmt("{url}{sep}Page={page}")
    sep = "&"
  when page_size
    url = fmt("{url}{sep}PageSize={page_size}")
  response = http.request(method: "GET", url)
  return response

op twilio-message-get(account_sid: String, message_sid: String) -> Any
  description "Fetch one message"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://api.twilio.com/2010-04-01"
  url = fmt("{base}/Accounts/{account_sid}/Messages/{message_sid}.json")
  response = http.request(method: "GET", url)
  return response

op twilio-call-list(account_sid: String, status: String, page: Number, page_size: Number) -> Any
  description "List calls made from or received by this account"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://api.twilio.com/2010-04-01"
  url = fmt("{base}/Accounts/{account_sid}/Calls.json")
  sep = "?"
  when status
    url = fmt("{url}{sep}Status={status}")
    sep = "&"
  when page
    url = fmt("{url}{sep}Page={page}")
    sep = "&"
  when page_size
    url = fmt("{url}{sep}PageSize={page_size}")
  response = http.request(method: "GET", url)
  return response

op twilio-call-get(account_sid: String, call_sid: String) -> Any
  description "Fetch one call"
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://api.twilio.com/2010-04-01"
  url = fmt("{base}/Accounts/{account_sid}/Calls/{call_sid}.json")
  response = http.request(method: "GET", url)
  return response
