# Generated by flux-connectors 0.6.0 — do not edit.
# Provider: typeform
# Regenerate with `flux-connectors build`.

op typeform-user-me -> Any
  description "Get the Typeform account this access token authenticates as: its account id, display alias, own account email and interface language. Confirms the token resolves. Takes no parameters. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/description`, its error code at `/code` in the response body."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://api.typeform.com"
  url = fmt("{base}/me")
  response = http.request(method: "GET", url)
  return response

op typeform-form-list(page: Number, page_size: Number, sort_by: String, order_by: String) -> Any
  description "List the forms in the authenticated account, most recently updated forms sorting available. Returns each form's id, title and public/private status but not its questions — use typeform-form-get for a form's fields. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/description`, its error code at `/code` in the response body."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://api.typeform.com"
  url = fmt("{base}/forms")
  sep = "?"
  when page
    url = fmt("{url}{sep}page={page}")
    sep = "&"
  when page_size
    url = fmt("{url}{sep}page_size={page_size}")
    sep = "&"
  when sort_by
    url = fmt("{url}{sep}sort_by={sort_by}")
    sep = "&"
  when order_by
    url = fmt("{url}{sep}order_by={order_by}")
  response = http.request(method: "GET", url)
  return response

op typeform-form-get(form_id: String) -> Any
  description "Get one form's own definition: its title, language, rendering type and questions (fields), plus its welcome and thank-you screens. Does not return any response data — use typeform-response-list for that. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/description`, its error code at `/code` in the response body."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://api.typeform.com"
  url = fmt("{base}/forms/{form_id}")
  response = http.request(method: "GET", url)
  return response

op typeform-response-list(form_id: String, page_size: Number, before: String, after: String, since: String, until: String, response_type: String, sort: String) -> Any
  description "List one form's responses, newest first by default. Paginate with `before`/`after`, each naming the `token` of a response already retrieved, to page toward older or newer responses respectively; `page_size` alone returns only the first page. Each response's `answers` holds whatever that respondent typed or selected — this connector never inspects or filters on answer content. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/description`, its error code at `/code` in the response body."
  risk "low"
  idempotency "idempotent"
  effects ["network"]
  expose true

  base = "https://api.typeform.com"
  url = fmt("{base}/forms/{form_id}/responses")
  sep = "?"
  when page_size
    url = fmt("{url}{sep}page_size={page_size}")
    sep = "&"
  when before
    url = fmt("{url}{sep}before={before}")
    sep = "&"
  when after
    url = fmt("{url}{sep}after={after}")
    sep = "&"
  when since
    url = fmt("{url}{sep}since={since}")
    sep = "&"
  when $until
    url = fmt("{url}{sep}until={until}")
    sep = "&"
  when response_type
    url = fmt("{url}{sep}response_type={response_type}")
    sep = "&"
  when sort
    url = fmt("{url}{sep}sort={sort}")
  response = http.request(method: "GET", url)
  return response

op typeform-response-delete(form_id: String, included_response_ids: String) -> Any
  description "Permanently delete one or more of a form's responses by their own token. There is no undelete: once deleted, a response's answers are gone. Deletion is asynchronous — a successful call confirms the request was registered, not that the responses are already gone. A non-2xx response is returned as data, not a failure: the vendor's error message is at `/description`, its error code at `/code` in the response body."
  risk "destructive"
  idempotency "non_idempotent"
  effects ["network"]
  expose true

  base = "https://api.typeform.com"
  url = fmt("{base}/forms/{form_id}/responses?included_response_ids={included_response_ids}")
  response = http.request(method: "DELETE", url)
  return response
