# Generated by flux-connectors 0.24.0 — do not edit.
# Provider: vercel
# Regenerate with `flux-connectors build`.

op vercel-projects-list -> Any
  description "List the projects of the team this connector is installed for. The team is pinned at install time and is not a parameter, so every call returns that team's projects and no other account's"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.vercel.com"
  teamId = "{teamId}"
  url = fmt("{base}/v10/projects")
  response = http.request(method: "GET", query: { teamId }, url)
  return response

op vercel-project-get(idOrName: String) -> Any
  description "Get one project of the team this connector is installed for, by its id or name. A project belonging to any other account is a 404 here: the team is pinned at install time and is not a parameter"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.vercel.com"
  teamId = "{teamId}"
  url = fmt("{base}/v9/projects/{idOrName}")
  response = http.request(method: "GET", query: { teamId }, url)
  return response

op vercel-deployments-list(projectId: String) -> Any
  description "List the deployments of the team this connector is installed for, newest first, optionally filtered to one project. The team is pinned at install time and is not a parameter, so every call returns that team's deployments and no other account's"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.vercel.com"
  teamId = "{teamId}"
  url = fmt("{base}/v7/deployments")
  response = http.request(method: "GET", query: { projectId, teamId }, url)
  return response

op vercel-deployment-get(idOrUrl: String) -> Any
  description "Get one deployment of the team this connector is installed for, by its id or its unique hostname. A deployment belonging to any other account fails here: the team is pinned at install time and is not a parameter"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://api.vercel.com"
  teamId = "{teamId}"
  url = fmt("{base}/v13/deployments/{idOrUrl}")
  response = http.request(method: "GET", query: { teamId }, url)
  return response

op vercel-deployment-cancel(id: String) -> Any
  description "Cancel a deployment of the team this connector is installed for, stopping it before it completes; refused with 400 if it already finished (READY, ERROR or CANCELED). The team is pinned at install time and is not a parameter, so this cannot reach a deployment of another account"
  risk "high"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose true

  base = "https://api.vercel.com"
  teamId = "{teamId}"
  url = fmt("{base}/v12/deployments/{id}/cancel")
  response = http.request(method: "PATCH", query: { teamId }, url)
  return response
