# Generated by flux-connectors 0.26.0 — do not edit.
# Provider: zendesk
# Service: help-center
# Regenerate with `flux-connectors build`.

op zendesk-help-center-category-list -> Any
  description "List Help Center categories; this zero-argument read also verifies that the shared Zendesk account and credential can reach the knowledge base"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://{subdomain}.zendesk.com"
  url = fmt("{base}/api/v2/help_center/categories")
  response = http.request(method: "GET", url)
  return response

op zendesk-help-center-section-list -> Any
  description "List Help Center sections across all categories"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://{subdomain}.zendesk.com"
  url = fmt("{base}/api/v2/help_center/sections")
  response = http.request(method: "GET", url)
  return response

op zendesk-help-center-article-list(start_time: Number) -> Any
  description "List Help Center articles, optionally limited to articles updated since a Unix timestamp"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://{subdomain}.zendesk.com"
  url = fmt("{base}/api/v2/help_center/articles")
  response = http.request(method: "GET", query: { start_time }, url)
  return response

op zendesk-help-center-article-get(article_id: Number) -> Any
  description "Get one Help Center article by its numeric id"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://{subdomain}.zendesk.com"
  url = fmt("{base}/api/v2/help_center/articles/{article_id}")
  response = http.request(method: "GET", url)
  return response

op zendesk-help-center-translation-list(article_id: Number) -> Any
  description "List every translation of one Help Center article without exposing unencoded locale filters"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://{subdomain}.zendesk.com"
  url = fmt("{base}/api/v2/help_center/articles/{article_id}/translations")
  response = http.request(method: "GET", url)
  return response

op zendesk-help-center-article-incremental-list(start_time: Number) -> Any
  description "Incrementally list Help Center articles updated since an optional integer Unix timestamp"
  risk "low"
  idempotency "idempotent"
  effects ["read", "network"]
  expose true

  base = "https://{subdomain}.zendesk.com"
  url = fmt("{base}/api/v2/help_center/incremental/articles")
  response = http.request(method: "GET", query: { start_time }, url)
  return response

op zendesk-help-center-article-create(section_id: Number, article: Any) -> Any
  description "Publish a new externally visible Help Center article in one numeric section"
  risk "high"
  idempotency "non_idempotent"
  effects ["write", "network"]
  expose true

  base = "https://{subdomain}.zendesk.com"
  url = fmt("{base}/api/v2/help_center/sections/{section_id}/articles")
  content_type = "application/json"
  payload = { article }
  response = http.request(body: payload, headers: { "content-type": content_type }, method: "POST", url)
  return response
