#!/usr/bin/env python3
"""Regenerate Asterisk ARI event declarations from the pinned normalized document."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
from typing import Any


ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "specs" / "asterisk" / "ari-22.10.1.openapi.json"
SOURCE = ROOT / "specs" / "asterisk" / "api-docs" / "events.json"
PROVIDER = ROOT / "providers" / "asterisk.toml"
BEGIN = "# BEGIN generated:asterisk-events"
END = "# END generated:asterisk-events"


def fail(message: str) -> None:
    raise SystemExit(message)


def kebab(value: str) -> str:
    value = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1-\2", value)
    value = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", value)
    return value.lower()


def toml(value: Any) -> str:
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return repr(value)
    if isinstance(value, list):
        return "[" + ", ".join(toml(item) for item in value) + "]"
    if isinstance(value, dict):
        return "{ " + ", ".join(
            f"{json.dumps(key)} = {toml(item)}" for key, item in sorted(value.items())
        ) + " }"
    fail(f"cannot encode {value!r} as TOML")


def merged_schema(
    name: str,
    schemas: dict[str, dict[str, Any]],
    parents: dict[str, str],
) -> dict[str, Any]:
    lineage: list[str] = []
    cursor: str | None = name
    while cursor is not None:
        if cursor in lineage:
            fail(f"cyclic Asterisk subtype lineage at {cursor}")
        lineage.append(cursor)
        cursor = parents.get(cursor)

    result: dict[str, Any] = {"type": "object", "properties": {}, "required": []}
    for model_name in reversed(lineage):
        schema = schemas[model_name]
        result["properties"].update(schema.get("properties", {}))
        for required in schema.get("required", []):
            if required not in result["required"]:
                result["required"].append(required)
    result["properties"]["type"] = {"const": name}
    if "type" not in result["required"]:
        result["required"].append("type")
    description = schemas[name].get("description")
    if description:
        result["description"] = description
    return result


def dereference(value: Any, schemas: dict[str, dict[str, Any]], stack: tuple[str, ...] = ()) -> Any:
    if isinstance(value, list):
        return [dereference(item, schemas, stack) for item in value]
    if not isinstance(value, dict):
        return value
    reference = value.get("$ref")
    if reference is not None:
        prefix = "#/components/schemas/"
        if not isinstance(reference, str) or not reference.startswith(prefix):
            fail(f"unsupported schema reference {reference!r}")
        name = reference[len(prefix):]
        if name in stack:
            fail(f"recursive Asterisk schema reference: {' -> '.join((*stack, name))}")
        replacement = dereference(schemas[name], schemas, (*stack, name))
        if len(value) == 1:
            return replacement
        if not isinstance(replacement, dict):
            fail(f"referenced schema {name} is not an object")
        replacement.update(
            (key, dereference(item, schemas, stack))
            for key, item in value.items()
            if key != "$ref"
        )
        return replacement
    return {key: dereference(item, schemas, stack) for key, item in value.items()}


def render() -> str:
    normalized = json.loads(SPEC.read_text())
    source = json.loads(SOURCE.read_text())
    schemas = normalized["components"]["schemas"]
    models = source["models"]
    event_names = models["Event"]["subTypes"]
    if len(event_names) != 45 or len(set(event_names)) != 45:
        fail(f"expected 45 unique Event subtypes, got {len(event_names)}")

    parents: dict[str, str] = {}
    for parent, model in models.items():
        for child in model.get("subTypes", []):
            prior = parents.setdefault(child, parent)
            if prior != parent:
                fail(f"{child} has multiple parents: {prior}, {parent}")

    lines = [BEGIN, "# Generated by scripts/generate-asterisk-events.py; do not edit this region."]
    declared_names: list[str] = []
    for wire_value in event_names:
        name = kebab(wire_value)
        declared_names.append(name)
        schema = dereference(merged_schema(wire_value, schemas, parents), schemas)
        lines.extend(
            [
                "",
                "[[events]]",
                f"name = {toml(name)}",
                f"wire_value = {toml(wire_value)}",
                f"description = {toml(schemas[wire_value].get('description', wire_value))}",
                f"schema = {toml(schema)}",
            ]
        )

    lines.extend(
        [
            "",
            "[[channels]]",
            'name = "ari-events"',
            'description = "Receive the complete stream of events for an ARI Stasis application"',
            'transport = "socket"',
            f"events = {toml(declared_names)}",
            'discriminator = { source = "body", name = "type" }',
            "payload_root = true",
            "",
            "[channels.connect]",
            'path = "/events"',
            'auth = [{ credentials = ["asterisk.password"] }]',
            'query = { app = "{app}", subscribeAll = "{subscribe_all}" }',
            END,
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    current = PROVIDER.read_text()
    if BEGIN not in current or END not in current:
        fail(f"{PROVIDER} has no generated event markers")
    before, remainder = current.split(BEGIN, 1)
    _, after = remainder.split(END, 1)
    expected = before + render() + after
    if args.check:
        if expected != current:
            fail(f"generated Asterisk event declarations are stale: {PROVIDER}")
    else:
        PROVIDER.write_text(expected)


if __name__ == "__main__":
    main()
